### ISSUE TITLE
regression in beanproperty path

### ISSUE THREAD

**Issue by emmanueltouzery** [vojtechhabarta/typescript-generator#103]
due to recent changes, bean property path extension doesn't work correctly anymore.

The symptom is that inheritance doesn't work.

we should generate:

    class A extends BFields {}

but with the bug we generate only:

    class A extends Fields {}

We do not properly match the parent class.

One quickfix is to replace inside the function `getBeanModelByType`:

    // current and not working
    if (curBean.getName().equals(originalType)) {

by:

    // quickfix which fixes the issue
    if (curBean.getName() != null
        && originalType != null
        && Objects.equals(curBean.getName().toString(), originalType.toString())) {

Is it possible you fixed `toString` but still have to fix `equals`?

**Comment by vojtechhabarta** [comment]
`Symbol` doesn't need `equals` override because it is created in factory.
Thanks for fixing this issue and improving test.
