### ISSUE TITLE
The POM for cz.habarta.typescript-generator:typescript-generator-maven-plugin:jar:1.14.259 is missing, no dependency information available

### ISSUE THREAD

**Issue by fabm22** [vojtechhabarta/typescript-generator#106]
Hi,

With the version 1.14.259, it seems the pom is missing on the distribution I downloaded
```
[WARNING] The POM for cz.habarta.typescript-generator:typescript-generator-maven-plugin:jar:1.14.259 is missing, no dependency information available
```
 ..could this be repo dependent ? My <dependency> definition: 
```
<dependency>
   <groupId>cz.habarta.typescript-generator</groupId>
   <artifactId>typescript-generator-maven-plugin</artifactId>
   <version>1.14.259</version>
</dependency>
```
Also if I remember correctly it seems it was the same with the 1.14.25**1** I was using before.

Thanks

**Comment by vojtechhabarta** [comment]
Hi,

latest release in this moment is **v1.14.251**. By release I mean version which is uploaded to **[Maven central repository](https://repo1.maven.org/maven2/cz/habarta/typescript-generator/typescript-generator-maven-plugin/)** and has **[release notes](https://github.com/vojtechhabarta/typescript-generator/releases)**.

There are also newer versions on "Releases" page but these are just git tags added automatically by build. I usually remove them when "releasing" new version.

Thanks for using typescript-generator.

**Comment by vojtechhabarta** [comment]
Latest release is now [v1.15.265](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.15.265) 😄
