### ISSUE TITLE
Feature request: add java 8 OptionalDouble, OptionalInt support

### ISSUE THREAD

**Issue by kisdaniel** [vojtechhabarta/typescript-generator#107]
from this java 8 code 
```
public class MyClass {
    final OptionalDouble currentPercent;
}
```

it generates:

```
interface MyClass {
    currentPercent: OptionalDouble;
}

interface OptionalDouble {
    asDouble: number;
    present: boolean;
}
```

but, Jackson maps this stucture to number:
so in json, it looks :
```
{
   currentPercent: 10
}
```

**Comment by vojtechhabarta** [comment]
@kisdaniel thanks for this feature request.
I will add support for `OptionalInt`, `OptionalLong` and `OptionalDouble` if it's not too complicated to implement it in Java 7 compatible way (it shouldn't be).

**Comment by vojtechhabarta** [comment]
Part of [v1.15.265](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.15.265) release.
