### ISSUE TITLE
Emitter Code-Style Configuration for single-quotes

### ISSUE THREAD

**Issue by basst314** [vojtechhabarta/typescript-generator#108]
Is it possible to add a property to specify, whether the emitted code (e.g. enums) should contain single or double-quotes - or even more code-style specific properties?
Instead of having double quotes like
`export type MyEnum = "ONE" | "TWO" | "THREE";`
it would be nice to be able to specify single quotes to be used like:
`export type MyEnum = 'ONE' | 'TWO' | 'THREE';`

Most projects use linting tools which are sensible to the right quote-style being used. Instead of reformating the emitted file, it would be nice to be able to get the right format right away!
Btw: nice work @vojtechhabarta for the generator!

**Comment by vojtechhabarta** [comment]
@basst314 thanks for using typescript-generator and starring the project.

Goal for typescript-generator is to produce "right" format :smile: By "right" format I mean that when official TypeScript formatter with default settings is invoked on generated file it will not change anything (for example invoking Format Document in VS Code).

In general I don't want to complicate the configuration by adding many switches but I will add some switch for the quotes.

BTW Ideally I think generated files should be excluded from linting tool (if possible).

**Comment by basst314** [comment]
Hi @vojtechhabarta , 
Probably you're right about the linting, but thanks anyway for enabling this option!
Good work!

**Comment by vojtechhabarta** [comment]
Part of [v1.15.265](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.15.265) release.
