### ISSUE TITLE
Discriminated Unions pattern support

### ISSUE THREAD

**Issue by doblak** [vojtechhabarta/typescript-generator#109]
I'd find it useful to be able to provide 'kind' string literal (see discriminated unions: https://www.typescriptlang.org/docs/handbook/advanced-types.html)

Example:
```
interface SquareDto {
    kind: "SQUARE";
    size: number;
}
interface CircleDto {
    kind: "CIRCLE";
    radius: number;
}
```

It would be possible to define `public final String kind = "CIRCLE";` or maybe even `public final ShapeKind kind = ShapeKind.CIRCLE;` on dto.

Currently that gets emitted as `kind: string;` or `kind: ShapeKind` in typescript.

What do you think?

Thanks

**Comment by doblak** [comment]
Just noticed #26, I'll lok into it, it might suffice.

**Comment by vojtechhabarta** [comment]
@doblak if you are using Jackson 2 have a look also at support for tagged unions (discriminated unions) #81.

**Comment by doblak** [comment]
That works great. I'd prefer if kind property was emitted to the actual class having @JsonTypeName annotation (not the first non-interface/abstract class), but ... it's probably good enough.

In case you wonder what's the use case ... with [immutables](http://immutables.github.io/) the immutable implementation gets appended the kind field.

Relevant code:
`Jackson2Parser.java:90` 

`/.../ else if (!sourceClass.type.isInterface() && !Modifier.isAbstract /.../`

e.g. if we only add immutable implementation for circle:

```
interface SquareDto {
    kind: "SQUARE";
    size: number;
}
interface CircleDto {
    radius: number;
}
interface ImmutableCircleDto extends CircleDto {
    kind: "CIRCLE";
}
```

**Comment by vojtechhabarta** [comment]
Great to hear that it works for you.

Actually I don't remember all details why I implemented it this way. It was relatively complicated to describe Jackson's kind of dynamic behavior with TypeScript static typing and I am happy that it works for most cases 😉
