### ISSUE TITLE
Generate from downloaded sources (no java project)

### ISSUE THREAD

**Issue by fplini** [vojtechhabarta/typescript-generator#114]
Hi all! I have an angular 2 project (builded using maven) and on generate-sources I download some java files from another module. I want to generate TS from these java files saved into "target/be-sources" directory. Could I configure the plugin to set the dir input files instead of specific class/package?
An example of what I want to do is to set the input sources like this
/target/be-sources/**/*Controller.java

Thanks!

**Comment by vojtechhabarta** [comment]
Hi @fplini, typescript-generator works with compiled classes. It uses Java reflection to get needed information. So you first need to compile the sources.

Here is how you can use _Maven phases_ to achieve it:
- **generate-sources** - download java sources to `target/be-sources` and add this directory to project sources using [build-helper-maven-plugin](http://www.mojohaus.org/build-helper-maven-plugin/usage.html)
- **compile** - compile downloaded sources (normal compile, no extra configuration)
- **process-classes** - run typescript-generator and set input class/es as needed using `<classes>` or `<classPatterns>` parameters

Hopefully it will work for you.

**Comment by fplini** [comment]
Hi and thanks for the reply. So I already have the compiled files but these are in another project. I'm getting these with maven-dependency-plugin and copy that into target directory. So now I have to set the plugin to get as input files the java classes into target directory... but.. the plugin conf provide only 
`<classes>
   <class>cz.habarta.typescript.generator.Person</class>
</classes>`
and not something like 
`
<sourceDir>target/myPathToDownloadedSources</sourceDir>
`

**Comment by vojtechhabarta** [comment]
BTW it is easier to add `be` module to `<dependencies>` in your module and typescript-generator will find these `be` classes.
(If this makes sense in your workflow - `be` module is _jar_ and not _war_ for example.)

**Comment by fplini** [comment]
Uhm maybe I can get the classes without unpack the sources but only using dependency plugin.. BTW could I config all classes into a specific path? Or need I to set each file?

**Comment by vojtechhabarta** [comment]
So lets say you have 2 modules: `be` and `fe`? What is type of these two modules? I mean `<packaging>` element in `pom.xml`?

**Comment by fplini** [comment]
I have two project, the fe and be. 
FE contains 1 pom and the packaging is war
BE contains 2 sub-modules (service and webapp) and a parent pom, the webapp pom packaging is war

Essentially there are 2 webapp (war) one for the be and one for the fe

**Comment by vojtechhabarta** [comment]
I would recommend to run typescript-generator in a _war_ module where you have all your compiled classes (either directly or using `<dependency>`). This is first step.

Once you have this declaration file (`.d.ts`) you can solve how to use it elsewhere. There are few possibilities.

**Comment by fplini** [comment]
Found the solution, exactly this way!

**Comment by vojtechhabarta** [comment]
Great 😄

**Comment by fplini** [comment]
Here again :) Do you know if there are a way to config all classes under a package? 
Ex. com.mypackage.*

**Comment by vojtechhabarta** [comment]
Closing (cleaning up issues).
