### ISSUE TITLE
Option for readonly interfaces?

### ISSUE THREAD

**Issue by IRus** [vojtechhabarta/typescript-generator#119]
I think it would be useful to generate all properties as readonly:

``` typescript
    interface Course {
        readonly id: number;
        readonly name: string;
        readonly code: string;
        readonly description: string;
    }
```

**Comment by vojtechhabarta** [comment]
I was thinking that marking all properties as `readonly` does not make sense.
But since it seems to be useful I will implement it and I will add `declarePropertiesAsReadOnly` parameter (similar to existing `declarePropertiesAsOptional` parameter).

**Comment by vojtechhabarta** [comment]
`declarePropertiesAsReadOnly` parameter is part of [v1.19.294](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.19.294).

**Comment by IRus** [comment]
@vojtechhabarta great work, thanks :+1:
