### ISSUE TITLE
Using @JsonUnwrapped

### ISSUE THREAD

**Issue by ramgom** [vojtechhabarta/typescript-generator#122]
Hello all thanks a lot for this helpful plugin. I've been wondering if there is a way to set up the plug in to generate proper typescript when @JsonUnwarpped annotation is used. Right now is not creating a flat typescript interface, it creates the nested classes instead.

**Comment by vojtechhabarta** [comment]
Part of [v1.20.300](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.20.300) release.
