### ISSUE TITLE
Support Varied Project Structures?

### ISSUE THREAD

**Issue by ollwenjones** [vojtechhabarta/typescript-generator#123]
This project is working really well with some caveats.
I might just not know enough about how to use it, but it seems like all the methods
to tell the plugin which Java classes to generate assume the classes to convert are part of the same
project/module as the pom that runs the plugin, correct?

```shell
parent/
  |_ app/
    |- pom.xml                # runs this plugin
    |- src.main...restAPI/    # Java classes to convert to TypeScript
    |_ webapp/client/         # tightly coupled UI consuming TypeScript
```
However in my case, the UI is treated as a _separate_ project from the REST API,
(Though they are part of the same parent maven build)

```shell
parent/
  |- server/
  |  |- pom.xml               # runs this plugin
  |  |- src.main...restAPI/   # Java classes to convert
  |  |_ webapp/ui-host        # hosts UI in deployment
  |_ ui/
     |- types/                # depends on generated TypeScript
     |- core/                 # depents on /types
     |- app1/                 # depents on /types
     |_ app2/                 # depents on /types
    
```

If `ui/types` managed TypeScript generation it could drive which server(s) API(s) it cares about.
It would also eliminate a circular dependency I'm working around between
the server project which hosts UI after compilation, and the types.

Right now I don't see a way to tell it to reach out and across to the server to look for
classes or a Jax-RS application, or to allow the parent maven project to reach into the
server to look for the Jax-RS application.

**Comment by vojtechhabarta** [comment]
What is packaging of your `server` module and `ui` module? Or is `ui` just directory without pom.xml?

If your Java classes are in module with `<packaging>jar</packaging>` you can declare dependency on this module from another module and run typescript-generator in dependent module. It will have access to classes from the first module.

Basically I think there are following **layers**, each depending on previous one:
- Java classes
- generated TypeScript declarations
- UI TypeScript code
- UI host

and it is a question how to organize this in Maven modules.

I you want to have UI separate project I would try to have these **modules**:
- `rest/core` with `jar` packaging containg java code
- `ui` with dependeny on `rest/core`, runs typescript-generator, can have `pom` packaging
- `server/host` with `war` or `jar` packaging running/hosting REST and UI, depends on previous two modules

What do you think?

**Comment by ollwenjones** [comment]
I think you are exactly correct. That's what I would _like_ to do. Right now we have a legacy UI inside the project with the `rest api` and the `ui host` - to be more forthcoming, they are a huge GWT app. This wouldn't be a problem for the new UI, except we are hoping to incrementally rewrite off of GWT with it. Right now I'm working around this with npm scripts (UI guy will use UI tools.) I'm resisting letting the new UI get moved inside the GWT app, but we'll see what the rest of the team says. 😉 

Thanks for the help / feedback. I think I have a better understanding now.
