### ISSUE TITLE
Generate TS class and instatiate it

### ISSUE THREAD

**Issue by fplini** [vojtechhabarta/typescript-generator#125]
Hi all! I'm using this plugin to generate ts classes (frontend module) from java classes (backend module).
Al works fine but I want to know if there is the possibility to generate a class where the inside objecta are already instatiated.
To let you understand I have a class "Car" that contains a field "engine" of type Engine" (another class), so after the plugin is executed I'll get this:
`export class Engine {
    model: string;
}
export class Car {
    engine: Engine;
}`

what instead I really want is this 
`export class Car {
    engine: Engine = new Engine();
}`

Is this possible? 

Thanks all,
have a good day

Fabrizio

**Comment by vojtechhabarta** [comment]
@fplini unfortunately this is not possible.

I would recommend to create factory function that could create an instance and set all needed values or create derived class that could do the same in constructor.

**Comment by vojtechhabarta** [comment]
Closing the issue - inactive for some time.
