### ISSUE TITLE
Upgrade io.github.lukehutch:fast-classpath-scanner to version 2.0

### ISSUE THREAD

**Issue by nedjs** [vojtechhabarta/typescript-generator#128]
I was having some problems with the fast-classpath-scanner scanning my projects classpath on a few jars. It was throwing IndexOutOfBoundsExceptions. I tested upgrading the depenency to 2.0.17 and it worked just fine.

I propose an upgrade to 2.0, I can put in a pull request for this if you like. I will wait to put it in until you take a look at the change notes to ensure there are no unintended side effects of this upgrade in terms of your own libraries support. (Although all tests passed with the upgrade as well)

Major release notes for 2.0 are found here https://github.com/lukehutch/fast-classpath-scanner/releases/tag/fast-classpath-scanner-2.0.0

**Comment by vojtechhabarta** [comment]
@nedjs thanks for suggesting fast-classpath-scanner upgrade and testing it!
I also tried version 2.0.17 and so far it looks good so I committed it.

**Comment by vojtechhabarta** [comment]
Part of [1.22.307](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.22.307) release.

**Comment by nedjs** [comment]
Great thank you!
