### ISSUE TITLE
Exclude Enum or InnerEnum

### ISSUE THREAD

**Issue by fplini** [vojtechhabarta/typescript-generator#129]
Hi all, 
I'm having a problem on my plugin due to more "Status" enum into some model class (java).
I have about 3 model classes that have an inner enum Status.
When I run the plugin I get "Multiple classes are mapped to 'Status' name"
I can both ignore enum classes or trasform the enum name into 'ClassNameEnumName'.

How I can do this?
Thx
Fabrizio

**Comment by vojtechhabarta** [comment]
Hi Fabrizio,
here are examples for Maven.
#### Exclude individual classes
``` xml
<excludeClasses>
    <class>com.package.ClassA$Status</class>
    <class>com.package.ClassB$Status</class>
    <class>com.package.ClassC$Status</class>
</excludeClasses>
```
#### Exclude classes using globing pattern
``` xml
<excludeClassPatterns>
    <pattern>com.package.*$Status</pattern>
</excludeClassPatterns>
```
#### Rename classes
``` xml
<customTypeNaming>
    <naming>com.package.ClassA$Status:ClassAStatus</naming>
    <naming>com.package.ClassB$Status:ClassBStatus</naming>
    <naming>com.package.ClassC$Status:ClassCStatus</naming>
</customTypeNaming>
```

**Comment by fplini** [comment]
Hi and thanks! 
I think this solution
`<customTypeNaming>
    <naming>com.package.ClassA$Status:ClassAStatus</naming>
    <naming>com.package.ClassB$Status:ClassBStatus</naming>
    <naming>com.package.ClassC$Status:ClassCStatus</naming>
</customTypeNaming>`
could be the better solution but is there a common pattern to avoid to set each class?

**Comment by vojtechhabarta** [comment]
You can try to use `<customTypeNamingFunction>` feature.

**Comment by vojtechhabarta** [comment]
And now you can also use `<mapPackagesToNamespaces>` feature (release [1.24.314](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.24.314)).
