### ISSUE TITLE
Consistent ordering of object properties

### ISSUE THREAD

**Issue by jollytoad** [vojtechhabarta/typescript-generator#130]
Hi, this is a great tool btw, I'm finding it very useful. Although I have one minor gripe atm, as I'm storing the generated d.ts files in the git repo with the src for reference, I'm finding that everytime it runs the order of object properties seems to be different. Would there be some way to force consistent ordering?
Thanks.

**Comment by jollytoad** [comment]
Bah, sorry, just found the sortDeclarations param in the maven plugin docs!

**Comment by vojtechhabarta** [comment]
Hi, yes, you can use `sortDeclarations` parameter to sort interface and properties alphabetically.
Example for Maven:
``` xml
<configuration>
    <sortDeclarations>true</sortDeclarations>
</configuration>
```
BTW I think Jackson2
- sorts properties created from **fields** by their original order in source file
- for properties created from **getters** it tries to find corresponding field and use it for ordering

So in many cases default ordering works well.

**Comment by jollytoad** [comment]
That's useful to know about Jackson2 thanks - although i'm stuck with Jackson1 atm, which I'm guessing doesn't do that. sortDeclarations is doing the trick now though.
Thanks for the quick reply and great work.
