### ISSUE TITLE
declaring optional properties

### ISSUE THREAD

**Issue by jechlin** [vojtechhabarta/typescript-generator#131]
Hi - I'm quite new to this so perhaps I am missing something obvious.

I'm looking for a way to declare a property as optional (https://www.typescriptlang.org/docs/handbook/interfaces.html#optional-properties).

I see that I can use _declarePropertiesAsOptional_ , which makes them all optional, and @Transient, to exclude them, but I can't find a way of making particular properties optional.

Thanks in advance

**Comment by jechlin** [comment]
Duh, found optionalAnnotations 2 seconds later.
Thanks a lot.

**Comment by vojtechhabarta** [comment]
Hi, great to hear that it works for you.

BTW why do you have symbols of former Soviet Union (hammer and sickle etc.) in your profile picture?
Troops of this former state [invaded Czechoslovakia](https://en.wikipedia.org/wiki/Warsaw_Pact_invasion_of_Czechoslovakia) (my country) in 1968 and stayed here for more than 20 years. This destroyed our freedom and democracy.

**Comment by jechlin** [comment]
It does work for me, appreciate your work on it.

Yes, I was aware of the history of the Czech Rep, and have visited your country several times. I needed a big red star, the hammer and sickle was incidental other than I like the picture.

I appreciate though it can cause offence and might seem insensitive, and I plan to change it within the next 3 weeks.

While we are talking - is special treatment given to @class properties, ie the one usually used for polymorphic types in jackson? Because for me it's generating declarations with the short class name, rather than "string".

Thanks again.

**Comment by vojtechhabarta** [comment]
Yes, there is special treatment for Jackson 2 polymorphic types. See [Tagged unions](https://github.com/vojtechhabarta/typescript-generator/pull/81). It can be disabled using `disableTaggedUnions` parameter.

**Comment by jechlin** [comment]
Awesome, thank you.

Avatar updated by the way, takes a while to percolate.

**Comment by vojtechhabarta** [comment]
Thank you too 😄
