### ISSUE TITLE
Nashorn, TypeScript generator compatibility

### ISSUE THREAD

**Issue by dmdeklerk** [vojtechhabarta/typescript-generator#134]
Hi, this is more of question than a bug.

I could not easily find a configuration that generates ts interfaces from java classes/interfaces which include both all java (parameterized) method calls, as well all property getters translated to ts interface properties.

Use case is where we want to generate ts interfaces for a TypeScript app that runs (after compilation) in the Nashorn js engine, since Nashorn exposes the java classes to javascript we figured we could create typings for our own application classes as well as for java's built-ins.

Looking at https://github.com/vojtechhabarta/typescript-generator/blob/09562def86a10e0aeec3f5153c22fc1b6303c095/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/parser/MethodModel.java its clear that typescript-generator basically has all the tools needed for such functionality, hopefully i've looked over it. 
Thanks.

**Comment by vojtechhabarta** [comment]
Hi, currently this is not supported.

Originally typescript-generator processed just data classes (for JSON mapping) and later I implemented support for JAX-RS client (added `MethodModel`).

You are right typescript-generator now probably has good enough model and emitter for this feature. So I think it is needed to implement `ModelParser` specifically aimed for Nashorn which would create model that would represent Java objects in a way how Nashorn provides them to JavaScript code.

Do you want to try to implement this parser? Something like `JavaInNashornParser`, `JavaForNashornParser`, `NashornJavaParser` ... Probably there would be some functionality shared with `Jackson2Parser` but maybe it is better to start from scratch.

**Comment by dmdeklerk** [comment]
Hi, thanks for your quick reply.

Yes I would like to try and implement this, cloned your repo and want to try this quick, cant be that much work. 

So your suggestion is to create a new parser, any other tips maybe?

A probably familiar project is https://www.npmjs.com/package/ts-java, its generated ts typings have a nice mapping from java to ts types which you can see below. I'd think those are sufficient to add as a static addition to the output file. Although created for node-java initially they seem to match the Nashorn mappings.

```typescript
  // Node-java has special handling for methods that return long or java.lang.Long,
  // returning a Javascript Number but with an additional property longValue.
  export interface longValue_t extends Number {
    longValue: string;
  }

  // Node-java can automatically coerce a javascript string into a java.lang.String.
  // This special type alias allows to declare that possiblity to Typescript.
  export type string_t = string | Java.java.lang.String;

  // Java methods that take java.lang.Object parameters implicitly will take a java.lang.String.
  // But string_t is not sufficient for this case, we need object_t.
  export type object_t = Java.java.lang.Object | string | boolean | number | longValue_t;

  // Java methods that take long or java.lang.Long parameters may take javascript numbers,
  // longValue_t (see above) or java.lang.Long.
  // This special type alias allows to declare that possiblity to Typescript.
  export type long_t = number | longValue_t | Java.java.lang.Long;

  // Handling of other primitive numeric types is simpler, as there is no loss of precision.
  export type boolean_t = boolean | Java.java.lang.Boolean;
  export type short_t = number ;
  export type integer_t = number ;
  export type double_t = number ;
  export type float_t = number ;
  export type number_t = number ;

  export interface array_t<T> extends Java.java.lang.Object {
    // This is an opaque type for a java array_t T[];
    // Use Java.newArray<T>(className, [...]) to create wherever a Java method expects a T[],
    // most notably for vararg parameteters.
    __dummy: T;
  }

  export type object_array_t = array_t<Java.java.lang.Object> | object_t[];
```
Would you be available for hints/tips while i try and implement this today and tomorrow?

**Comment by dmdeklerk** [comment]
So if i get this correct, the order is to create a ModelParser, register that with TypeScriptGenerator.createModelParser(), is `nashorn` a good enum name for that?

The ModelParser (named NashornJavaParser) implements the NashornJavaParser.parseBean(SourceType<Class<?>>) which returns a BeanModel which I have to create and populate in parseBean.

Now when BeanModel is properly populated with all class properties and methods and parameters there is other, generic code, in typescript-generator that will take this BeanModel and create the required TypeScript file (be that global, module or the other one).

**Comment by vojtechhabarta** [comment]
I will not be online during the day but I should be able to help you in the evening.

Yes, that's exactly how typescript-generator works and yes I think `nashorn` is good name for this.

`ModelParser` cannot currently add static TypeScript content to the output. You can then implement `EmitterExtension` which can add whatever it wants using `writer.writeIndentedLine()` or `Emitter.writeTemplate` (see `AxiosClientExtension` for example).

It is possible to create a file with some declarations and use [importDeclarations](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#importDeclarations) parameter to import this file (if you are generating module).

But I think it would be better to leave Java primitive types mapping to `DefaultTypeProcessor` which maps them directly to TypeScript types.

You can also implement `TypeProcessor` or use [customTypeMappings](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#customTypeMappings) parameter.

**Comment by dmdeklerk** [comment]
Also it seems an addition to ModelCompiler.javaToTypeScript(Model) is required in a section called '// nashorn' that basically does what createJaxrsInterfaces(...) or better processJaxrsMethods(...) does.

Thanks for your pointers, I think i got the idea how to tackle this now. I've cloned your repo here https://github.com/dmdeklerk/typescript-generator.

**Comment by dmdeklerk** [comment]
Having trouble only fully understanding the following concepts:

1. what is/are PropertyModel.PullProperties
2. how do getDiscriminantProperty and getDiscriminantProperty work

Questions of course being related to adding nashorn parser which extends ModelParser

**Comment by dmdeklerk** [comment]
Made some progress, hopefully it can be completed tomorrow. Your advise would be very welcome https://github.com/dmdeklerk/typescript-generator/commits/dennis

**Comment by vojtechhabarta** [comment]
Answers to your questions:
1. `PropertyModel.PullProperties` is used to implement support for `@JsonUnwrapped` Jackson2 annotation. It pulls properties from nested object one or more levels up (http://fasterxml.github.io/jackson-annotations/javadoc/2.0.0/com/fasterxml/jackson/annotation/JsonUnwrapped.html).
2. Discriminant is used in [tagged union types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions). Here is typescript-generator support for them: #81.

I think you don't need these two features.

**Comment by dmdeklerk** [comment]
Hi, thanks for your answers and comments on my commits. 
You are correct in reflection method, plain java reflection is better when dealing with mapping Nashorn.

Now running test https://github.com/dmdeklerk/typescript-generator/blob/3c1197df08191e4182870870ac882178f8d87b3d/typescript-generator-core/src/test/java/cz/habarta/typescript/generator/NashornJavaParserTest.java#L58 gives as output 
http://paste.ubuntu.com/24433946/. Which is actually pretty close to what we are after.

To get actual parameter names to methods some tinkering with javac arguments was needed to have those available to reflection in the first place (see http://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Parameter.html#getName--)

Also i had to opt for using source class declared methods and fields, instead of all inherited fields and methods. What is wanted of course is a set of interfaces in the output that actually declare and extend their base classes. See this part for how reflection is done now, i think solution to proper extending would be there https://github.com/dmdeklerk/typescript-generator/blob/81661e5d0bf5962bf9e13fa22dbfccd7dc18b67e/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/parser/NashornJavaParser.java#L29

Any pointers on how to get proper extending of classes working would be helpful.

**Comment by dmdeklerk** [comment]
Just tried this https://github.com/dmdeklerk/typescript-generator/commit/2cfe504806f75c5f6c174ca49a63af6788371dce
Which now gives http://paste.ubuntu.com/24433996/ or better put, it does seem to support super classes.

I'll see how things work when i compile the whole package and use again as gradle plugin (after probably adding the nashorn type somewhere).

Comments always welcome.

**Comment by dmdeklerk** [comment]
What would also help bring out the power of TypeScript used with Nashorn is to auto convert types like  java.util.function.Consumer<string> to their SAM (single abstract method) form. What Nashorn does with a param type like java.util.function.Consumer<string> is auto convert a 'function (string) {}' to an instance of Consumer.

For TypeScript this gets slightly better even where we can write:

```typescript
interfaceA.methodAcceptingConsumer((arg: string)=>{
});
```
Right now we have this output

```typescript
    namespace cz.habarta.typescript.generator.NashornJavaParserTest {
        export interface MyDummyBean extends cz.habarta.typescript.generator.NashornJavaParserTest.MyDummyBeanSuper {
            boolenproperty: boolean;
            stringproperty: string;
            iteratorgetter: java.util.Iterator<any>;
            someMethod(nameArg: string, someNumArg: number, arg3: string[]): string;
            getIteratorMethod(x: string): java.util.Iterator<cz.habarta.typescript.generator.NashornJavaParserTest.OtherDummy>;
            callbackMethod(consumer: java.util.function.Consumer<string>): void;
        }
    }
```
Better would be if the method callbackMethod would have a typescript type of '(arg:string)=>void |  java.util.function.Consumer<string>'.

Any idea on how to best do that?

**Comment by vojtechhabarta** [comment]
Hi,

**Method parameter names**: I also set `-parameters` argument to javac to get names of parameters. `java.lang.reflect.Parameter` is Java 8 class and my goal for typescript-generator is to support last two major versions of Java so currently it means to support Java 1.7. If you plan to make PR eventually you can use `cz.habarta.typescript.generator.util.Parameter` which calls `Parameter.getName()` using reflections if available.

**Inherited members**: parser for Jackson2 beans gets all properties (declared and inherited) from Jackson2 library. `ModelCompiler` then removes inherited properties and adds implemented properties (https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/compiler/ModelCompiler.java#L46). I think you don't need this mechanism since you are using `getDeclaredXXX` methods and only get members added in actual class. You just need to fill `BeanModel.parent` and `BeanModel.interfaces`. But I am not sure 😄 

**Consumer**: I think it would be nice to generate following declarations but I am not sure if it would work as needed:
``` typescript
interface MyDummyBean {
    callbackMethod(consumer: java.util.function.Consumer<string>): void;
}
interface Consumer<T> {
    (value: T): void;
}
```
First part (`callbackMethod` signature) is for free but `Consumer` interface is harder. We would need:
1. detect that class/interface is SAM - maybe we could just use `@FunctionalInterface` annotation
2. enhance model - maybe we could somehow reuse `MethodModel` just without name
3. enhance `Emitter` model and `Emitter` itself

**Comment by dmdeklerk** [comment]
Hi, 

I would love to contribute to your project more but am extremely short on time. 

The hours spend on this already luckily were not in vain, also very happy to see that my first instinct was correct, which was that your project is probably the best engineered (pure) Java to TypeScript engine out there.

What I would love to see is that the current changes I made would land in your project, when this happens is up to you of course, its clear that your project is well very structured and that you cant just simply accept any contribution. 

What I need however is to get on with my own work and make good the time spend on adding Nashorn support to typescript-generator.

The improvements mentioned in your last comment would serve our intended purpose very well and we'll definitely be making those in the future either ourselves or we'll be looking to hire talent to add those. 

Looking at what was produced this far, would you consider adding that to typescript-generator already? My github-pull-request-making skills are not my best quality which is why I ask.

**Comment by vojtechhabarta** [comment]
Hi,
thanks for your good evaluation of my project.

Nashorn support would be nice addition to typescript-generator but it's fine that you have just your fork. This open source diversity is a good thing. Currently I also don't want to invest in production quality nashorn support because I am not using it and I don't have experience with it. I thing your prototype is useful and maybe situation will change in the future and typescript-generator will get support for nashorn.

**Comment by dmdeklerk** [comment]
Ok, thanks for your help, created a pr for your reference https://github.com/vojtechhabarta/typescript-generator/pull/137

**Comment by dmdeklerk** [comment]
One more question:
Do you by any chance recognize the following error or have an idea on where to look for a solution?

Error in gradle build:

```
Parsing 'java.security.DomainCombiner' used in 'AccessControlContext.domaincombiner'
Warning: Unsupported type 'A[]' used in 'Stream.toArray'
:generateTypeScript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateTypeScript'.
> java.lang.NullPointerException (no error message)
```

Location of null pointer ex: https://github.com/dmdeklerk/typescript-generator/blob/nashorn/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/DefaultTypeProcessor.java#L75

**Comment by dmdeklerk** [comment]
Another question:

The generated generic identifier seems to be wrong. Please see example of generated typescript, notice the return type of `valueOf(arg0: any, arg1: string): T;` what it should say is `E` I believe.

```typescript
    namespace java.lang {
        export interface Enum<E> extends java.lang.Comparable<E>, java.io.Serializable {
            declaringClass: any;
            name(): string;
            equals(arg0: any): boolean;
            toString(): string;
            hashCode(): number;
            compareTo(arg0: any): number;
            compareTo(arg0: E): number;
            valueOf(arg0: any, arg1: string): T;
            ordinal(): number;
        }
    }
```
How is this handled in typescript-generator or how could i fix that?

**Comment by dmdeklerk** [comment]
Will look at it later, current generated result after applying the following exclusions.

```closure
generateTypeScript {
  outputFile = 'build/java.heatledger.d.ts'  
  classPatterns = [
    'com.heatledger.scripting.ScriptGlobalBinding'
  ]
  excludeClassPatterns = [
    'java.util.stream.Stream',
    'java.lang.Class',
    'java.lang.Object',
    'java.util.stream.IntStream',
    'java.lang.Enum',
    'java.util.stream.LongStream',
    'java.util.stream.DoubleStream',
    'java.util.Spliterator'
    
  ]
  jsonLibrary = 'nashorn'
  outputKind = 'global'
  namespace = 'Java';
  mapPackagesToNamespaces = true
  referencedFiles = [
    'java.heatledger.referenced.d.ts'
  ]
}
```
Output: https://gist.github.com/dmdeklerk/23dd8f05b1d75d8805af09ab07d23781

**Comment by dmdeklerk** [comment]
https://github.com/vojtechhabarta/typescript-generator/pull/138

**Comment by vojtechhabarta** [comment]
I think the warning is there because typescript-generator doesn't support generic arrays yet. I will implement it.

NullPointerException is probably thrown as a consequence of this unsupported type.

**Comment by vojtechhabarta** [comment]
Generic arrays: https://github.com/vojtechhabarta/typescript-generator/commit/9ea922c2ec51e8174a714730bb7ef2553c6165a8

**Comment by vojtechhabarta** [comment]
Closing old issues/PRs after v2 release.
