### ISSUE TITLE
When outputKind is global I get error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.

### ISSUE THREAD

**Issue by haynesgt** [vojtechhabarta/typescript-generator#136]
I have `<outputKind>global</outputKind>` and  `<mapPackagesToNamespaces>true</mapPackagesToNamespaces>`

## Actual
```
namespace com.me.core.Service {
    export type ServiceType = "UNKNOWN" | "DELIVERED" | "RECEIVED";
}
```
### Error
Either TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.
Or I set the output file to index.ts and get cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.24.314:generate failed: Declaration file must have 'd.ts' extension:

## Expected
This would be nice:
```
declare namespace com.me.core.Service {
    export type ServiceType = "UNKNOWN" | "DELIVERED" | "RECEIVED";
}
```
While the ambientModule option adds a `declare namespace` around everything, I don't want to have anything before `com` when I reference the types (I want `com.me.core.Service`, not `java.com.me.core.service`, etc).
## Workarounds
I can set `<outputFile>index.ts</outputFile>` and `<outputFileType>implementationFile</outputFileType>` to avoid the typescript error

**Comment by vojtechhabarta** [comment]
Thanks for detailed description of the problem. I will fix it, it should work as you mentioned.

Just to clarify:
`<outputFileType>declarationFile</outputFileType>` generates file with `.d.ts` extension
`<outputFileType>implementationFile</outputFileType>` generates file with `.ts` extension

Here is Wiki page that describes how modules and namespaces are handled in typescript-generator: http://www.habarta.cz/typescript-generator/doc/ModulesAndNamespaces.html, but it wasn't yet updated for `<mapPackagesToNamespaces>` feature which has been added recently.

**Comment by haynesgt** [comment]
It works great.

**Comment by vojtechhabarta** [comment]
Closing old issues after release.
