### ISSUE TITLE
Enum as Object issues

### ISSUE THREAD

**Issue by haynesgt** [vojtechhabarta/typescript-generator#140]
I have enums that are annotated with `@JsonFormat(shape= JsonFormat.Shape.OBJECT`

My enums are like this:
```
@JsonFormat(shape= JsonFormat.Shape.OBJECT)
public enum StatusType {
        GOOD(0, "Good"),
        FULL(1, "Full");
        private int code;
        private String label;
        private StatusType(int code, String label) {
            this.label = label;
            this.code = code;
        }
	public int getCode() { return code; }
	public String getLabel() { return label; }
}
```

In the HTTP response they look like this:
```
{
    code: 0,
    label: "GOOD"
}
```

However, my generated Typescript looks like this:
```
    export type StatusType = "GOOD" | "FULL";
```

Also, excluding the class does not work. StatusType is still there.

I'm looking for a workaround right now.

**Comment by vojtechhabarta** [comment]
Universal workaround is to exclude class which is not mapped correctly. Excluded class is then mapped to `any`.

I am not sure why excluding doesn't work in your case. I added test(https://github.com/vojtechhabarta/typescript-generator/commit/eed856e7413f96ca62aed069276be27121fc3efa) specifically for enum class and it works.

**Comment by haynesgt** [comment]
sorry -- I was using 1.24.314 but fix is in 1.24.320

**Comment by vojtechhabarta** [comment]
Build v1.24.320 adds just one test and it is not released to maven central repository.
Anyway, does it mean that exclude workaround now works for you?

**Comment by vojtechhabarta** [comment]
I implemented support for enums with `JsonFormat.Shape.OBJECT` (release [1.25.322](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.25.322)).
Could you please try it?

**Comment by haynesgt** [comment]
It works!

**Comment by vojtechhabarta** [comment]
Closing old issues after release.
