### ISSUE TITLE
Export constants

### ISSUE THREAD

**Issue by tomasj** [vojtechhabarta/typescript-generator#141]
Hi Vojta,
what I got is not really an issue. I need to export (public static final) constants alongside my interfaces to TS. Is it possible somehow? And if not, could you please advice me the right direction, where should I start with implementing of this functionality?

**Comment by vojtechhabarta** [comment]
Hi,
currently this is not possible. Do you have some example (Java class and corresponding TypeScript file) of what you would like to achieve? Maybe there is some workaround.

**Comment by tomasj** [comment]
Of course, in JAVA there is a class:

```
public final class ApiUriConstants {
    public static final String API_EVENT = "/api/event";
    public static final String API_USER = "/api/user";
}
```
 In Typescript, curretly generated interface looks like this:
```
export interface ApiUriConstants {

}
```
But instead, I would like to get something like this:
```
export class ApiUriConstants {
    public static readonly API_EVENT = "/api/event";
    public static readonly API_USER = "/api/user";
}
```
Important is that generated entity is class instead of interface, and it's member static variables are preserved.

**Comment by vojtechhabarta** [comment]
So these constants will be used as a value where some `string` value is required, right?

Would it be possible to change these constants into enum? This would provide better type safety and typescript-generator can be configured to generate enum constants.

Here is sample Maven configuration for enum constants:
``` xml
<configuration>
    <outputFileType>implementationFile</outputFileType>
    <extensions>
        <extension>cz.habarta.typescript.generator.ext.EnumConstantsExtension</extension>
    </extensions>
</configuration>
```

BTW you can generate classes (instead of interfaces) using following configuration parameter:
``` xml
<configuration>
    <outputFileType>implementationFile</outputFileType>
    <mapClasses>asClasses</mapClasses>
</configuration>
```

**Comment by vojtechhabarta** [comment]
Closing old issues after release. Feel free to reopen if needed.

**Comment by diachok** [comment]
I need similar functionality. @vojtechhabarta, based on your comments, it is possible to solev this issue via enum. Ok, could you give more details?
I've implemented next enum:
```
public enum Urls {
    URL1("/url/1"),
    URL2("/url/2");
    Urls(String s) {
        this.url = s;
    }
    private String url;
    public String getUrl() {
        return url;
    }
    public void setUrl(String url) {
        this.url = url;
    }
}
```
but it is converted into TS as this:

```
export const enum 0Urls {
    URL1 = "URL1",
    URL2 = "URL2",
}
```

**Comment by diachok** [comment]
@tomasj How have you solved this issue?

**Comment by vojtechhabarta** [comment]
It is possible to use `@JsonProperty` or `@JsonValue` annotations.
See some examples in [TestEnums.java](https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-core/src/test/java/cz/habarta/typescript/generator/TestEnums.java) and [EnumTest.java](https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-core/src/test/java/cz/habarta/typescript/generator/EnumTest.java) if you find something useful for you.

**Comment by jjzazuet** [comment]
+1 for some way to assign alternate values other than the use of `@JsonValue`. Thanks!

**Comment by vojtechhabarta** [comment]
@rajesh99, @jjzazuet I just released version [2.11.472](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.11.472) which adds possibility to use `toString()` method instead of `name()` to define enum values (#300). I think it might be useful in your cases.

Here is Maven configuration snippet:
``` xml
<configuration>
    <jsonLibrary>jackson2</jsonLibrary>
    <jackson2Configuration>
        <enumsUsingToString>true</enumsUsingToString>
    </jackson2Configuration>
    <mapEnum>asEnum</mapEnum>
    ...
</configuration>
```

**Comment by jjzazuet** [comment]
@vojtechhabarta thanks! I'll give it a shot and report back!

**Comment by jjzazuet** [comment]
@vojtechhabarta is there a configuration snippet example available for Gradle? I'm also using the plugin on Gradle based code base. This rocks, thanks again!

**Comment by jjzazuet** [comment]
@vojtechhabarta never mind, I was able to figure it out:

```
jsonLibrary = 'jackson2'
jackson2Configuration = [
  'enumsUsingToString': true
]
```
Thanks!

**Comment by vojtechhabarta** [comment]
@jjzazuet thanks for sharing Gradle configuration snippet.
