### ISSUE TITLE
java annotation to ignore fields

### ISSUE THREAD

**Issue by emreavsar** [vojtechhabarta/typescript-generator#143]
hi,

i really enjoy the plugin and def. will use it in the current project.

i'm curious whether it is possible to ignore certain attributes of a class?

examples could be:
```
public class Person {
    private String name;

    // only needed in backend so i don't want to publish this.
    private String doNotExposeMe;
}
```

result would be here:
```
export interface Person {
    private name: string;

    // doNotExposeMe should not be in the typescript definition
}
```

cheers
emre

**Comment by vojtechhabarta** [comment]
Hi @emreavsar, are you using Jackson2 for JSON serialization?

If yes, add `<jsonLibrary>jackson2</jsonLibrary>` configuration parameter to typescript-generator. In this case it will get list of properties from Jackson library. You can then use Jackson 2 annotations to define properties:
- `@JsonProperty` to include property
- `@JsonIgnore` to ignore property
- `@JsonAutoDetect` to specify which members should be considered as property

**Comment by emreavsar** [comment]
Oh my bad, works perfectly and makes sense anyway to not introduce custom annotations when there are already some for json ignore.

Great thanks!
