### ISSUE TITLE
Running typescript generator fails with a configuration error

### ISSUE THREAD

**Issue by JamesKelley** [vojtechhabarta/typescript-generator#146]
Hi.

I'm  having trouble getting Typescript generator working.  

[INFO] 
[INFO] --- typescript-generator-maven-plugin:1.25.322:generate (default-cli) @ cip_server ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.395 s
[INFO] Finished at: 2017-06-06T10:50:05-04:00
[INFO] Final Memory: 21M/219M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.25.322:generate (default-cli) on project cip_server: The parameters 'outputKind', 'jsonLibrary' for goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.25.322:generate are missing or invalid -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException

But as you can clear see from the pom.xml snippet, both outputKind and jsonLibrary have both be configured

[pom.xml.txt](https://github.com/vojtechhabarta/typescript-generator/files/1055437/pom.xml.txt)

???

Please see attached for full runtime log:

[tgSimpleRuntimeError.txt](https://github.com/vojtechhabarta/typescript-generator/files/1055413/tgSimpleRuntimeError.txt)

Please see the attached for a detailed error log (using -X switch):

[tgDetailedErrorLogging.txt](https://github.com/vojtechhabarta/typescript-generator/files/1055411/tgDetailedErrorLogging.txt)

Thank you

**Comment by vojtechhabarta** [comment]
Hi, there are two options:

1. Run some maven build phase which includes typescript-generator - for example `mvn process-classes` or `mvn install`...

2. If you want to run it using `mvn typescript-generator:generate` you need to move `<configuration>` element two levels up (under `<plugin>` element). See [sample-maven/pom.xml](https://github.com/vojtechhabarta/typescript-generator/blob/master/sample-maven/pom.xml#L44).
I also updated README.

**Comment by vojtechhabarta** [comment]
Closing issues after release. Feel free to reopen if needed.
