### ISSUE TITLE
Problem using <classPatterns>on maven 3.3.9  java 8

### ISSUE THREAD

**Issue by Ixoh** [vojtechhabarta/typescript-generator#147]
Hello,
I try to use your plugin on a simple maven module under spring boot which contains DTO. 
Everything work fine when I use it with **classes** in configuration, however I get errors when I try to use it with **classPatterns**

```
<dependencies>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		<dependency>
			<groupId>cz.habarta.typescript-generator</groupId>
			<artifactId>typescript-generator-maven-plugin</artifactId>
			<version>1.25.322</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>cz.habarta.typescript-generator</groupId>
				<artifactId>typescript-generator-maven-plugin</artifactId>
				<version>1.25.322</version>
				<executions>
					<execution>
						<id>generate</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<phase>process-classes</phase>
					</execution>
				</executions>
				<configuration>
					<jsonLibrary>jackson2</jsonLibrary>
					<classPatterns>
						<pattern>fr.asi.central.dto.project.*</pattern>
					</classPatterns>
					<outputKind>module</outputKind>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

I got this error : 

> [ERROR] Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.25.322:generate (generate) on project central-server-dto: Execution generate of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.25.322:generate failed: A required class was missing while executing cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.25.322:generate: io/github/lukehutch/fastclasspathscanner/FastClasspathScanner
> [ERROR] -----------------------------------------------------
> [ERROR] realm =    plugin>cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.25.322
> [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
> [ERROR] urls[0] = file:/C:/Users/xrobert.ASI/.m2/repository/cz/habarta/typescript-generator/typescript-generator-maven-plugin/1.25.322/typescript-generator-maven-plugin-1.25.322.jar
> [ERROR] urls[1] = file:/C:/Users/xrobert.ASI/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
> [ERROR] urls[2] = file:/C:/Users/xrobert.ASI/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
> [ERROR] urls[3] = file:/C:/Users/xrobert.ASI/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
> [ERROR] urls[4] = file:/C:/Users/xrobert.ASI/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
> [ERROR] urls[5] = file:/C:/Users/xrobert.ASI/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar
> [ERROR] urls[6] = file:/C:/Users/xrobert.ASI/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
> [ERROR] urls[7] = file:/C:/Users/xrobert.ASI/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
> [ERROR] urls[8] = file:/C:/Users/xrobert.ASI/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
> [ERROR] urls[9] = file:/C:/Users/xrobert.ASI/.m2/repository/cz/habarta/typescript-generator/typescript-generator-core/1.25.322/typescript-generator-core-1.25.322.jar
> [ERROR] urls[10] = file:/C:/Users/xrobert.ASI/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar
> [ERROR] urls[11] = file:/C:/Users/xrobert.ASI/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar
> [ERROR] urls[12] = file:/C:/Users/xrobert.ASI/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.8.6/jackson-jaxrs-json-provider-2.8.6.jar
> [ERROR] urls[13] = file:/C:/Users/xrobert.ASI/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.8.6/jackson-jaxrs-base-2.8.6.jar
> [ERROR] urls[14] = file:/C:/Users/xrobert.ASI/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.6/jackson-core-2.8.6.jar
> [ERROR] urls[15] = file:/C:/Users/xrobert.ASI/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.6/jackson-databind-2.8.6.jar
> [ERROR] urls[16] = file:/C:/Users/xrobert.ASI/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar
> [ERROR] urls[17] = file:/C:/Users/xrobert.ASI/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.8.6/jackson-module-jaxb-annotations-2.8.6.jar
> [ERROR] urls[18] = file:/C:/Users/xrobert.ASI/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar
> [ERROR] urls[19] = file:/C:/Users/xrobert.ASI/.m2/repository/io/github/lukehutch/fast-classpath-scanner/2.0.17/fast-classpath-scanner-2.0.17.jar
> [ERROR] Number of foreign imports: 1
> [ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
> [ERROR]
> [ERROR] -----------------------------------------------------: io.github.lukehutch.fastclasspathscanner.FastClasspathScanner

Do I miss some dependencies ? 

Anyway  thanks for your plugin, really a nice job you made there, so saved me a lot of work :)

Ixoh

**Comment by Ixoh** [comment]
Ok perhaps i missed some **warning** before,  but my dependencie to io/github/lukehutch/fastclasspathscanner
was **corrupted**. I have simply removed it to solve my problem.

**Comment by vojtechhabarta** [comment]
Hello,
nice to hear that it works for you.

I think you should remove following dependency:
``` xml
<dependency>
    <groupId>cz.habarta.typescript-generator</groupId>
    <artifactId>typescript-generator-maven-plugin</artifactId>
    <version>1.25.322</version>
</dependency>
```
Plugins should only be included in `<plugins>` section.

**Comment by Ixoh** [comment]
Hello, 

Thanks for your reply, still work like a charm.

Btw is it possible de generate "class" and not "interface" ?

**Comment by vojtechhabarta** [comment]
Yes, you can set `<mapClasses>` configuration parameter to `asClasses` value.
But you need to generate implementation file (.ts) instead of declaration file (.d.ts) in this case.
``` xml
<configuration>
    <outputFile>something.ts</outputFile>
    <outputFileType>implementationFile</outputFileType>
    <mapClasses>asClasses</mapClasses>
    ...
</configuration>
```
And then you need to compile generated .ts file into .js file.

**Comment by Ixoh** [comment]
Oh sorry I missed it in the documention..,

In fact use it to generate my **dto** for my angular 4 application so a **.ts** is perfectly fine. 
Next step would be to generate http service in TypeScript using those **dto** and my rest controller ;). Like this I can keep my frontend and my backend perfectly synchronized.

Thanks you :)

**Comment by vojtechhabarta** [comment]
BTW if you have your REST service implemented using JAX-RS you can generate TypeScript client for it using typescript-generator as well. But it depends on your situation if it is helpful or not.

**Comment by Ixoh** [comment]
Ah yes i'm gonna try this. 
Spring boot allow us to define REST service using JAX-RS thanks to Jersey.

Thanks

**Comment by Ixoh** [comment]
Hey,

I tried to generate my REST Client based on Jersey and it works really great :)

For information I have tried to use my Jersey configuration class like it was said in documentation as an entry point to class discovert but it was not really working. It was working good with the Application example.

> **Application class doesn't have to derive directly from javax.ws.rs.core.Application, it can derive from some framework class like org.glassfish.jersey.server.ResourceConfig in Jersey.**

```
@Configuration
public class JerseyConfig extends ResourceConfig {

	public JerseyConfig() {
		registerEndpoints();
	}

	private void registerEndpoints() {
		packages("fr.asi.central.server.controller");
	}
}
```
I used the **<jaxrsNamespacing>perResource</jaxrsNamespacing>**  to generate separate classes and it worked good. 
Now my last need would be to get 2 separate file :  one for **DTO** and one for **Resources** (REST Client) : can you tell me if it's possible ?

Anyway like I already said ! really thank you :D

Ixoh

**Comment by vojtechhabarta** [comment]
Hi,
good to see that you made a progress. I have couple of notes:

- Using JAX-RS application class (`classesFromJaxrsApplication`) is somewhat tricky because specified class should be instantiable in different context than it lives normally. In the end automatic way (`classesFromAutomaticJaxrsApplication`) is probably better. At least in our case it works well.
- Generate two files is not possible and I would not like to complicate typescript-generator with this kind of functionality because many people would like to split generated declarations in different ways. BTW why do you prefer to split it? Maybe there is some workaround for you.
- Adding `@Injectable()` annotation to client class is not currently possible. Are you using `AxiosClientExtension` or do you generate just generic client? I am not sure how to support this in "right" way. I think workaround for you now is to write class derived from client class and add annotation there but I understand that it is annoying especially when you have more client classes.

**Comment by Ixoh** [comment]
- About splitting **DTO** and **Resources** I can do it easilly manually so no problem. It isn't necessary for me, it's just for design and readability. 
- I generate the generic client which clearly feet my needs since I just need to define my own implementation of HttpClient. The only problem is that I really need to make those clients **@Injectable()** to be able to use it easily with angular. If I must do it manually each time I generate my client it will be waste of time.

I have clone the project, I will check what I can do ;)

Thanks

**Comment by vojtechhabarta** [comment]
I would  recommend to write extension similar to `AxiosClientExtension`. In this case you can include your `HttpClient` implementation as well as `@Injectable()` decorator.
