### ISSUE TITLE
Dates in nested DTOs are not output as Dates in Typescript definition

### ISSUE THREAD

**Issue by bniedermeyer** [vojtechhabarta/typescript-generator#158]
I am currently converting one DTO that is nested within another using the example from #24 . 

The DTO is being generated, but one field that is of type java.util.Date is being converted to a DateTime type in Typescript. This DateTime appears to be a number of interfaces generated that follow the inheritance chain of java.util.Date while other types from non-nested DTOs that contain Date member variables are being generated with the correct Typescript Date types. The nested DTO is the only type that contains this new DateTime type. 

I've tried explicitly setting `<mapDate>` to `asDate`, but the problem still persists. Is there anything that needs to be done to ensure that the java.util.Date member is being converted to the Typescript Date type correctly?

The project is running with Java 8, and Maven 3. Below is an example of my configuration. 

```
<plugin>
	<groupId>cz.habarta.typescript-generator</groupId>
	<artifactId>typescript-generator-maven-plugin</artifactId>
	<version>1.25.322</version>
	<executions>
		<execution>
			<id>generate</id>
			<goals>
				<goal>generate</goal>
			</goals>
			<phase>process-classes</phase>
		</execution>
	</executions>
	<configuration>
		<jsonLibrary>jackson2</jsonLibrary>
		<classes>
			<class>com.myApp.dataModel.DataItem</class>
			<class>com.myApp.query.desc.DeltaQueryDescriptor</class>
			<class>com.myApp.controller.cmd.FetchHeadersCommand$HeaderEntry</class>
		</classes>
		<mapDate>asDate</mapDate>
		<outputKind>module</outputKind>
		<outputFile>src/app/shared/models/models.d.ts</outputFile>
	</configuration>
</plugin>
```

**Comment by vojtechhabarta** [comment]
Type mapping should not depend on class nesting.
Are you using Jackson2? Check if the **property** (field/getter/setter) is really recognized as "java.util.Date" by Jackson. Maybe there is some getter with different type.
________________________________

**Comment by bniedermeyer** [comment]
It appears that is what is happening when we serialize the DTO - we convert a Joda based timestamp.

**Comment by vojtechhabarta** [comment]
So have you managed to make it work as you need? I guess that yes (since you closed the issue) but I am asking anyway if you need some help.

**Comment by bniedermeyer** [comment]
Ultimately yes. We had some changes to the model we were converting so this shouldn't be an issue. I'll keep an eye out if we run into it again though. Thanks!
