### ISSUE TITLE
Any possible way to add support for new types

### ISSUE THREAD

**Issue by mohamnag** [vojtechhabarta/typescript-generator#159]
I just came to this tool and find it a very great solution for Java-JS combined solutions, however it is lacking some features for me. before diving into source to find possible answers, wanted to ask it here.
My major problem is related to not supporting Java 8 types, specifically in my case ZonedDateTime, Instant and Optionals. The question is whether or not there is a plan to support these or at least if there is a way to add these as kind of extensions, like a converter class per type or similar.

**Comment by vojtechhabarta** [comment]
@mohamnag it is possible to use `customTypeMappings` parameter and specify how `ZonedDateTime` and `Instant` should be mapped. For example if you want to map these Java types to TypeScript `string` you can configure it like this (in Maven):
``` xml
<configuration>
    <customTypeMappings>
        <mapping>java.time.ZonedDateTime:string</mapping>
        <mapping>java.time.Instant:string</mapping>
    </customTypeMappings>
</configuration>
```
You can find more information here: https://github.com/vojtechhabarta/typescript-generator/wiki/Type-Mapping

Support for Java 8 Optional is described here: https://github.com/vojtechhabarta/typescript-generator/pull/93

**Comment by mohamnag** [comment]
@vojtechhabarta thanks for fast reply. As for ZonedDateTime and Instant I'm clear now. For Optional I have another question, why don't you use the TS's optional on interfaces?

**Comment by vojtechhabarta** [comment]
Do you mean that for `Person` class in #93 PR email property in TypeScript interface should be optional like this?
``` typescript
interface Person {
    name: string;
    email?: string;
}
```
The question mark should probably be added in this case.

BTW it is possible to generate optional TS properties for Java properties marked with specified annotation or it is possible to generate all properties as optional.

**Comment by mohamnag** [comment]
Yes I mean the question mark is missing in PR.

I saw the annotation, but in my case some of the DTOs do not belong to me and therefore I can't change them but they use Java's optional to show the possibility of missing properties.

**Comment by vojtechhabarta** [comment]
See improvements in [v1.28.343](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.28.343).

**Comment by mohamnag** [comment]
Thats really nice, thanks for the fast reaction ;)
