### ISSUE TITLE
Prevent running unnecesarily

### ISSUE THREAD

**Issue by r89m** [vojtechhabarta/typescript-generator#161]
Hi Vojtěch,

Thanks for you tool - I've been finding it really useful.

One issue I've been having it that it runs a bit too often (on every build) due to the addition of the generateTypeScript tasks as a dependency on the classes tasks here:
https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-gradle-plugin/src/main/java/cz/habarta/typescript/generator/gradle/TypeScriptGeneratorPlugin.java#L14-L16

Is there a  reason for this, or would it be possible to configure it to not always run?
At the moment I'm doing `classes.dependsOn.remove(generateTypeScript)` which works but feels like a work around. I'd love it if I could configure it to only run when I call `generateTypeScript`

Thanks,

Richard

**Comment by vojtechhabarta** [comment]
Hi Richard, thanks for using the tool.

In Maven it is possible to configure typescript-generator either to run in each build or only on demand.
But I don't how Gradle works. Maybe somebody can comment or make PR with some improvement?

**Comment by r89m** [comment]
I'd possibly suggest removing the lines referenced above, then any users who want the tool to run on every build can add `classes.dependsOn(generateTypeScript)` to their `build.gradle` as that's the way task dependencies are configured in Gradle.

**Comment by vojtechhabarta** [comment]
This would be incompatible change. Lets wait for more feedback on this issue.

**Comment by jtoplak** [comment]
I agree that running the tool on every build is overkill. It would be preferable to run `generateTypescript` on demand. If your concerned about making a breaking change, what about adding another setting property like `onBuild = false` (default to `true`) that bypasses the task on build? I would be willing to make the enhancement if everyone thought this was an acceptable solution

**Comment by jechlin** [comment]
Isn't the problem here just that the inputs and outputs are not declared, so gradle can't work out whether to skip it? Typically you would have the task run every time, but gradle will skip it if the inputs and outputs are not changed.

**Comment by vojtechhabarta** [comment]
@jechlin yes, automatically determining whether `generateTypeScript` task needs to be invoked is complicated or impossible but if I understand it correctly original request was just to allow to invoke `generateTypeScript` task **manually** when needed.

**Comment by vojtechhabarta** [comment]
@r89m I just pushed commit which removed setting dependency on `generateTypeScript` task.
Is it what is needed?

**Comment by r89m** [comment]
Perfect. It may be worth adding a note under the Gradle section of the readme outlining how to call the task, ie `gradle generateTypeScript ` just to get people started.
