### ISSUE TITLE
Support for @Nullable

### ISSUE THREAD

**Issue by pstawinski** [vojtechhabarta/typescript-generator#165]
Hi,
thank you for a great project! 
Please let me make a simple feature request. It would be wonderful to have possibility to mark some interface entries as optional.
For example for Java class:

`
public class DocumentEntry {
    @javax.annotation.Nullable    
    private String url;
}
`
generate a typescript interface:
`
export interface DocumentEntry {
    url?: string;
}
`
(mind the ?:).
Or maybe there is some way to generate optional entries already?

Thank you, best wishes,
Piotr

**Comment by vojtechhabarta** [comment]
Hi Piotr,
yes, it is already possible. You can use `optionalAnnotations` configuration parameter and specify one or more annotations which you are using to mark nullable/optional properties.

Here is sample for Maven:
``` xml
<configuration>
    <optionalAnnotations>
        <annotation>javax.annotation.Nullable</annotation>
    </optionalAnnotations>
    ...
</configuration>
```

**Comment by pstawinski** [comment]
Great! Thank you. 
I haven't this in docs/wiki...

It's amazing job you're doing. Best wishes!

**Comment by vojtechhabarta** [comment]
Here is page generated from `typescript-generator-maven-plugin` 
http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html which mentions this parameter. It is linked from the [Wiki](https://github.com/vojtechhabarta/typescript-generator/wiki) but I know it is not ideal 😏
