### ISSUE TITLE
question: generating equals & hashcode

### ISSUE THREAD

**Issue by emmanueltouzery** [vojtechhabarta/typescript-generator#168]
the [immutablejs](https://facebook.github.io/immutable-js/) framework for instance allows you to have `Set` of items, but so that no two duplicate items are in fact added in the Set, the user must provide equality semantics for the items.

In particular, the user must provide two methods for items:
https://facebook.github.io/immutable-js/docs/#/ValueObject

`equals` and `hashCode`. What I would like to have is getting typescript-generator to optionally generate such functions for the mapped DTOs. So, we generate classes, not interfaces, and add these methods.

Now clearly there are multiple possible equality semantics. Sometimes we may want to compare only by the ID field. And sometimes we want to recursively compare every field. Also a function must be written to calculate the hash of basic types, such as strings. So I think the full logic for that doesn't belong in typescript-generator. But I'd love to have an extension point, a possibility to write a plugin to do that. Do you think it's possible?

For our project, ideally, I could see toplevel annotations on DTOs like `@EqualityById` (must have an `id` field) and `@EqualityByValue` or something like that. Then our plugin affects the code generation. Adds these extra methods.

There is a side-task too. We currently generate a `.ts` already, not a `.d.ts`, but we generate interfaces for our types. Generating classes would bring in some bloat. It's not that often that we need Sets.. So ideally we would still generate interfaces, and generate classes only when one of these annotations, EqualityById, or EqualityByValue is present (it would be a typescript compile error down the line if a class has the annotation but has a field with a non-primitive type without that annotation, no need to handle that ourselves). I was looking at `ModelCompiler.processBean`. Even though nominally the setting to generate a class or an interface is global for the whole system, in the code, it's actually per-class. So I think there an extension could also be possible. That typescript-generator could invoke a plugin in `processBean` and the plugin would say whether, for that particular class, it should generate a class or an interface.

What do you think? Do you think these features are possible without complicating typescript-generator too much?

**Comment by vojtechhabarta** [comment]
Generate mix of classes and interfaces based on some annotations could be useful feature in general.

What do you expect to be generated? Something like this:
``` typescript
// annotation in Java was @EqualityById
class Company {
    id: string;
    name: string;
    hashCode(): number {
        return hashCodeHelper(this.id);
    }
    equals(other: any): boolean {
        return equalsHelper(this.id, other.id);
    }
}

// annotation in Java was @EqualityByValue
class Person {
    name: string;
    age: number;
    hashCode(): number {
        return hashCodeHelper(this);
    }
    equals(other: any): boolean {
        return equalsHelper(this, other);
    }
}
```
where helper functions have following signatures:
``` typescript
declare function hashCodeHelper(object: any): number;
declare function equalsHelper(a: any, b: any): boolean;
```

You described two equality cases: using `id` field and using whole object (all fields). Sooner or later somebody will want to use not all fields but some of them. For this we could have `getKey()` method returning object with fields relevant to `hashCode()` and `equals()`. But this could be done in many variants, here is sample with 4 variants how to specify that `name` is used as key but `age` not:
``` typescript
// variant 1 in Java: @EqualityByValue(keys = {"name"})
// variant 2 in Java: @EqualityByValue(exclude = {"age"})
class Person2 {
    // variant in Java 3: @EqualityKey
    name: string;
    // variant in Java 4: @Transient or @Auxiliary
    age: number;
    getKey(): Partial<Person2> {
        return {
            name: this.name,
        };
    }
    hashCode(): number {
        return hashCodeHelper(this.getKey());
    }
    equals(other: any): boolean {
        return equalsHelper(this.getKey(), other.getKey());
    }
}
```

So this is probably really job for some plugins.

Do you expect some helper functions like `hashCodeHelper`/`equalsHelper` would go through objects, process primitive values and recursively call `hashCode()`/`equals()` (if available) on objects? Or do you think it should be implemented directly in these methods (for example for performance reasons or because we could know the static types)?

Solution could have following parts:
1. determine fields that should be used in `hashCode()`/`equals()` methods
2. generate `hashCode()`/`equals()` methods and delegate to helpers
3. implement helpers

I am not sure what should be fixed, what should be customizable and what should be in some plugin. What do you think?

**Comment by emmanueltouzery** [comment]
I think almost nothing should go in the core of typescript-generator. We could provide a sample plugin shipped in the typescript-generator repo, which provides a version of this feature though, once the core supports it. Then if people are interested, they can take that sample plugin as a starting point, and tune it for their needs.

What I would see in the core would just be:
* extension point so that a plugin may request that a class is exported as a class or an interface. Maybe the plugin gets a list of all the classes and it returns a list of classes to generate as classes. The others are implicitely generated as interfaces, for instance.
* extension point for a callback which gets the current class being generated right now. That callback can freely add new functions to be generated to the class that is being generated, and view the fields of the class. It could add `equals`, it could add `hashCode`, it could add `toString`, it could add anything it wants. But the callback couldn't modify what the core generates already. only add new methods (and possibly fields).

That what's I had in mind for the core. No `EqualityById`, not even the idea of `equals` or `hashCode`.

Then how the extension would work.. I mean we could do an `equalHelper` in javascript that would work through reflection and the like, but we know the full model. So for each class where `@EqualityByValue` is specified, I would generate an inline equals method, like:

```typescript
class Person2 {
    // variant in Java 3: @EqualityKey
    name: string;
    // variant in Java 4: @Transient or @Auxiliary
    age: number;
    // complex object
    address: Address;
    equals(other: any): boolean {
        return this.name === other.name && this.address.equals(other.address);
    }
```

Now if the user did not specify `@EqualityById` or `@EqualityByValue` on `Address`, there will be no `equals` method on `Address`, and you get a typescript compile error after we generate. Which is good. So no need to recursively implement it in each class physically. We only need to know whether the type is primitive (generate `===`) or not (generate a `equals` code). Similar for `hashCode`.

If it's `@EqualityById` even easier: we just return generate `return this.id === other.id`. Well there is an annoyance about whether it's the same type. Don't want a `Customer` to be equal to an `Address` just because they have the same id. Maybe we could add a new function `getType(): string` returning the classname. Then we have `return this.getType() === other.getType() && this.id === other.id`. But yeah again.. Not in the core. That's the extension's problem.

Yes, so... As I'm typing this, I'm thinking that this really sounds doable :-)

**Comment by emmanueltouzery** [comment]
Actually I realized that for the per-class control whether to generate an interface or a class we don't really need plugins. This could be specified in the pom.xml, like that for instance:

```
<classes>
  <class>...</class> <--- follows the global setting as of now
  <class target="class">..</class> <--- forced to a class output
  <class target="interface">...</class> <--- forced to an interface output
</classes>
```

anyway, it's your call, but that's an option too. It doesn't really have to be decided using that annotation. It's not a problem for us to edit the pom.xml to get a class, and then add the annotation to specify the type of equality. It doesn't matter if it's one step or two. And modifying the XML format is probably less work in typescript-generator. And it's also easier for other people to leverage that feature without having to write plugins for typescript-generator.

**Comment by vojtechhabarta** [comment]
It is not possible to use attributes in Maven. Moreover `classes` parameter is not only way how to specify input classes. It is also possible to specify them using `classPatterns`, `classesFromJaxrsApplication` and `classesFromAutomaticJaxrsApplication`. So it would be better to leave these parameters as they are now and rather add some parameter meaning "patterns for Java classes that should become classes in TS" (I don't have good name now) that would work for all classes regardless how they are specified (or discovered).

But for now I would rather add something like `classAnnotations` (and maybe `interfaceAnnotations`):
``` xml
<configuration>
    <classAnnotations>
        <annotation>com.package.EqualityById</annotation>
        <annotation>com.package.EqualityByValue</annotation>
    </classAnnotations>
    ...
</configuration>
```
I think annotations are better for your case. And it doesn't prevent adding configuration parameter later.

**Comment by emmanueltouzery** [comment]
Yes, I came to the same conclusion looking at the code.

I actually started work on another, maybe over-aggressive approach:
https://github.com/emmanueltouzery/typescript-generator/commit/c57423432f2c4575f4386577d082e04cccda56e9

(this is not finished, the extension doesn't get all the parameters it needs, it'll need at least to get the `Writer` and the `Settings`)

By doing that, I solve both problems at once. The downside is that there is some copy-pasting between the core and the extension, although I don't expect that's code that changes very often. It's also attractive for me, because it doesn't look like much work :-) But also it's really the maximally flexible solution: with this, a plugin can do many things potentially. Any opinion?

**Comment by emmanueltouzery** [comment]
(hmm the code is buggy, it shouldn't be `if (!emitterExtension.emitBean(bean, exportKeyword)) {` but rather `if (emitterExtension.emitBean(bean, exportKeyword)) {` -- but you get the idea. Allow extensions to completely override code generation for any particular bean.

**Comment by emmanueltouzery** [comment]
But yes what i started overrides the whole generation for that bean. Instead we could have your annotations idea to force a class, then the extension can only add new methods on the class as I suggested at first, instead of overriding the whole generation. Then there is less flexibility for extensions, but less copy/pasting between core & extension. I guess you prefer the second solution?

**Comment by vojtechhabarta** [comment]
I prefer not overriding generated code and just add extra code.

**Comment by emmanueltouzery** [comment]
I submitted a PR to make it possible to specify per-class whether it should be generated as a class or as an interface, in the way you suggested. However now I'm a little unsure. I expected that if we generate as a class, as opposed to an interface, and we generate a JAX-RS client, then the class is instantiated when getting the response from the server?

right now we get back:

```typescript
return this.httpClient.request({ method: "GET", url: uriEncoding`...`, options: options });
```

even if the return type is a class. But now if we add extra methods on the class and expect them to work, we'd probably need to change this generated code to something like:


```typescript
return this.httpClient.request({ method: "GET", url: uriEncoding`...`, options: options })
    .then(r => r.data = r.data.map(x => x new ClassDto(x));
```

or something like that, no? Otherwise presumably the extra methods we add to the class on the client won't in fact be available at runtime? I'm not sure what's the use-case for classes as opposed to interfaces in typescript-generator right now.

**Comment by vojtechhabarta** [comment]
Oh, you are right. We will need to copy JSON data objects to classes objects (or assign prototypes).

Since this needs to work "recursively" I thing best solution is to generate _copy_ constructors which would assign fields one by one and use `new` where needed.

I am not exactly sure why people wanted to generate classes instead of interfaces. Maybe it is somehow useful in angular or they just like it more.

FYI generate classes feature was implemented before JAX-RS client and till now it didn't matter that objects returned from client don't have "correct" prototypes.

I will probably start with this so we don't have some broken features.

**Comment by emmanueltouzery** [comment]
Oh I'm glad you offered to write the code to instantiate the classes, especially since I didn't realize, as you mentioned, that it must be done recursively. Otherwise with the two PRs I made in theory all the pieces are there, but I must test with all the pieces together to be 100% sure. Looking good though!

**Comment by vojtechhabarta** [comment]
Generate copy constructors is actually harder than I was expecting. It should handle:
- `undefined`, `null`
- simple values
- classes
- arrays, objects
- generics

and combinations of all this. Plus it has to have special handling of tagged unions. But I don't plan to support interfaces, see bellow.

Here is a sample what I want to implement:
``` typescript
class User {
    name: string;
    childAccount: boolean;
    age: number;
    address: Address;
    addresses: Address[];
    taggedAddresses: { [index: string]: Address };
    groupedAddresses: { [index: string]: Address[] };
    listOfTaggedAddresses: { [index: string]: Address }[];
    orders: PagedList<Order>;
    allOrders: PagedList<Order>[];
    shape: ShapeUnion;
    shapes: ShapeUnion[];

    constructor(data?: User) {
        if (data) {
            this.name = data.name;
            this.childAccount = data.childAccount;
            this.age = data.age;
            this.address = data.address && new Address(data.address);
            this.addresses = __copyArray(data.addresses, data => new Address(data));
            this.taggedAddresses = __copyObject(data.taggedAddresses, data => new Address(data));
            this.groupedAddresses = __copyObject(data.groupedAddresses, data => __copyArray(data, data => new Address(data)));
            this.listOfTaggedAddresses = __copyArray(data.listOfTaggedAddresses, data => __copyObject(data, data => new Address(data)));
            this.orders = data.orders && new PagedList<Order>(data.orders);
            this.allOrders = __copyArray(data.allOrders, data => new PagedList<Order>(data));
            this.shape = Shape.__copyOf(data.shape);
            this.shapes = __copyArray(data.shapes, item => Shape.__copyOf(item));
        }
    }
}
```

Full example is here: [CopyConstructorsTest-expected.ts](https://github.com/vojtechhabarta/typescript-generator/blob/880608f79b1fcdb3b3dd69e1e09fe62d545241bf/typescript-generator-core/src/main/resources/cz/habarta/typescript/generator/CopyConstructorsTest-expected.ts), [CopyConstructorsTest.java](https://github.com/vojtechhabarta/typescript-generator/blob/880608f79b1fcdb3b3dd69e1e09fe62d545241bf/typescript-generator-core/src/test/java/cz/habarta/typescript/generator/CopyConstructorsTest.java).
Could check it if it makes sense?

The problem with interfaces is this. Let's say we have:
``` typescript
class Organization {
    people: Person[];
}
interface Person {
    address: Address;
}
class Address {
}
```
then `Person` cannot have constructor. When creating instance of `Organization` class from data objects then `Address` would not be instantiated. So I would not allow to generate mix of classes and interfaces (#170), at least for now. Of course it has a solution but I would keep it simple. Is this a problem for you?

**Comment by emmanueltouzery** [comment]
wow i didn't foresee that level of complexity :-( i'll review it properly the earliest tonight.

Regarding the mix of classes and interfaces, I totally understand where you come from. however my issue is that we have LOTS of DTOs here and we would actually need classes only rarely, especially to begin with. I'm worried about the bloat on the client by having classes for everything. We would probably stick with interfaces then.
What do you think about side-stepping the problem in the generation phase -- we require that if one class is exported as a class then all its fields must be classes too.
Either we could enforce it ourselves, in the #170 pull request I could add code to say "we export this class to a TS class if the user asked to, or if its used as a field of another class which is exported to a TS class" (but yeah that's not really super simple either), or we rely on the compiler: if we generate a `new Person(data)` there would be a typescript compile error after generation, and the user would understand that they must mark `Person` as being a class too.

But if you don't want to support this feature, especially at first, I would totally understand.

**Comment by emmanueltouzery** [comment]
I looked at the links you gave. It's amazing work. Arrays, tagged unions.. I had no idea typescript-generator supported all of that. I think it's great.

As I said, the only thing I would wish for is ... sure we don't support interfaces. So it fails if there are interfaces in the graph; if the user takes care to really have classes all the way down for those object hierarchies, it would work and we are not forced to have 100% classes for the whole project. So, give the responsability to the user. The user can get manual control, but then (s)he must take care of that.

In practice, in our cases, our DTOs are not that complex in general, and I don't think that discipline would be too much to ask.

**Comment by vojtechhabarta** [comment]
Thanks for checking these files. Didn't you think it is already implemented? ;-) It is just description in the form of unit test (sometimes TDD is practical). It will be lot of work but I think it can be useful also in other cases. Once generated client returns objects with correct prototypes people will be able to add their manually written methods to classes (assign to prototype).

**Comment by emmanueltouzery** [comment]
You still have this on your radar right? It's just that you're busy elsewhere, correct? For now i can't find the time to help implement this either :-(

**Comment by vojtechhabarta** [comment]
Exactly, after finishing few smaller things I am returning to this.

There is one more thing: constructors which do deep-copy of passed object are useful for converting JSON objects to instances of classes but if somebody would like to use these constructors for constructing some object tree it would unnecessarily copy some objects multiple times. Here is an example:
``` typescript
class A {
    b: B;
}
class B {
    c: C;
}
class C {
    d: string;
}

const x = new A({
    b: {
        c: {
            d: "d"
        }
    }
});
```
Assume these classes have deep-copy constructors. Then object `C` would be copied twice, first time when creating object `B` and second time indirectly when creating object `A`.

This might not be a big problem but it is strange. Maybe these constructors should have second parameter `deepCopy: boolean`.

**Comment by emmanueltouzery** [comment]
Good point! Or static builders instead of constructors. Maybe a trivial constructor and then a `static fromJSON` function as well? But just talking from the top of my head.

Thank you for the time you take, it is appreciated!

**Comment by vojtechhabarta** [comment]
I added two variants into branch so now we have these proposals:
- [CopyConstructorsTest-expected.ts](https://github.com/vojtechhabarta/typescript-generator/blob/copy-constructors/typescript-generator-core/src/test/resources/cz/habarta/typescript/generator/CopyConstructorsTest-expected.ts) - constructors with deep copying (original variant)
- [CopyConstructorsShallowOrDeepTest-expected.ts](https://github.com/vojtechhabarta/typescript-generator/blob/copy-constructors/typescript-generator-core/src/test/resources/cz/habarta/typescript/generator/CopyConstructorsShallowOrDeepTest-expected.ts) - constructors with shallow or deep copying
- [FromDataTest-expected.ts](https://github.com/vojtechhabarta/typescript-generator/blob/copy-constructors/typescript-generator-core/src/test/resources/cz/habarta/typescript/generator/FromDataTest-expected.ts) - static method with deep copying (no constructors at all)

I agree that static method is best solution so I will start implementing it (slowly 🙂).

While creating these proposals I discovered one more think that needs to be handled: generic classes.

Let's say I have following generic class:
``` typescript
export class PagedList<T, A> {
    page: number;
    items: T[];
    additionalInfo: A;
```
In this case I don't know how to copy `items` and `additionalInfo` of types `T[]` and `A` so `PagedList`'s copy function needs to get copy functions for these generic parameters like this:
``` typescript
static fromData<T, A>(
    data: PagedList<T, A>,
    constructorFnT: (data: T) => T,
    constructorFnA: (data: A) => A,
    target?: PagedList<T, A>
    ): PagedList<T, A> {

    if (!data) {
        return data;
    }
    const instance = target || new PagedList<T, A>();
    instance.page = data.page;
    instance.items = __copyArray(data.items, constructorFnT);
    instance.additionalInfo = constructorFnA(data.additionalInfo);
    return instance;
}
```
This of course needs to be correctly rendered also on call sites.

And I rather haven't think much about combining this with inheritance. 😉

**Comment by emmanueltouzery** [comment]
oh my god inheritance :-(
well clearly i avoid inheritance of DTOs but yes I have to assume not everyone follows that practice..

the mechanism you have in mind for generics looks like it could be used also to allow a mixed setup classes/interfaces by the way... so one mechanism for types you don't know anything smart about/for which there is no autogenerated static copy function. for interfaces which don't need any conversion one could pass x=>x and that would be it. sorry to mention that since i guess it complicates even more an already very complicated endeavor.

it's up to you though really to consider the impact on typescript-generator codebase. I hope all of this doesn't introduce simply too much new complexity. I didn't consider all the ramifications when I suggested the feature...

**Comment by vojtechhabarta** [comment]
@emmanueltouzery it took longer than I expected but finally JSON deserialization into classes is implemented and released [v1.30.381](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.30.381) 😄 It is also possible to generate mix of classes and interfaces.
It would be good if you could sometime check if it is enough for your needs  (if you are still interested in this feature after such long time 😏). If you have only few classes where you want to have `equals` and `hashcode` you can augment generated classes manually.

- [JSON Deserialization](https://github.com/vojtechhabarta/typescript-generator/wiki/JSON-Deserialization) Wiki page, it also contains sample how to augment generated classes
- `mapClassesAsClassesPatterns` configuration parameter allows to specify which Java classes should be mapped to TypeScript classes ([Configuration parameters](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html))

**Comment by emmanueltouzery** [comment]
Hey great! I'll take a look ASAP, thank you for the work! I really had no idea it was going to be so much work when I opened the bug, but I think the potential applications are huge, including some that we can't yet see right now!

**Comment by vojtechhabarta** [comment]
@emmanueltouzery I am doing big issues/PRs cleanup after [v2 release](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.0.400), we can of course continue discussion here or in new issues.
