### ISSUE TITLE
glob patterns not matched correctly

### ISSUE THREAD

**Issue by hneuer** [vojtechhabarta/typescript-generator#169]
Hy!

Using glob patterns in classPatterns does not find classes which are in the root-directory matched by **.

For example a.b.**.* does not find classes which are located in the a.b package. (As a workaround I had to add the a.b.* pattern).

**Comment by vojtechhabarta** [comment]
Hi, what about `a.b.**`? Could this work for you?

**Comment by hneuer** [comment]
Hy! 
Yes, a.b.**  works in my case, as I want all classes in this package. Though filtering further is not possible this way, like say a.b.**.*Dto .

**Comment by vojtechhabarta** [comment]
And what about ` a.b.**Dto`?
I know these glob patterns work little bit different than in some other tools but it should not be a big problem, I think.

**Comment by hneuer** [comment]
a.b.**Dto works too. So I guess it's just a thing I have to remind :-)

Thanks btw for this tool, it was quite useful in multiple projects for me now!
