### ISSUE TITLE
Empty/default jackson @JsonTypeName isn't handled correctly

### ISSUE THREAD

**Issue by Yona-Appletree** [vojtechhabarta/typescript-generator#172]
According to the JavaDoc on Jackson's @JsonTypeName, if it's value is left blank, it defaults to the non-qualified class name of the annotated class. typescript-generator, however, actually emits the empty string, when it should emit the simple class name.

**Comment by vojtechhabarta** [comment]
Resolved in #178. Released [v1.29.355](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.29.355).
