### ISSUE TITLE
optionalAnnotations should support RetentionPolicy.CLASS annotations

### ISSUE THREAD

**Issue by Yona-Appletree** [vojtechhabarta/typescript-generator#173]
I'm using Kotlin to define my JSON beans, and it has support for nullability in it's type system. For Java interoperability, it adds a @org.jetbrains.annotations.Nullable annotation to all fields and methods which are nullable. Unfortunately, @org.jetbrains.annotations.Nullable has RetentionPolicy.CLASS, and it seems that typescript-generator ignores such annotations when listed in "optionalAnnotations"

If this is supported, folks using Kotlin will get null-safe type checking between server and client automatically, which would be awesome.

**Comment by Yona-Appletree** [comment]
I'm going to close this, as I wanted it for kotlin type support, but there is a better way. I'll create a new slip.

**Comment by RobbinBaauw** [comment]
Could you tell what your "better way" is? The only way I see now is by adding an annotation, which is not preferable because that means duplicating information that is already there.
