### ISSUE TITLE
Jackson2: Support BeanPropertyWriter's metadata for optional properties

### ISSUE THREAD

**Issue by Yona-Appletree** [vojtechhabarta/typescript-generator#174]
Currently, the Jackson2Parser only looks for optionalAnnoations when determining if a property should be optional. It seems like it should default to `! beanPropertyWriter.getMetadata().isRequired()` so as to support custom optional-detection by jackson modules.

In my case, I want it so that the Kotlin module can determine nullability.

**Comment by vojtechhabarta** [comment]
Resolved in #183. Released [v1.29.355](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.29.355).
