### ISSUE TITLE
JAXBElement<T> should be converted in type T

### ISSUE THREAD

**Issue by sanja224** [vojtechhabarta/typescript-generator#175]
Example: 
If I have property of type JAXBElement<Context> I want that to be converted in 'Context' type instead of 'any' in typescript. 
jsonLibrary is already set to jaxb. Maybe I could write something in customTypeMappings but I don't know what.

**Comment by vojtechhabarta** [comment]
@sanja224 `customTypeMappings` is not solution for this because it doesn't work with generics.

I think it would be good if typescript-generator could handle `JAXBElement`s directly.
Do you have some example (Java class -> TypeScript interface)? Is really just needed to "unwrap" the `T` type in all cases?

**Comment by sanja224** [comment]
Yes, I just need the T type unwraped in all cases. I have many examples. Here's one:

These are the properties in the java class
@XmlElement(name = "ExternalReference")
    protected String externalReference;
@XmlElementRef(name = "UserInformation", type = JAXBElement.class, required = false)
    protected JAXBElement<UserType> userInformation;
@XmlElementRef(name = "Source", type = JAXBElement.class, required = false)
    protected JAXBElement<EndPointType> source;
 @XmlElementRef(name = "AdditionalContextInfo", type = JAXBElement.class, required = false)
    protected JAXBElement<AdditionalContextType> additionalContextInfo;

This is the output: 
 externalReference: String,
 userInformation: any,
 source: any,
 additionalContextInfo: any

This is how the output should look like:
 externalReference: String,
 userInformation: UserType,
 source: EndPointType,
 additionalContextInfo: AdditionalContextType

**Comment by vojtechhabarta** [comment]
I committed support for `JAXBElement<T>`. For your example Java input following TypeScript interface is generated (note also casing):
``` typescript
interface ClassWithJAXBElements {
    ExternalReference: string;
    UserInformation: UserType;
    Source: EndPointType;
    AdditionalContextInfo: AdditionalContextType;
}
```
Could you please check it if it does what's expected?

**Comment by sanja224** [comment]
Yes, it works great.
Thanks :))
