### ISSUE TITLE
Maven throw error when trying to parse Enums with 'asEnum' option

### ISSUE THREAD

**Issue by GAngelov5** [vojtechhabarta/typescript-generator#184]
I use the sample-maven project and the pom.xml from it just added support for enums to test it imported all plugins and dependencies automatically by idea. But somehow the 'asEnum' is missing in **EnumMapping**

[ERROR] Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.25.322:generate (default-cli) on project sample-maven: Unable to parse configuration of mojo cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.25.322:generate: Cannot convert 'asEnum' to Enum: No enum constant cz.habarta.typescript.generator.EnumMapping.asEnum -> [Help 1]

Any idea how can I proceed?

**Comment by vojtechhabarta** [comment]
It seems you have typescript-generator version 1.25.322. String enums (`mapEnum` parameter set to value `asEnum`) is supported from version [1.27.339](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.27.339).

You can find latest version released to maven central repository on [releases](https://github.com/vojtechhabarta/typescript-generator/releases) page or it should be visible on [main page](https://github.com/vojtechhabarta/typescript-generator) (if it works 🙂).
