### ISSUE TITLE
Drop Java 7 support

### ISSUE THREAD

**Issue by vojtechhabarta** [vojtechhabarta/typescript-generator#186]
My goal regarding Java compatibility is to support last 2 versions. Since Java 9 was released I am considering upgrading to Java 8.

Moreover latest versions of Jackson and Jersey already don't support Java 7.

What do you thing? Is Java 7 still needed?

**Comment by emmanueltouzery** [comment]
It's fine for me/my company. we're already on java8 (for quite some time). So no issue for us!

Note that java's release cycle will soon accelerate. Supposedly there'll be releases every 6 months, and a new month.year release cycle, starting with java 18.3 in march 2019: http://www.oracle.com/technetwork/java/javase/eol-135779.html

**Comment by jtoplak** [comment]
It would be nice. I would have really liked to implement my class enum feature with streams.

**Comment by Yona-Appletree** [comment]
My company uses Java 8 across the board and is looking to Java 9, I'm all in favor of this.

**Comment by vojtechhabarta** [comment]
Version [2.0.400](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.0.400) is released.
