### ISSUE TITLE
Tagged union types ignoring package with @JsonTypeInfo(use=JsonTypeInfo.Id.CLASS)

### ISSUE THREAD

**Issue by Q-Man** [vojtechhabarta/typescript-generator#189]
Jackson with `@JsonTypeInfo(use=JsonTypeInfo.Id.CLASS)` is using fully qualified class name including the package path.

So the typescript generator should include the package path in the tagged union types. But it's generating only the class name.

Tested with v1.29.355

**Comment by vojtechhabarta** [comment]
Fixed in [v1.29.366](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.29.366).
