### ISSUE TITLE
Another release?

### ISSUE THREAD

**Issue by ryan10132** [vojtechhabarta/typescript-generator#19]
Hi!

Can we have another release? Looks like the last release was on oct 29, eager to use the new features!

**Comment by ryan10132** [comment]
Specifically I was looking here: http://search.maven.org/#search%7Cga%7C1%7Ccz.habarta.typescript-generator

**Comment by vojtechhabarta** [comment]
Yes, I will release it soon.

**Comment by ryan10132** [comment]
Cool, will that create a new artifact here: http://search.maven.org/#search%7Cga%7C1%7Ccz.habarta.typescript-generator

**Comment by vojtechhabarta** [comment]
Released [v1.3.134](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.3.134).
Yes, it is available in Maven Central Repository.

**Comment by ryan10132** [comment]
Terrific! thanks
