### ISSUE TITLE
Add support for API compatible Class based Enums

### ISSUE THREAD

**Issue by jtoplak** [vojtechhabarta/typescript-generator#191]
Proper serialization/deserialization of enums is a huge waste of time.  As such, robust API safe enums are quite often mimicked using classes (and they should be in most cases). It avoids an incredible amount of hassle and is commonly implemented with the following pattern.

    @EqualsAndHashCode
    public class ApiFriendlyType {

        public static final ApiFriendlyType FOO = new ApiFriendlyType("FOO");
        public static final ApiFriendlyType BAR  = new ApiFriendlyType("BAR");

        private final String value;

        @JsonCreator public ApiFriendlyType(String value) { 
            this.value = Objects.requireNonNull(value);
        }

        @JsonValue public String getValue() { return value; }

        @Override public String toString() { return value; }

    }

Since the class is not treated like an enum, this pattern will always produce

    interface ApiFriendlyType {
        value: string;
    }

Instead of

    type ApiFriendlyType = "FOO" | "BAR";
    interface ApiFriendlyEnum {
        value: ApiFriendlyType
    }

or the preferred

    enum ApiFriendlyType {
        FOO = "FOO",
        BAR = "BAR"
    }

I decided to try and implement a custom TypeProcessor that checks for class names with the suffix "Type". I ran into issues when I tried to pass FOO and BAR and the TsType enum type to the Result object. As it is I also don't see any way to utilize an EmitterExtension.

How else could I properly map this kind of Pseudo Enum to a typescript enum?

**Comment by vojtechhabarta** [comment]
@jtoplak this cannot be done using `TypeProcessor` or `EmitterExtension`. `TypeProcessor` maps one Java type to TypeScript type, it cannot produce new declarations. `EmitterExtension` can add declaration to output but cannot change declarations.

This could be achieved in `ModelParser` or `ModelCompiler` (https://github.com/vojtechhabarta/typescript-generator#architecture) but they are not extensible now. Would you be ok with using your own typescript-generator fork?

Do you think this feature is mostly for Jackson2 classes?

If yes you could extend `Jackson2Parser`, override `parseClass` and produce `EnumModel` insteadof `BeanModel` for your "enum" classes.

If you wanted this to work with all libraries you could create a method which transforms `TsModel`. In `ModelCompiler.javaToTypeScript()` is chain of such transformers. You could put it before enum section.

**Comment by jtoplak** [comment]
@vojtechhabarta That's very helpful, thanks for the quick response. 

I'm okay with forking this feature for now. Jackson2 classes are for sure the majority use case and overriding the `parseClass` seems like the quickest solution, although in the long run it would make sense to support it for jaxb as well.

 I'll give it a shot and send you a pull request :)

**Comment by jtoplak** [comment]
Hey there @vojtechhabarta.

I have added a transformClassToEnum method in the ModelCompiler, which is triggered when it picks up a class name pattern set by `settings.classEnumPattern`. I am successfully returning  a Typescript Enum from a Java class but not I'm having a bit of trouble finding where the interface for the Ts Enum gets set. Right now my following test object

    private static class AClassEnumType {

        public final AClassEnumType ATYPE  = new AClassEnumType("ATYPE");
        public final AClassEnumType BTYPE  = new AClassEnumType("BTYPE");
        public final AClassEnumType CTYPE  = new AClassEnumType("CTYPE");

        private final String value;

        public AClassEnumType(String value) {
            this.value = Objects.requireNonNull(value);
        }
    }

generates:

    interface AClassEnumType {
        ATYPE: AClassEnumType;
        BTYPE: AClassEnumType;
        CTYPE: AClassEnumType; 
    }
    
    declare const enum AClassEnumType {
        ATYPE = "ATYPE",
        BTYPE = "BTYPE",
        CTYPE = "CTYPE",
    }

Instead of:

    interface AClassEnumType {
        value: AClassEnumType;
    }
    
    declare const enum AClassEnumType {
        ATYPE = "ATYPE",
        BTYPE = "BTYPE",
        CTYPE = "CTYPE",
    }

A point in the right direction would be appreciated :)

**Comment by vojtechhabarta** [comment]
I think you should remove whole `interface AClassEnumType { ... }` from generated output.

You are adding your enums to `TsModel.enums` and in the same time you should also filter these enums out of `TsModel.beans`.

BTW: I was thinking that you enum constants should be `static`.

**Comment by jtoplak** [comment]
Yeah the interface was a bit overkill, and filtering the bean wasn't an issue. I agree with using `static`, but the `ModelCompiler` doesn't seem to pick up the any properties when I have a class with properties such as `public static final DummyClassEnum FOO  = new DummyClassEnum("FOO");`. As soon as I take out static, everything works. Is this by design?

**Comment by vojtechhabarta** [comment]
Aha, you are right, `static` fields are not "properties" and are not serialized into JSON so `Jackson2Parser` doesn't get them from Jackson's `BeanSerializer`. That's how Jackson mapping works.

If you really wanted to use `static` fields you would need to use reflections either in `ModelParser` or you could get `Class` from bean in `ModelCompiler` using `BeanModel.getOrigin()`.

But I still think it is not worth to trade Java enums for performance improvement. Do you have some measurement how performance of enums vs. constant fields compares?

**Comment by jtoplak** [comment]
Sorry i explained the problem poorly, I wasn't referring to performance more so enums in API's being a waste of time because of versioning. I'll close this issue. I commented on this with a better argument in my PR.
