### ISSUE TITLE
Feature request: Enum generation from Uppercase with underscore to camelcase

### ISSUE THREAD

**Issue by PatrykF123** [vojtechhabarta/typescript-generator#195]
Hello!

Could You please add a feature to Your plugin regarding enum generation?

In Java enum values are written in uppercase with underscore e.g. MAJOR_VERSION, MINOR_VERSION, SOME_OTHER_VERSION, but i would like to use camelcase types in generated files (MajorVersion, MinorVersion, SomeOtherVersion).

Best Regards,
Patryk

**Comment by vojtechhabarta** [comment]
Hello Patryk,
generated declarations describes JSON data serialized using some JSON library. Are you using Jackson2? If yes, you can use Jackson annotations to specify enum serialized values.

Here is an example of `@JsonProperty` annotation usage:
https://github.com/vojtechhabarta/typescript-generator/blob/2d23071344abf43e3f7c8ebef126c40487ea35f0/typescript-generator-core/src/test/java/cz/habarta/typescript/generator/EnumTest.java#L162-L167

And here is example of `@JsonValue` usage:
https://github.com/vojtechhabarta/typescript-generator/blob/2d23071344abf43e3f7c8ebef126c40487ea35f0/typescript-generator-core/src/test/java/cz/habarta/typescript/generator/EnumTest.java#L169-L185

Both annotation are recognized and processed by typescript-generator.

BTW As you can see in samples I don't use UPPER_CASE in Java enums 🙂

**Comment by PatrykF123** [comment]
@JSonProperty solved my issue! thanks!
