### ISSUE TITLE
LineLength on generated enums not working?

### ISSUE THREAD

**Issue by PatrykF123** [vojtechhabarta/typescript-generator#196]
Hello (again ;) )

While generating a multi-valued enum, the result file has all its values in one line. In result line length exceeds 80 characters. I tried to set in command line and in pom parameter lineLength to anything else, but it seems that it didn't have any effect. Is there a way to solve this issue?

BR,
Patryk Frackowiak

**Comment by vojtechhabarta** [comment]
There is no `lineLength` parameter in typescript-generator-maven-plugin, see http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html.

Code formatting is really out of scope of typescript-generator and I think that if you have some linter or style checker in your build pipeline generated file should be excluded from it.

If you really want to achieve some code style you can add some typescript formatter to your build pipeline.

**Comment by vojtechhabarta** [comment]
BTW why do you care about line length (or generally code style) in generated file? If it is primarily because of warnings from linting we could add `/* tslint:disable */` line into generated file.

**Comment by PatrykF123** [comment]
To make it easier to read :)

**Comment by vojtechhabarta** [comment]
Ok, then I would really recommend to use some formatter 😏

**Comment by vojtechhabarta** [comment]
Closing issues after release.
