### ISSUE TITLE
Automatic class discovery from REST resources

### ISSUE THREAD

**Issue by mzuzcak** [vojtechhabarta/typescript-generator#20]
please add automatic discovery of rest classes, based on consumed and produced classes from resources.

**Comment by vojtechhabarta** [comment]
Great idea.
For example from this REST resource class:
```
@Path("user")
public class UserResource {
    @GET
    public User getCurrentUser() {}
}
```
we can discover JSON class `User`.

But we need to first discover resource classes. This could be done using some classpath scanning library or maybe we can get list of resources from JAX-RS/Jersey.

Classpath scanning is slow but this feature is meant to be turned on by user so I think this is not a problem.

**Comment by vojtechhabarta** [comment]
Implemented automatic discovery of JSON classes used in configured JAX-RS application (`classesFromJaxrsApplication` option). It is possible to exclude some resources or classes from processing using `excludeClasses` option. Also practical is to set `sortTypeDeclarations` option to sort generated interfaces alphabetically.

(part of 1.4.152 release)
