### ISSUE TITLE
gradle plugin - less functionality

### ISSUE THREAD

**Issue by stoetti** [vojtechhabarta/typescript-generator#203]
As far as I can see, the gradle plugin does not support all the parameters the maven plugin provides, e.g. npm, enum,...

Is there a way to get the according functionality when using gradle?
Is there a roadmap for adding the support in gradle?

**Comment by vojtechhabarta** [comment]
I think `typescript-generator-gradle-plugin` supports the same functionality as `typescript-generator-maven-plugin`. Do you miss some parameter? Or do you see different results from these plugins?

**Comment by stoetti** [comment]
I am missing the parameters for npm and for enum-generation

**Comment by vojtechhabarta** [comment]
This is really some misunderstanding. Here is description of parameters supported by both build plugins (Maven and Gradle): [configuration parameters](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html).

There is `generateNpmPackageJson` parametr for npm `package.json` and `mapEnum` parameter which specifies how Java enums are mapped to TypeScript.

Could you try these parameters and copy here relevant part of your configuration and output from build?

**Comment by stoetti** [comment]
When going through the code one more time it hit me like a truck... I made a mistake when adding the plugin, using an old version.

With the newest version it works fine and all the params are present.
