### ISSUE TITLE
Suggestion: customize the generated npm-script

### ISSUE THREAD

**Issue by stoetti** [vojtechhabarta/typescript-generator#208]
First of all, really nice job with this handy little tool!

In my generated typescript-file I need to import Observable-class in order to compile successfull, but with that dependency the created 'build-script' reports an error cause the used lib is lower than ES6 and the Promise-class is missing.

My suggestion is to make the created script customizable via settings or to add the oppurtinity to provide own scripts like its realized with dependencies.

**Comment by vojtechhabarta** [comment]
How would you like to change the build script? Is adding `--target ES2015` sufficient for you? I think this could be changed in code without breaking anything.

**Comment by stoetti** [comment]
in my case --lib ES6 is needed.

Another thing I fell over is that I need to define "devDependencies", are there any plans adding this possibility to settings?

**Comment by vojtechhabarta** [comment]
I thought `--target ES2015` also sets `--lib es6`, but anyway maybe `--target es5 --lib es6` would be best solution nowadays.

I don't have plans to add `package.json` features I would rather keep it minimalistic and leave this for other tools. For `devDependencies` do you think you could call `npm install some-dependency --save-dev` as next step in build process?

**Comment by stoetti** [comment]
sounds good to me

calling install save-dev made the job tx

**Comment by vojtechhabarta** [comment]
I released [v2.1.406](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.1.406). Could you please try it?

**Comment by stoetti** [comment]
Works thx
