### ISSUE TITLE
Migrating from spring boot 1.5.9 to 2.0.0.M7 : "FastClasspathScanner Error"

### ISSUE THREAD

**Issue by sparqueur** [vojtechhabarta/typescript-generator#209]
Hi,

First of all, thank's for your cool plugin. We use it on a production project and it really time saving for us.

We are currently trying to migrate from srping boot 1.5.9 to 2.0.0.M7 :
```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.0.0.M7</version>
	<!-- version>1.5.9.RELEASE</version -->
</parent>
```

As soon as I switch the version, typescript-generator plugin starts crashing : 
```[ERROR] Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.30.385:generate (generate-typescript-contract) on project formation-java: Execution generate-typescript-contract of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.30.385:generate failed: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unknown constant pool tag [I@131dcc9b in classfile module-info.class (element size unknown, cannot continue reading class. Please report this on the FastClasspathScanner GitHub page. -> [Help 1]```

There might be an incompatibility with some maven plugins.

Please find bellow a minimal test :
[spring-boot-test.zip](https://github.com/vojtechhabarta/typescript-generator/files/1603793/spring-boot-test.zip)

The following dependency seems to "break" the plugin in spring boot 2 (if you remove the dependency, everything works back)
```
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter</artifactId>
  <scope>compile</scope>
</dependency>
```

Regards,

**Comment by vojtechhabarta** [comment]
Hi @sparqueur,

thanks for this report with minimal test! I haven't tried it but I am working on typescript-generator version 2 and in last commit (6b74fc6e6ebf0588c456387dedf9a38e8b55a309) I also updated fast-classpath-scanner which could fix your problem.

If you had time you can build `master` branch and try whether it works in your case. Otherwise I will let you know once v2 is released. (Build currently only runs on Java 8, result should work on Java 8 and 9).

**Comment by sparqueur** [comment]
Hi, thanks for your quick answer,

Nice, **it's working with version 2.0-SNAPSHOT** ! 👍 

Is there anyway to expect a quick dependency update on V1 ?

Thank's in advance

**Comment by vojtechhabarta** [comment]
Hi, thanks for trying it.

V2 will be released in few days or you can override fast-classpath-scanner dependency in your pom.xml file like this:
``` xml
<plugin>
    <groupId>cz.habarta.typescript-generator</groupId>
    <artifactId>typescript-generator-maven-plugin</artifactId>
    <version>1.30.385</version>
    <executions>...</executions>
    <configuration>...</configuration>
    <dependencies>
        <dependency>
            <groupId>io.github.lukehutch</groupId>
            <artifactId>fast-classpath-scanner</artifactId>
            <version>2.9.4</version>
        </dependency>
    </dependencies>
</plugin>
```

**Comment by sparqueur** [comment]
Thank's, forcing the dependency as  suggested workds perfectly.

Good continuation !

I will continue promoting your plugin in my company ;)

**Comment by vojtechhabarta** [comment]
@sparqueur thanks!
BTW you can also give typescript-generator a star here on GitHub 😉
