### ISSUE TITLE
disable parsing message in console

### ISSUE THREAD

**Issue by istiti** [vojtechhabarta/typescript-generator#212]
after using direct call of this lib in java code in my spring boot project, I get a lot of parsing message in console 
![image](https://user-images.githubusercontent.com/2789203/35153510-16e5fa96-fd27-11e7-8074-5880aa8d9a4b.png)

Theses lines are useful : 
```
Scanning classpath
Scanning finished in 1,90 seconds. Total number of classes: 47888.
Found 159 classes matching pattern.
...
Writing declarations to: C:\Users\...\model.d.ts

```

and errors of course BUT what you think to disable all Parsing message in console to avoid pollute my console. 

Thanks 

cc @vojtechhabarta

**Comment by vojtechhabarta** [comment]
Output from typescript-generator is long but these messages ("Parsing ...") are really helpful when finding which class causes problems or why some class is parsed (by which class it is used) and which class should be excluded to prevent generating useless declarations. So I don't want to remove them and at the same time I don't want to add yet another configuration parameter for this.

**Comment by istiti** [comment]
@vojtechhabarta dammage, in big project it pollute console, we can see in output useless class, and leave in console only errors. but ok will continue with it

**Comment by istiti** [comment]
@vojtechhabarta please apologize to make noise here again, can't we imagine here add some option to enable or disable them ? Because  even if spring /hibernate are big projects with my spring boot I can only see 3/4 lines in console by default and enable what aftertime what we need.

Even if this is helpful  i think this can be option to avoid pollute console 

thanks

**Comment by vojtechhabarta** [comment]
@istiti in #234 I am changing typescript-generator to output messages through logger which can be changed.
Could you please check this PR if it is what you need?
You can use `TypeScriptGenerator.setLogger(Logger logger)` method and override `Logger.write` method.

**Comment by danielkaneider** [comment]
Such a feature would also be useful for gradle. Could you add a `verbose` property to the `GenerateTask`, such that we could set it to `false`?

**Comment by vojtechhabarta** [comment]
Ok, I will add it to Gradle and Maven plugins too.

**Comment by istiti** [comment]
good news & it works as expected, really better thanks ! you should close issue by the way

**Comment by vojtechhabarta** [comment]
Closing the issue as it is already implemented and released. Thanks @istiti for the feedback.
