### ISSUE TITLE
type DateAsString DateAsNumber instead string or number

### ISSUE THREAD

**Issue by istiti** [vojtechhabarta/typescript-generator#213]
Actually I run lib direct in code, 

in setting I have : `sett.mapDate = DateMapping.asString;`

and output in my ts file is `data: DateAsString` same with asNumber it will output `date: DateAsNumber`

instead : `date : string` or `date : number`

might be bug ?

**Comment by vojtechhabarta** [comment]
`DateAsString` is just type alias to `string`. It is used to indicate that property is not arbitrary string but date serialized as string. This alias is declared in generated file like this:

``` typescript
export type DateAsString = string;
```
