### ISSUE TITLE
jaxrs generation for file upload?

### ISSUE THREAD

**Issue by emmanueltouzery** [vojtechhabarta/typescript-generator#215]
file upload rest service as it looks on our server end (TOMEE):

```java
    @POST
    @Path("/upload")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public void upload(MultipartBody body) {
            final InputStream uploadedInputStream = body.getAttachment("file").getDataHandler().getInputStream();
            final String uploadedFilename = body.getAttachment("file").getContentDisposition().getFilename();
```
What typescript-generator generates for this REST entry point:

```typescript

    export interface MultipartBody {
        allAttachments: any[];
        childAttachments: any[];
        rootAttachment: any;
        type: MediaType;
    }

     upload(arg0: MultipartBody, options?: Axios.RequestOptions): RestResponse<..> {
         return this.httpClient.request({ method: "POST", url: uriEncoding`upload`, data: arg0, options: options });
     }
```

Probably we'd need custom support. Unfortunately I cannot contribute it at this point.

**Comment by vojtechhabarta** [comment]
Yes, currently there is no support for it.
Do you think we just need to map `MultipartBody` in Java to `FormData` in TypeScript?
Or what would you expect to be generated?

**Comment by emmanueltouzery** [comment]
hmm that's a good point... I'm using higher-level libraries, but for typescript-generator we would need to go lower-level. Right now I don't know enough on the topic :(

**Comment by vojtechhabarta** [comment]
Closing inactive issues after release.
I can reopen it if there is something new.
