### ISSUE TITLE
Support for String based Enums

### ISSUE THREAD

**Issue by gurkerl83** [vojtechhabarta/typescript-generator#218]
Hi guys, this is a great project! Is there any support for String based Enums yet? Can not figure out how something like this is done.

```

JAVA

public enum FileState {
  CREATE("file-create"),
  READ("file-read"),
  UPDATE("file-update"),
  DELETE("file-delete");

  private String key;

  FileState(String key) {
    this.key = key;
  }
  public String getKey() {
    return key;
  }

}

Typescript

enum FileState {
  CREATE = 'file-create',
  READ = 'file-read',
  UPDATE = 'file-update',
  DELETE = 'file-delete'
}

```
Does this make any sense? Also, I wanted to know if / how the typescript-generator is able to handle the JsonPropertyDescription Jackson annotation. 

Thanks for your feedback!

Markus

**Comment by vojtechhabarta** [comment]
Thanks @gurkerl83 

You can set `mapEnum` configuration parameter to `asEnum` value which will generate:
``` typescript
const enum FileState {
    CREATE = "CREATE",
    READ = "READ",
    UPDATE = "UPDATE",
    DELETE = "DELETE",
}
```

Then you can annotate your `getKey()` method with `@JsonValue` annotation and you will get:
``` typescript
const enum FileState {
    CREATE = "file-create",
    READ = "file-read",
    UPDATE = "file-update",
    DELETE = "file-delete",
}
```

Alternatively you could annotate your enum values using `@JsonProperty` annotation and remove `key` field (if you don't need it for other purposes than JSON serialization).

Regarding `JsonPropertyDescription` annotation: currently it is not used at all. Would you expect that its value is put into JSDoc in generated TypeScript declarations? If yes, could you plese create separate issue for it?

**Comment by ampirator** [comment]
Methods which is annotated with JsonValue and hasn't name prefix `get` not work. (e.g. method toValue())

**Comment by vojtechhabarta** [comment]
@ampirator are you saying that there is some bug or something missing in typescript-generator?
In that case could you please open new issue with example and what do you expect?

**Comment by vojtechhabarta** [comment]
Closing issues after release.
