### ISSUE TITLE
Additional information about type definitions

### ISSUE THREAD

**Issue by jlogar** [vojtechhabarta/typescript-generator#22]
I have feature request about which I'd like your opinion.

In our project we have many AngularJS based grids. The initialization options that set he fields go something like this:
```typescript
$scope.dtos: SomeGeneratedDtoInterface[];
 gb.setColumnDefs([
            {field: 'orderType', displayName: translate('ORDER_TYPE'), cellFilter: "translate"},
            {field: 'itemType', displayName: translate('ITEM_TYPE')},
            {field: 'issueOrderComments', displayName: translate('COMMENTS')}
        ]);
```
We would very much like to improve upon this by using TypeScript and the DTO interfaces as generated by this project. The problem is that the fields as defined above are just strings that map to actual fields in the strongly typed DTOs. Ideally we would be able to reference by using some lambda expression like:

    field: dtoType => dtoType.orderType

That is not possible with current Typescript version (probably never will be).

The solution that we were thinking about is just adding some static classes that represent the generated DTO types. So we would get:

    field: DtoType.orderTypeFieldName

Where the `orderTypeFieldName` is a const string containing the field name. So these static classes that I mention would be like type descriptors. And pretty much type safe.

I propose that we add the option to generate the above described classes. An optional extension of course.

We'd be prepared to make a PR if you think something like that would be OK for the project. Let me know and we'll prepare a more detailed proposition. Or if you have a better solution ofcourse :)

**Comment by vojtechhabarta** [comment]
@jlogar thanks for feature suggestion and detailed description of the use case.
I see some possibilities how to solve this problem:

(1) Request feature in Angular grid that would allow to pass function to `field` property. This function would took grid row as a parameter and returned needed value. Example:
``` typescript
// generated
interface SomeGeneratedDtoInterface {
    orderType: string;
}
// usage
field: (row: SomeGeneratedDtoInterface) => row.orderType
```
This is clean solution and does not require any special feature in typescript-generator.

(2) Wait for [String Literal Types](https://github.com/Microsoft/TypeScript/pull/5185) feature. This feature together with _union types_ should help with this type of issues. It will be part of TypeScript [version 1.8](https://github.com/Microsoft/TypeScript/wiki/Roadmap).

(3) Generate class with string constants as you are suggesting. But it is not sufficient to declare this class in `*.d.ts` file like this:
``` typescript
declare class DtoType {
    static orderTypeFieldName;
}
```
This class must be in runnable `*.ts` file which is then compiled to `*.js` file.
``` typescript
class DtoType {
    static orderTypeFieldName = "orderType";
}
```
Currently typescript-generator is meant to describe systems written in Java. For this I think declaration files (`*.d.ts`) are proper solution. They doesn't produce any JavaScript code, they're just for compilation. On the contrary `*.ts` file must be compiled to `*.js` file and loaded by application. This adds complexity. I would like to stick with declaration files as long as practical.

So if modifying Angular grid (1) is not feasible I would prefer (2).
What do you think?

**Comment by jlogar** [comment]
I didn't know of the coming feature in TS. I definitely agree. Option (2) is best in the long term. 
BTW: Option (1) is no good to us since it's just an example usage. There's a few different use cases with other libraries/framework.

Thank you for your time & feedback.
