### ISSUE TITLE
Execution configuration seems to be ignored by plugin

### ISSUE THREAD

**Issue by polifr** [vojtechhabarta/typescript-generator#220]
Hi,
I am trying to configure the plugin execution to generate different ts files for groups of classes, referring to different classPatterns tags, using multiple configurations, one for each plugin execution.
What I am seeing is that if I try to put the <configuration> tags into the <execution>, i.e. like this:
```
<plugin>
    <executions>
        <execution>
            <foo>...</foo>
            <configuration>...</configuration>
        </execution>
    </executions>
</plugin>
```

With no <configuration> specified as a <plugin> direct node, I receive the error:
The parameters 'outputKind', 'jsonLibrary' for goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.1.406:generate are missing or invalid -> [Help 1]

This seems that the inner configuration is ignored at execution time.

Thank you!

**Comment by vojtechhabarta** [comment]
Hi,
Here are issues with similar questions: #193, #146.
If it doesn't help could you please paste complete plugin configuration structure (remove all values you don't want to share). How do you invoke the plugin?
