### ISSUE TITLE
GSON Support

### ISSUE THREAD

**Issue by jwcarman** [vojtechhabarta/typescript-generator#222]
Have you considered supporting the GSON Json library?  Would you accept a quality PR if it were submitted adding GSON support?

**Comment by vojtechhabarta** [comment]
Yes, that was my initial plan to support also GSON (see #3) but it seemed nobody was interested.

Do you know how to implement it?

**Comment by jwcarman** [comment]
I could give it a whirl.  I just didn't want to start work if you had already chosen not to support GSON.  I can take a look.  I briefly investigated it and it looks like it might be tough to do the introspection necessary, but I'll keep digging.  I'm probably missing something.

**Comment by chinhodado** [comment]
I would love to have GSON supported as well

**Comment by cjnygard** [comment]
@jwcarman it might be easier to implement the introspection via ClassGraph.  See PR https://github.com/vojtechhabarta/typescript-generator/pull/261 for the port to ClassGraph.  This might help the GSON implementation.

**Comment by vojtechhabarta** [comment]
I don't want to use any dependency in GSON support except for Java reflections and GSON library itself.
It should not be much harder and it eliminates impact when the dependency is changed or deprecated.

@jwcarman do you have any plans to implement GSON support? Or anybody else?

**Comment by ruediste** [comment]
I'm using GSON in my project and can give it a go. Is basic support sufficient for a PR to be accepted, or should only close to perfect support go into the project?

**Comment by vojtechhabarta** [comment]
I can create structure for this support and then it can be implemented iteratively as needed.

**Comment by vojtechhabarta** [comment]
GSON is already supported, thanks to everybody who contributed, closing issue.
