### ISSUE TITLE
Use @ApiModelProperty attribute dataType to override target type

### ISSUE THREAD

**Issue by littleli** [vojtechhabarta/typescript-generator#227]
### Problem statement

I encounter such a situation that I need to override target type to be different from the one specified by type declared in bean. Imagine this

```java
class Entity {
  public String property1;
  
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Id
  @JsonSerialize(using = IdSerializer.class)
  @JsonDeserialize(using = IdDeserializer.class)
  public Long id; // is converted on-the-fly to some string hash
}
```
Such situation comes from the fact that bean is used for persistence to a database with a property used as a incremental sequence with JPA of type Long. Same bean have an annotation that marks this field with custom JSON de+serializer that produces string which is used for communication with REST API.

In such situation typescript definition currently produces `number` as target type. However proper type should be `string` because it is how it is treated by `IdSerializer` and `IdDeserializer`

```typescript
interface Entity {
  property1: string;
  id: number;
}
```

### Proposed solution

There is a Swagger annotation to the rescue with `dataType` attribute. It should be taken into account as a source of truth so that proper type declaration is generated.

```java
class Entity {
  public String property1;
  
  @ApiModelProperty(value = "Comment goes here", dataType = "java.lang.String")
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Id
  @JsonSerialize(using = IdSerializer.class)
  @JsonDeserialize(using = IdDeserializer.class)
  public Long id;
}
```
and generated typescript interface should look like this:

```typescript
interface Entity {
  property1: string;
  id: string;
}
```

**Comment by vojtechhabarta** [comment]
Thanks for this detailed and clear description.

PR #228 is merged and released in [v2.2.413](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.2.413).
