### ISSUE TITLE
FeatureRequest: nullable properties with " | null" union types

### ISSUE THREAD

**Issue by Xceno** [vojtechhabarta/typescript-generator#229]
First of, thanks for your package!
Would it be possible to implement an option that will render optional properties like this:

```TypeScript
interface Something {
    someProp: string | null
}

// Alternative
class Something {
   public someProp: string | null = null;
}
```

Instead of:

```TypeScript
interface Something {
    someProp?: string
}
```

The reason is, that `undefined` properties simply don't exist on an object whereas properties that are initialized with `null` do. This allows for better usage of reflection.

----

Another request would be an additional option `requiredAnnotations`, which should do the inverse of `optionalAnnotations`. So you could configure the plugin to output everything as optional except properties annotated by `requiredAnnotations`.

```XML
<configuration>
    <optionalProperties>all</optionalProperties>
    <requiredAnnotations>
        <annotation>NotNull</annotation>
    </requiredAnnotations>
</configuration>
```

**Comment by vojtechhabarta** [comment]
This feature was already proposed in #207.

In 54706b8be86f94cd7b4495f126b8ab3d23a6dfdd I implemented `optionalPropertiesDeclaration` parameter, see [optionalPropertiesDeclaration](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#optionalPropertiesDeclaration) description.

**Comment by vojtechhabarta** [comment]
Regarding your second point: would it be alternative for you to use `@JsonProperty(required = true)` annotation?
If yes you could set `optionalProperties` parameter to `useLibraryDefinition` value.

**Comment by Xceno** [comment]
Ah! Thanks for implementing the new `optionalPropertiesDeclaration`. I've overlooked #207, sorry!

Yes, I've actually used `@JsonProperty(required = true)` in the end. It's just that the other way round would mean way less code for us. But I can live with it for now. Case closed :)
