### ISSUE TITLE
Idea: JSweet integration

### ISSUE THREAD

**Issue by renaudpawlak** [vojtechhabarta/typescript-generator#23]
The JSweet project will develop a similar feature soon (Java @Ambiant classes => d.ts).
How about contacting us to talk about how your tool could be used in JSweet?
(http://www.jsweet.org)

**Comment by vojtechhabarta** [comment]
Outcome of email conversation was that JSweet has different (and bigger) goal than this project. typescript-generator is focused (at least currently) on describing JSON data classes.
Thanks @renaudpawlak
