### ISSUE TITLE
Publish v. 2.2.414 to maven central

### ISSUE THREAD

**Issue by gurkerl83** [vojtechhabarta/typescript-generator#230]
Hi,
any chance we see the latest version (2.2.414) at maven central anytime soon?

Thanks!

**Comment by vojtechhabarta** [comment]
I will make release soon...

**Comment by vojtechhabarta** [comment]
Released [v2.3.415](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.3.415).
