### ISSUE TITLE
Naming sub resource methods?

### ISSUE THREAD

**Issue by krezovic** [vojtechhabarta/typescript-generator#233]
Hi,

Sorry if this is already documented here. I'm facing a problem here, which comes to following:

I have a JAX-RS sub resource Foo, which has method "getFoo()", and @GET("{fooId}") annotation.

I have resource A invoke sub resource Foo from through "rest/a/{id}/foo"
I have sub resource B of resource A invoke sub resource Foo through path "rest/a/{id}/b/{bId}/foo"

The generated file produces method names like

```
getFoo$GET$a_id_foo_fooId
getFoo$GET$a_id_b_bId_foo_fooId
```

Is there a way to get nicer names? Can the sub resource invocation method be appended as the prefix there? Can an annotation be used for sub resources invocations? Any other solutions? Looking forward to your answer.

**Comment by krezovic** [comment]
Hi, sorry for the late reply.

I have (had) the following organisation:

```
class FooSubResource {
  @GET
  @Path("/{fooId}")
  public FooProjection getFoo(@PathParam("fooId") Integer fooId) {
    return new FooProjection();
  }
}
```

```
class BarSubResource {
  @Inject private FooSubResource fooSubResource_;

  @GET
  @Path("/{barId}")
  public BarProjection getBar(@PathParam("barId") Integer barId) {
    return new BarProjection();
  }

  @Path("/{barId}/foo")
  public FooSubResource invokeFooSr(@PathParam("barId") Integer barId) {
    return fooSubResource_;
  }
}
```

```
@Path("/root")
class RootResource {
  @Inject private BarSubResource barSubResource_;
  @Inject private FooSubResource fooSubResource_;

  @Path("/{id}/bar")
  public BarSubResource invokeBarSr(@PathParam("id") Integer id) {
    return barSubResource_;
  }

  @Path("/{id}/foo")
  public FooSubResource invokeFooSr(@PathParam("id") Integer id) {
    return fooSubResource_;
  }
}
```

Final endpoints for RootResource are:

```
/root/{id}/bar/{barId} getBar()
/root/{id}/bar/{barId}/foo/{fooId} getFoo()
/root/{id}/foo/{fooId} getFoo()
```

Note the two getFoo(), invoked from different locations (don't ask). Solution (for those that need it) was:

```
@Path("/root")
class RootResource {
  @Inject private BarSubResource barSubResource_;

  @Path("/{id}/bar")
  public BarSubResource invokeBarSr(@PathParam("id") Integer id) {
    return barSubResource_;
  }
}
```

```
@Path("/root")
class RootFooResource {
  @Inject private FooSubResource fooSubResource_;

  @Path("/{id}/foo")
  public FooSubResource invokeFooSr(@PathParam("id") Integer id) {
    return fooSubResource_;
  }
}
```

and enabling per-resource client generation.

**Comment by vojtechhabarta** [comment]
Thanks for detailed explanation. I didn't realized that naming conflict occurs also in this case.

And thanks for the solution.

**Comment by vojtechhabarta** [comment]
Closing the issue (as part of cleanup after release).
Thanks again for sharing your issue and solution.
