### ISSUE TITLE
Circular dependency in V1 to V2 version bump (gradle)

### ISSUE THREAD

**Issue by JonathanSawyer** [vojtechhabarta/typescript-generator#235]
When migrating from v1.27.339 to v2.0.400 ~ 2.4.418 we got the following.

```
Circular dependency between the following tasks:
:projectName:projectName-cms:classes
\--- :projectName:projectName-cms:processResources
     \--- :projectName:projectName-cms:gulp_default
          \--- :projectName:projectName-cms:generateTypeScript
               \--- :projectName:projectName-cms:compileTestJava
                    \--- :projectName:projectName-cms:classes (*)
```
We included ⬇️ in gradle
`generateTypeScript.setDependsOn([compileJava])` which works. Is this the right approach? 

Seemed odd because done here https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-gradle-plugin/src/main/java/cz/habarta/typescript/generator/gradle/TypeScriptGeneratorPlugin.java#L16 is my understanding correct? 

Great tool, using for both Kotlin and Java models.

**Comment by vojtechhabarta** [comment]
It seems that you have some task (maybe `compileTestJava`) that depends on `generateTypeScript` task and at the same time `TypeScriptGeneratorPlugin` adds dependencies from `generateTypeScript` task to all `compile*` tasks. The reason for this was that typescript-generator should have access to all compiled classes (Java, Groovy, Kotlin etc.).

So I think your solution is right (to override `generateTypeScript` dependencies to only dependency you need).

**Comment by vojtechhabarta** [comment]
Closing the issue (as part of cleanup after release).
Hopefully current Gradle plugin behavior works in most cases and can be overridden in remaining cases.
Thanks for the feedback.
