### ISSUE TITLE
Convert to ES6 Map

### ISSUE THREAD

**Issue by fridoo** [vojtechhabarta/typescript-generator#236]
I would like to convert a Java Map to an ES6 Map. 

From Java:
`public Map<String, Object> someMap;`

To Typescript:
`someMap: Map<string, any>;`

instead of
`someMap: { [index: string]: any };`

Is this possible somehow?

**Comment by vojtechhabarta** [comment]
There is `customTypeMappings` parameter but it doesn't work with generics.
I'm thinking about improving it.

**Comment by vojtechhabarta** [comment]
Finally I returned to this issue and it is now possible to use generics in `customTypeMappings` parameter.
Released in [v2.10.466](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.10.466).

**Comment by vojtechhabarta** [comment]
Unfortunately mentioned change in [v2.10.466](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.10.466) broke mapping of generic classes to TypeScript non-generic types like `string`. So in [2.16.538](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.16.538) release I changed `customTypeMappings` parameter format (#384) and it is now needed to specify generic classes including their generic parameters.
