### ISSUE TITLE
Generating interface vs class

### ISSUE THREAD

**Issue by thepian** [vojtechhabarta/typescript-generator#238]
I've looked over the Emitter. It seems to have a distinction between interfaces and classes, but I cannot see the isClass being set on TsBeanModel, hence it always makes an interface.

What is the intention?

**Comment by vojtechhabarta** [comment]
You can generate classes when you set `mapClasses` parameter to `asClasses` value.

This can only be used when generating implementation file (`*.ts`) so set also `outputFileType` parameter to `implementationFile` value.

**Comment by vojtechhabarta** [comment]
Here is description of all parameters: http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html

**Comment by thepian** [comment]
Thanks. The isClass member variable had me confused, but I eventually stumbled over the wiki.
