### ISSUE TITLE
DTOs as nested classes

### ISSUE THREAD

**Issue by emmanueltouzery** [vojtechhabarta/typescript-generator#24]
the maven plugin doesn't work well when DTOs are contained as nested classes, eg:

    public class NestedClass {

        public static class NestedDto {
            public String testField;
        }
    }

if in the <classes> tag within the maven configuration you like the outer class, that is `NestedClass`, then the typescript DTO comes out empty.
If you like the nested class like `NestedClass.NestedDto`, then there is a build error:

    Execution generate of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.3.134:
    generate failed: java.lang.ClassNotFoundException: <classname>

I see two possible fixes:
1. when parsing a DTO class, `typescript-generator` should also check for nested classes to generate DTOs for them
2. the maven frontend should be fixed to make sure it can also find nested classes instead of hitting the `ClassNotFoundException`

Except if it's already supported today through another path?

**Comment by vojtechhabarta** [comment]
If you want TypeScript interface for `NestedDto` class you can configure typescript-generator like this:
``` xml
<classes>
    <class>com.example.NestedClass$NestedDto</class>
</classes>
```
Please note the `$` character.
Does this work for you? Or could you paste your configuration here?

**Comment by emmanueltouzery** [comment]
yes, it works for me. Sorry, that was my fault entirely... I knew the files had a `$` in the filename but didn't expect the classloader wanted it too... Thank you for the tip!

**Comment by vojtechhabarta** [comment]
Great to hear that it works as you need.
