### ISSUE TITLE
ClassNotFoundException when using optionalAnnotations

### ISSUE THREAD

**Issue by beleta** [vojtechhabarta/typescript-generator#240]
I am getting this error:

`Execution generate of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.5.423:generate failed: java.lang.ClassNotFoundException: javax.annotation.Nullable (cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.5.423:generate:generate:process-classes)`

When using this plugin configuration:

 ```
<plugin>
  <groupId>cz.habarta.typescript-generator</groupId>
  <artifactId>typescript-generator-maven-plugin</artifactId>
  <version>2.5.423</version>
  <executions>
    <execution>
      <id>generate</id>
      <goals>
        <goal>generate</goal>
      </goals>
      <phase>process-classes</phase>
    </execution>
  </executions>
  <configuration>
    <jsonLibrary>jackson2</jsonLibrary>
      <classPatterns>com.carveras.beca.escola.model.*</classPatterns>
      <excludeClassPatterns>com.carveras.beca.escola.model.*_</excludeClassPatterns>
    <outputFile>src-ts/app/model.d.ts</outputFile>
    <outputKind>module</outputKind>
    <optionalAnnotations>javax.annotation.Nullable</optionalAnnotations>
    <optionalPropertiesDeclaration>nullableType</optionalPropertiesDeclaration>
   </configuration>
   <dependencies>
	   <dependency>
		   <groupId>javax.annotation</groupId>
		   <artifactId>javax.annotation-api</artifactId>
		   <version>1.2</version>
     </dependency>
   </dependencies>
 </plugin>
```

Any help will be appreciated.

**Comment by vojtechhabarta** [comment]
Try moving `javax.annotation` dependency from plugin dependencies to compile dependencies of the module.

I mean this part:
``` xml
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.2</version>
</dependency>
```

**Comment by beleta** [comment]
The annotation-api jar was already available in the maven resolved dependencies, but following your suggestion I added it to the compile dependencies: same result.

I am executing the build process on Eclipse (Project Clean), using the included m2e Plugin.

**Comment by beleta** [comment]
Forget my problem. Java Maven packaging is a nightmare, `javax.annotations.Nullable` is not in artifact `javax.annotation-api` but in `jsr305` of groupId `com.google.code.findbugs`. !!!???

**Comment by vojtechhabarta** [comment]
You are right, I found `javax.annotation.Nullable` in `com.google.code.findbugs:jsr305:3.0.1` maven artifact.

**Comment by vojtechhabarta** [comment]
Problem seems to be solved, closing the issue.
