### ISSUE TITLE
Recommended method for configuring multi-project projects

### ISSUE THREAD

**Issue by bradleysmithllc** [vojtechhabarta/typescript-generator#241]
I am trying to figure out where to fit this plugin in our build process.  I would like to have an API maven module, which contains java classes with our data model, then have two other maven projects, one which defines the REST application and uses the data model module, and another angular maven module which uses the data model module.  I can't figure out if I should declare this plugin to the data model module or the front-end angular module.  Do you have a sample or pattern I could follow?

**Comment by vojtechhabarta** [comment]
I would have just two modules: Java REST application and TypeScript Angular application.
Then you could run typescript-generator in REST module and Angular module would depend on REST module.
What do you think?

**Comment by bradleysmithllc** [comment]
Sounds good, and that fixes the problem I had with getting the angular app to pull the java classes out of the external app.  I kept just getting no classes defined errors.

At this point, my java app has a package called 'model', and I generate my typescript classes from that and use the assembly plugin to make a zip of that file, then the angular app use the dependency plugin to pull that assembly and unzip it into the src/app/model folder.  Is that the best way?

By the way, thanks for all the effort you have put into this project.

**Comment by vojtechhabarta** [comment]
Yes, using assembly plugin and then dependency plugin is in my opinion best way how to use generated TypeScript files in dependent module.

BTW in addition to generating TypeScript interfaces from Java model you can also try to generate TypeScript client for your REST API. See https://github.com/vojtechhabarta/typescript-generator/wiki/JAX-RS-Application#2-jax-rs-application-client

**Comment by vojtechhabarta** [comment]
Closing the issue (as part of cleanup after release). Hopefully your build now works well.
