### ISSUE TITLE
Generating js output of the ts file

### ISSUE THREAD

**Issue by alirezamirian** [vojtechhabarta/typescript-generator#244]
We are using this plugin to maintain a generated npm package for types and use that in frontend via npm. 
The problem is that Enums don't work at runtime, and are undefined. We use `<mapEnum>asEnum</mapEnum>` and `<nonConstEnums>true</nonConstEnums>` and also
`<outputFileType>implementationFile</outputFileType>`.
When I put the js transpiled version of the generated types beside it, it works fine but without that, enums are undefined in runtime.

**Comment by vojtechhabarta** [comment]
I am not sure what you exactly mean. When I use following settings in test:
``` java
settings.outputFileType = TypeScriptFileType.implementationFile;
settings.outputKind = TypeScriptOutputKind.module;
settings.mapEnum = EnumMapping.asEnum;
settings.nonConstEnums = true;
```
generated enum looks like this:
``` typescript
export enum Direction {
    North = "North",
    East = "East",
    South = "South",
    West = "West",
}
```
When you are generating implementation file (`*.ts`) you need to compile it somewhere to `*.js` file.

When I compiled this TypeScript code I got following JavaScript code:
``` javascript
var Direction;
(function (Direction) {
    Direction["North"] = "North";
    Direction["East"] = "East";
    Direction["South"] = "South";
    Direction["West"] = "West";
})(Direction = exports.Direction || (exports.Direction = {}));
```
So when you import this file then `Direction` should be usable.

Is this what you expect?

**Comment by alirezamirian** [comment]
You are absolutely right.
The point is, I generate ts code and push it to a separate repository, say
`generated-types` automatically in each build. This generated repository is
added to frontend repo as an npm dependency. So it will be used from within
node_modules in frontend code, and therefore typescript assumes this is
already transpiled to js, and looks for a js file beside it, which doesn't
exist, and therefore nothing is emitted in the final bundle for enums, and
they end up being undefined.

If typescript-generator would support generating transpiled js in addition
to ts file, everything would work great.

**Comment by vojtechhabarta** [comment]
This is really disadvantage of generating `.ts` files instead of `.d.ts` file, it needs to be compiled.

I don't have any plans to generate JavaScript code because that's really responsibility of TypeScript compiler.

It is possible to generate `package.json` file using `generateNpmPackageJson` parameter. And if you want to invoke TypeScript compiler from Maven you can use `frontend-maven-plugin` which is able to download nodejs and run it.

**Comment by vojtechhabarta** [comment]
Closing the issue (as part of cleanup after release).
Hopefully you solved the problem to your needs. We can reopen the issue if needed.
