### ISSUE TITLE
Maven and pom packaging - No input classes found

### ISSUE THREAD

**Issue by petosorus** [vojtechhabarta/typescript-generator#245]
Hello!

I am trying to make the generator work on my project but I'm not sure I understand how to use it exactly.

I have one parent pom.xml, which defines some modules.
There is no code alongside this parent, only in the modules.

When I try using the <classes> tag with a class that's defined in one of the modules, I get a "no input classes found". I was wondering if that is due to the fact I am trying to use it in a pom.xml with pom packaging?

**Comment by vojtechhabarta** [comment]
Hello,

yes, you should run typescript-generator in a Java module, where your classes are (for example jar or war packaging).

And then if you run typescript-generator in multiple modules you can put common settings to the parent pom.xml.

**Comment by petosorus** [comment]
Ok I see. Thank you :)
