### ISSUE TITLE
@JsonUnwrapped Not Working As Expected

### ISSUE THREAD

**Issue by steve-oakey** [vojtechhabarta/typescript-generator#247]
See [steve-oakey/typescript-generator-jsonunwrapped](https://github.com/steve-oakey/typescript-generator-jsonunwrapped) for sample project to reproduce. Wondering if I am missing something trivial in my configuration or misunderstanding something.

Based on [JsonUnwrappedTest](https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-core/src/test/java/cz/habarta/typescript/generator/JsonUnwrappedTest.java), given classes:
```java
package ca.oakey.typescript.model;

public class Name {
    private String first;
    private String last;

    public String getFirst() {
        return first;
    }

    public String getLast() {
        return last;
    }
}

public class Person {
    @JsonUnwrapped
    private Name name;

    public Name getName() {
        return name;
    }
}
```
and Maven Configuration:
```xml
<configuration>
    <jsonLibrary>jackson2</jsonLibrary>
    <classPatterns>
        <class>ca.oakey.typescript.model.*</class>
    </classPatterns>
    <outputFile>${project.build.directory}\npm\model.d.ts</outputFile>
    <outputKind>ambientModule</outputKind>
    <module>model</module>
</configuration>
```
## Expected Output
```typescript
/* tslint:disable */
// Generated using typescript-generator version 2.5.423 on 2018-07-25 13:44:18.

declare module "model" {

    interface Name {
        first: string;
        last: string;
    }

    interface Person {
        first: string;
        last: string;
    }

}
```
## Actual Output
```typescript
/* tslint:disable */
// Generated using typescript-generator version 2.5.423 on 2018-07-25 13:44:18.

declare module "model" {

    interface Name {
        first: string;
        last: string;
    }

    interface Person {
        name: Name;
    }

}
```

**Comment by vojtechhabarta** [comment]
@steve-oakey thanks for clear explanation of the issue.

If you move `@JsonUnwrapped` from your private field to public getter it should work as expected.

I also pushed commit which should make your case (`@JsonUnwrapped` on backing field) to work as well.

**Comment by vojtechhabarta** [comment]
Change is now released, closing the issue.
