### ISSUE TITLE
Conditionally use non-const enums

### ISSUE THREAD

**Issue by danielkaneider** [vojtechhabarta/typescript-generator#248]
As far as I can see there is an option to make all the enums const or not. In terms of performance we are using the const version for all. It turns out that there are some situations were some of the enums should preferably non-const. If we agree on the API I'm willing to provide a PR for that. 
My proposal:
- add a `nonConstEnumAnnotations : List` setting which forces enums to be exported as non-const. Since const enums seem to be the default one, an opposite annotation like (constEnumAnnotations) is not necessarily needed

**Comment by vojtechhabarta** [comment]
Yes, since "const" is default, I would add `nonConstEnumAnnotations` next to `nonConstEnums` parameter in `Settings`, `GenerateMojo` and `GenerateTask`.

And I would add something like `isNonConstEnum` to `TsEnumModel` and move the logic from `Emitter` to `ModelCompiler`.
