### ISSUE TITLE
excludePropertyAnnotations Feature request

### ISSUE THREAD

**Issue by dhakehurst** [vojtechhabarta/typescript-generator#251]
You have a configuration option includePropertyAnnotations,

it would be nice to have a corresponding

excludePropertyAnnotations:
     If this list is not empty then TypeScript will only be generated for methods WITHOUT one of the annotations defined in this list.

**Comment by vojtechhabarta** [comment]
If you are using Jackson2 you can use `@JsonIgnore` annotation which should do what you wanted.
(I just added test for it: 43cb1e64d4f3e1e399ec31281c4c419d87e1ed7c.)

**Comment by dhakehurst** [comment]
I think that misses the point of the request.
I don’t want to add more annotations. I want to tell the generator not to
generate things that have an existing annotation.

No not using jackson or any other standard set of annotations.

**Comment by vojtechhabarta** [comment]
Finally I returned to this issue and added `excludePropertyAnnotations` parameter.
Released in [v2.10.466](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.10.466).
