### ISSUE TITLE
Optional annotations do not support TYPE_USE targetted annotations

### ISSUE THREAD

**Issue by cghislai** [vojtechhabarta/typescript-generator#252]
I noticed the optional annotations processing only takes into account annotations declared with `@Target({ElementType.FIELD})`. The checker framework contains null-safety annotations targetting the newly added `TYPE_USE` and `TYPE_PARAMETER` element types: 
```
@SubtypeOf({})
@ImplicitFor(literals = LiteralKind.NULL, typeNames = java.lang.Void.class)
@DefaultInUncheckedCodeFor({TypeUseLocation.RETURN, TypeUseLocation.UPPER_BOUND})
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
public @interface Nullable {}
```
Fields annotated with those are not marked as optional in the generated typescript files.

**Comment by vojtechhabarta** [comment]
I am not sure what you mean. I guess you are aware of `optionalProperties` and `optionalAnnotations` parameters. Could you please provide some example how you are using `Nullable` annotation?

**Comment by cghislai** [comment]
Sure.
If I have a bean like this one:

```
import com.charlyghislain.auth.api.common.annotation.NullableField;
import com.charlyghislain.auth.api.common.annotation.NullableFieldOnTypeUse;
import org.checkerframework.checker.nullness.qual.Nullable;

import java.util.Optional;

public class TestBean {

    @Nullable
    private String nullableFieldA;
    @NullableField
    private String nullableFieldB;
    private Optional<String> nullableFieldC;
    @NullableFieldOnTypeUse
    private String nullableFieldD;

   // getter/setter
}
```

And usse the following plugin configuration:
```
 <groupId>cz.habarta.typescript-generator</groupId>
  <artifactId>typescript-generator-maven-plugin</artifactId>
  <version>2.5.423</version>
<!--  ... -->
<jsonLibrary>jackson2</jsonLibrary>
<outputKind>module</outputKind>
<outputFileType>declarationFile</outputFileType>
<optionalAnnotations>
<optionalAnnotations>
  <annotation>org.checkerframework.checker.nullness.qual.Nullable</annotation>
  <annotation>com.charlyghislain.auth.api.common.annotation.NullableField</annotation>
  <annotation>com.charlyghislain.auth.api.common.annotation.NullableFieldOnTypeUse</annotation></optionalAnnotations>
</optionalAnnotations>                            
```

Then i get the following typescript code generated:
```
export interface TestBean {
    nullableFieldA: string;
    nullableFieldB?: string;
    nullableFieldC?: string;
    nullableFieldD: string;
}
```

Notice the field A is not marked as optional.
The `org.checkerframework.checker.nullness.qual.Nullable` annotation is defined as like pasted in the original post, while the other two are like this:
```

@Target({
        ElementType.FIELD,
})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface NullableField {
}
```
```
@Target({
        ElementType.TYPE_USE,
})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface NullableFieldOnTypeUse {
}
```

I suspect the fact that the annotation targets `TYPE_USE rather than `FIELD` prevents it to be correctly processed by the generator.

**Comment by vojtechhabarta** [comment]
Thanks for detailed description.

Could you please try to move the `@Nullable` annotation from `nullableFieldA` field to `getNullableFieldA` getter? Maybe this is a problem similar to #247.

**Comment by cghislai** [comment]
Moving the annotation on the getter does not help :(
I debugged the cause down to jackson-databind. They use [java.lang.reflect.Field#getDeclaredAnnotations()](https://github.com/FasterXML/jackson-databind/blob/bb870ae3ee5d982a9f0b80596b13a75e80de9f68/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotatedFieldCollector.java#L77), but not Field#getAnnotatedType(), so this information is not available is their model.

I doubt jackson will support TYPE_USE annotation anytime soon since that would mean quite some work to fully support it (ie alter serialization by placing annotations on generics and so on)...

I suppose this should not be fixed in this project neither. If you feel so I can reopen. Im happy with using other annotations, but maybe this limitation should be mentionned in the maven doc.
