### ISSUE TITLE
generate type of unused enum in classe

### ISSUE THREAD

**Issue by istiti** [vojtechhabarta/typescript-generator#256]
I have 
![image](https://user-images.githubusercontent.com/2789203/44446936-e94d0480-a5e6-11e8-9a6d-ab2cd9199351.png)

And I expect PaymentsProposalValidationType to be generated to my output file but it wont since I don't use it as a property of CreditorProposalPaymentDTO. 

If I add property `public PaymentsProposalValidationType temp;` in CreditorProposalPaymentDTO it is ok

How can I expect this enum generated even if not used in thsi class.

**Comment by vojtechhabarta** [comment]
If `PaymentsProposalValidationType` enum is not used anywhere in generated output (not just in `CreditorProposalPaymentDTO`) you can add it using `classes` parameter as `your.package.CreditorProposalPaymentDTO$PaymentsProposalValidationType`.
