### ISSUE TITLE
BeanParam implementation

### ISSUE THREAD

**Issue by RobbinBaauw** [vojtechhabarta/typescript-generator#259]
Hello,

I'm working on a project in which I would like to use this project.

For this project I use RestEasy (JAX-RS implementation). To be able to provide multiple parameters using JSON I use application/www-x-form-urlencoded with @FormParam and @BeanParam, example:

```
@POST
@Path("amethod")
public String login(@BeanParam Test test, @FormParam("stringExample")) {
        // Do something
}
```
```	
public class Test {
    @FormParam("test1") private int test1;
    @FormParam("test2") private String test2;
}
```

On this way I can call the method using POST, with the body formatted with JSON (using the qs.stringify method to go from JSON to www-x-form-urlencoded). Though I am not sure yet whether this is actually good practice, but I guess that's a different matter.

Unfortunately this doesn't work with this library, BeanParam doesn't seem to be recognized. In [here](https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/parser/JaxrsApplicationParser.java#L251) it seems like FormParam is implemented, but Beanparam isn't.

Is this my mistake or is BeanParam not implented? Is this planned to be implemented?

**Comment by vojtechhabarta** [comment]
Hello, `BeanParam` is not currently supported. Maybe I will implement it sometime in the future.

**Comment by RobbinBaauw** [comment]
Hm thanks!

If I wanted to use JSON, without www-x-form-unencoded, which annotation / method does the generator use to detect arguments? 

It seems that it uses both getters and annotations, as in the following code it puts "username" and "emailAddress" in the interface:

```
@JsonProperty("emailAddress")
private String emailAddress;

//Left out code for brevity

public String getUsername() {
	return emailAddress;
}

public void setUsername(String emailAddress) { this.emailAddress = emailAddress; }
```
When I change the setUsername to something else and leave the getUsername, it still shows "username", and when I change the getUsername to something else it does update the Typescript interface. So the conclusion is that it uses the name of the getter to create the interface? It this intended behaviour and is it possible to turn the detection of this getter off and annotate each JsonProperty myself?

**Comment by vojtechhabarta** [comment]
Typescript-generator gets list of fields from Jackson. You can use Jackson annotations to configure what Jackson considers as a field. You can for example annotate your class using this:
```
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE)
```
Alternatively you can use `@JsonIgnore` annotation.

**Comment by RobbinBaauw** [comment]
Thanks for answering (and for the plugin)! Closing this issue as resolved
