### ISSUE TITLE
Enums in QueryParameters not generated on the client side

### ISSUE THREAD

**Issue by krezovic** [vojtechhabarta/typescript-generator#266]
I have a following Resource on the backend

```
@GET
@PATH("somePath")
public List<Foo> getFoo(@QueryParam("target") TargetEnum target) {
  ...
}
```

On the client side, the enum is specified, but the enum definition is not generated. I need to manually add the enum to the list of classes. Can you please consider enum type generation in QueryParams? Thx

**Comment by vojtechhabarta** [comment]
Finally I returned to this issue and now enums are correctly generated when used as `@QueryParam`.
Released in [v2.10.466](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.10.466).
