### ISSUE TITLE
Unable to add plugin via new gradle plugins block

### ISSUE THREAD

**Issue by Jendoliver** [vojtechhabarta/typescript-generator#277]
I am trying to use this plugin via the new gradle plugins block instead of using `apply plugin`, but as far as I know this won't work unless the plugin is submitted to the gradle plugin repository (https://plugins.gradle.org). I searched for it there and it seems like it really doesn't exist.

Is there any particular reason why we should use the legacy version? I'm not any gradle expert but I've read that this way of adding plugins is intended to be standard right now. I also have some other plugins added this way and being forced to change them to use the old version would be a little bit of a pain.

If possible, I think it would be great if someone could upload the plugin to the repository. This would make adding the plugin easier for someone accostumed to the new gradle syntax (and if I'm not wrong and this is really the new standard way, it should be added like this in new gradle versions). I could update the readme myself describing how to use the new syntax if it's needed after this has been done.

Thank you very much for your work!

**Comment by vojtechhabarta** [comment]
Documented way how to publish Gradle plugins to Gradle plugin portal is to use Gradle "Plugin Publishing Plugin" but typescript-generator is built using Maven and releases are published to Maven central repository.

Since I don't want to use two build systems to build typescript-generator I've searched for possibilities how to publish already released versions to Gradle plugin portal but I didn't find any possibility (no manual upload using UI, no REST API documentation).

Maybe somebody could comment how to do this.

But I would wondered if it would not be possible to combine plugins from Maven central repository with plugins from Gradle plugin portal.

**Comment by Jendoliver** [comment]
Nevermind, it was me don't knowing to make it work. While it's true that if possible Gradle plugins should now be updated to the Gradle plugin repository, I understand that it overcomplicates your project having to manage two different build systems just for being compliant with new versions (which maybe become deprecated in one or two years, seeing how fast the Gradle team likes to make working things obsolete). Maybe someone in the future makes some kind of Maven plugin to update to the Gradle repo, so plugins like yours can still being uploaded there without forcing managers to use two build systems.

There is, as you suggested, a way to use both plugins systems which I struggled way more than I should to find, since it's pretty obvious. So sorry to waste your time, and anyway thank you for thinking about it. I'll leave my build.gradle here just in case someone faces the same problem!

`
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'cz.habarta.typescript-generator:typescript-generator-gradle-plugin:2.7.447'
    }
}

plugins {
    id 'java'
    id 'war'
    id 'eclipse-wtp'
    id 'net.ltgt.apt-eclipse' version '0.18'
    id 'io.github.divinespear.jpa-schema-generate' version '0.3.5.1'
}

apply plugin: 'cz.habarta.typescript-generator'

repositories {
    jcenter()
}

dependencies {
   ...
}

generateTypeScript {
   ...
}
`

**Comment by vojtechhabarta** [comment]
Thanks @Jendoliver for understanding and for sharing the example.
Actually it wasn't waste of time. At least I know now that we will need to solve this problem in the future.
Thanks again.
