### ISSUE TITLE
Include class methods in type definitions.

### ISSUE THREAD

**Issue by Humberd** [vojtechhabarta/typescript-generator#278]
Does such functionality exist? Is there a way for typescript interfaces to include java class methods?

**Comment by vojtechhabarta** [comment]
Do you have some example how exactly your Java class looks like and what do you want to generate?

**Comment by Humberd** [comment]
This
```java
class Foo {
   String name = "John"
   void sayHello(String to) {
      System.out.println(name + to)
   }
}
```

to this
```typescript
interface Foo {
   name: String
   sayHello(to: String): void
}
```

**Comment by vojtechhabarta** [comment]
Actually, that is not possible.

It is possible to generate properties based on getter methods, for example from `String getName()` Java method generate `name: string` TypeScript property.

Or it is possible to generate client class for some REST API: https://github.com/vojtechhabarta/typescript-generator/wiki/JAX-RS-Application#2-jax-rs-application-client.

What do you want to achieve?

**Comment by Humberd** [comment]
My Java application would have a scripting engine, which would allow me to write scripts in JavaScript, to which I would pass Java objects and classes. JavaScript is not a typed language, so I am invoking java methods blindly (no IDE autocompletion). That is why I am trying to generate TypeScript type definitions of passed classes.

**Comment by vojtechhabarta** [comment]
Yes, this is reasonable use case but unfortunately it is not supported.
I personally don't have plans to work on this use case.
There was PR #138 for this kind of functionality but it was just experiment which was not finished.

**Comment by vojtechhabarta** [comment]
Closing inactive issues.
