### ISSUE TITLE
Automatic class discovery from a web application with services registered through automatic discovery

### ISSUE THREAD

**Issue by jlogar** [vojtechhabarta/typescript-generator#28]
Hello,
I noticed that you implemented automatic class discovery (#20). I was wondering if this mechanism can be used with applications that do not subclass javax.ws.rs.core.Application. In my case the application servlet is added through web.xml like this (kind of like defined in the JAX-RS spec 2.0, page 7):
```XML
    <servlet>
        <servlet-name>javax.ws.rs.core.Application</servlet-name>
    </servlet>
    <servlet-mapping>
        <servlet-name>javax.ws.rs.core.Application</servlet-name>
        <url-pattern>/api/*</url-pattern>
    </servlet-mapping>
```

So there is no actual class to set in `classesFromJaxrsApplication` option.

**Comment by vojtechhabarta** [comment]
Actually this is not supported. This mechanism relies on container-supplied class scanning facilities as mentioned in 2.3.2 chapter and typescript-generator doesn't run in servlet container which could provide list of discovered classes. To support this feature we would need to implement automatic discovery of all root resource classes ourselves using some classpath scanning library.
Do you need this feature or do you have some alternatives?

**Comment by jlogar** [comment]
It's more of a would be quite nice to have. Currently we just add all the DTOs to the classes collection. As it's not too many for now it's not very bothersome.

**Comment by vojtechhabarta** [comment]
I added `classesFromAutomaticJaxrsApplication` parameter which when set to `true` adds classes from discovered JAX-RS REST resources.
