### ISSUE TITLE
"Multiple classes are mapped to the same name" error occurring for the same class

### ISSUE THREAD

**Issue by antch** [vojtechhabarta/typescript-generator#283]
I'm trying to use typescript-generator to generate a .ts.d file for a set of ~300 classes via custom Ant task. In my case I want all subclasses of a specific class so I'm using ClassGraph to load all of the classes and then using `Input.from(Type...)`. I'm also using `mapPackagesToNamespaces` for now to get past some of the same-class-difference-packages naming conflicts.

Unfortunately I am still receiving the error:

    cz.habarta.typescript.generator.compiler.SymbolTable$NameConflictException: Multiple classes are mapped to the same name. You can use 'customTypeNaming' or 'customTypeNamingFunction' settings to resolve conflicts or exclude conflicting class if it was added accidentally.
        at cz.habarta.typescript.generator.compiler.SymbolTable.reportConflicts(SymbolTable.java:108)

I have debug logging on and can see all of the "Parsing..." messages (around 1900 of them), followed by the warning:

    [typescript-generator] Warning: Multiple classes are mapped to 'com.mypackage.ComponentProjection' name. Conflicting classes: [interface com.mypackage.ComponentProjection, interface com.mypackage.ComponentProjection]

Note that the packages are the same -- there is only one class defined with that name. Is there any way to effectively troubleshoot an issue like this? `com.mypackage.ComponentProjection` itself is not generic, though it is used as a type parameter in a few of the other applicable classes.

**Comment by vojtechhabarta** [comment]
Maybe your `ComponentProjection` class is loaded twice using different class loaders. Can you check how many times this class occurs in "Parsing..." messages? These messages also contain reason why the class is being parsed.

**Comment by antch** [comment]
Thanks for the reply. It is only mentioned once in the output:

    [typescript-generator] Parsing 'com.mypackage.ComponentProjection' used in 'SomeOtherClass.someProperty'

**Comment by vojtechhabarta** [comment]
Ok, I was expecting that it will be there twice. But it still could be a class loading issue. How exactly do you load your input classes? Are you using ClassGraph or some classloader for it? I am asking because ClassGraph has its own classloader which should not be combined with other classloaders. Typescript-generator uses ClassGraph just for getting list of class names but it loads the classes using classloader created in Maven or Gradle plugin.

Do you think there is "right" classloader available for you to load the classes? If yes, could you try to use it for loading the classes? You can also try to set it as "context" classloader: `Thread.currentThread().setContextClassLoader(classLoader)`. You can also check how Maven plugin is implemented: [GenerateMojo.java](https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-maven-plugin/src/main/java/cz/habarta/typescript/generator/maven/GenerateMojo.java).

**Comment by antch** [comment]
The classloader is retrieved using Ant's `ClasspathUtils` -- I was setting that classloader in ClassGraph and loading the classes that way, then setting that classloader on the `Settings` and passing in the loaded classes to `Input.from(Type...)`.

After your comment I tried the approach from the Maven plugin: Create `URL[]` from the target class names, then:

    URLClassLoader urlClassLoader = Settings.createClassLoader(getProject().getName(), urls, classLoaderFromAnt);
    settings.classLoader = urlClassLoader;
    Input input = Input.fromClassNamesAndJaxrsApplication(classNames,
        Collections.<String>emptyList(), Collections.<String>emptyList(),
        null, false, null, urlClassLoader, true)

Unfortunately I get the same error in both scenarios. The "Parsing ..." lines look the same as well.

**Comment by vojtechhabarta** [comment]
I really don't know.

Name conflicts are handled in [SymbolTable](https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/compiler/SymbolTable.java) class. You can check if there is something suspicious. There is `symbols` field which is `Map` which key is `Pair` of class and suffix. So this `Map`, I think, cannot contain same class twice (same class with two different suffixes produces different non-conflicting names). So I still don't know what could be the reason other than multiple classloaders.

If you are willing to build typescript-generator from sources you can also try to confirm or deny that this class is loaded by two classloaders. In this case change how list of confilicting classes is logged  on this line: https://github.com/vojtechhabarta/typescript-generator/blob/2aa0a89a19383d929cb19c94fe653d443a1baaa4/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/compiler/SymbolTable.java#L103 Put there for example `classes.stream().map(cls -> cls.getName() + " from " + cls.getClassLoader()).collect(Collectors.toList())`.

**Comment by vojtechhabarta** [comment]
You can also try to upgrade ClassGraph to latest version.

**Comment by antch** [comment]
So I hooked up a debugger and set a breakpoint at the line in `SymbolTable` and you are correct, the class is there with two different classloaders. One instance has the classloader that I explicitly set, and the other is some other classloader that Ant is creating somewhere along the line. Not sure how to fix it yet, but thanks for the help in tracking it down.
