### ISSUE TITLE
"generateInfoJson" does not export enum mappings in the generated JSON file

### ISSUE THREAD

**Issue by antch** [vojtechhabarta/typescript-generator#284]
When generating a "base" `.d.ts` file, I export the info JSON file to use in a subsequent run of the generator. However, the enums are not added to the info JSON file, and so they are re-defined when generating the new declarations file.

When I add the definition of the enum manually to the `typescript-generator-info.json` file, it does import correctly.

I am using the "asEnum" option for enum mapping, however the default option exhibited the same issue.

**Comment by vojtechhabarta** [comment]
Sorry for late response, I only received empty notification about this issue. I will look into it.

**Comment by vojtechhabarta** [comment]
I added enums and type aliases to `typescript-generator-info.json` file. I think this is sufficient for enums to work. I added test for it. Could you please try it if you had time (from master branch)?

**Comment by vojtechhabarta** [comment]
Released [v2.9.456](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.9.456).

**Comment by antch** [comment]
I ended up going with a single typings file but if I get a chance I'll check it out, thank you!
