### ISSUE TITLE
Is possible use custom param naming like customTypeNaming

### ISSUE THREAD

**Issue by krejciOndrej** [vojtechhabarta/typescript-generator#287]
Hello, 
is possible change param's name same as type by customTypeNaming? 
For example if you want remove "-" characters.

**Source**
![image](https://user-images.githubusercontent.com/44830947/48120020-2c775500-e271-11e8-9732-306808f7cb2b.png)

**Output**
![image](https://user-images.githubusercontent.com/44830947/48119991-19648500-e271-11e8-8320-9313abcd6016.png)

**Comment by krejciOndrej** [comment]
Thank you, replace character by uppercase letter is great solution.

I found another minor problem. The generator has inserted GET into the function name.

**Source**
![image](https://user-images.githubusercontent.com/44830947/48193937-f3f87980-e34b-11e8-8aba-f39c32c104bf.png)

**Output**
![image](https://user-images.githubusercontent.com/44830947/48193959-01156880-e34c-11e8-9aef-d461587ad8a2.png)

Thank you, your generator is great project.

**Comment by vojtechhabarta** [comment]
There are two ways how method names are generated. If there is no conflict then original Java method name is used. But when there is a conflict then HTTP method and path is used to construct unique name. There could be two methods with the same path which could only differ in HTTP method (GET and POST for example).

Do you have access to Java class and could you change method name there? In this case it will not be needed to generate new unique name and you will have nice names directly.

**Comment by vojtechhabarta** [comment]
Fix for invalid identifiers released in [v2.9.456](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.9.456).
For other problems/questions please open separate issue.
