### ISSUE TITLE
Output client only (assume definition file already output)

### ISSUE THREAD

**Issue by richturner** [vojtechhabarta/typescript-generator#288]
Great project! I am trying to generate two node packages for my java code:

1. a model package which only includes the definition file (generated using your awesome gradle plugin)
2. A REST API package which only includes the client (again generated using your awesome gradle plugin)

Outputting the first is easy  (don't use the generateJaxrsApplicationClient option) but for the second I cannot see any way of telling the generator to assume the type definitions exist and to only output the client class.

Is there some way of doing this that I'm missing?

**Comment by richturner** [comment]
I've achieved this for the time being by using a custom `TypeProcessor` but it is a big hack and would love to see this support out of the box.

**Comment by vojtechhabarta** [comment]
There is a feature which might help you: [dependent modules](https://github.com/vojtechhabarta/typescript-generator/pull/276) if you are generating modules. It is rather complex so don't hesitate to ask questions.

**Comment by richturner** [comment]
Thanks for the suggestion will take a look.
