### ISSUE TITLE
Missing 'export' keyword in latest version

### ISSUE THREAD

**Issue by lonnelars** [vojtechhabarta/typescript-generator#29]
We are using `typescript-generator` in our project to generate `d.ts` files for our front end code. We're using ES2015 modules on the front end, and when we updated `typescript-generator` to the latest version, our build broke because the `export` keywords are missing from the interfaces (updated from 1.1.85 to 1.4.52).

**Comment by vojtechhabarta** [comment]
Actually I don't know why this should be a problem. Could you please add more details like error message, tsconfig.json, TypeScript version, typescript-generator settings etc.?

**Comment by lonnelars** [comment]
The error message is `Error TS2306: File 'process.d.ts' is not a module.`. We can fix it by hand by replacing `interface` with `export interface` in the generated .d.ts file. In version 1.1.85 the generated .d.ts file had `export interface`. In version 1.4.152, the generated .d.ts file has just `interface`. Without the `export` keyword, the file is not recognized as an ES2015 module.

**Comment by vojtechhabarta** [comment]
In TypeScript it is possible to describe ES2015 module in two different ways.
Regular module example:
``` TypeScript
// -------- my-module-regular.d.ts --------
export interface MyObject {
}
// -------- usage.ts --------
import { MyObject } from "./my-module-regular"
var obj: MyObject;
```
Ambient module example:
``` TypeScript
// -------- whatever.d.ts --------
declare module "my-module-ambient" {
    interface MyObject {
    }
}
// -------- usage.ts --------
import { MyObject } from "my-module-ambient";
var obj: MyObject;
```

Ambient declarations are used for describing **existing** JavaScript code (or JSON format). So typescript-generator generates modules in ambient style. Maybe in the future it will support both ways but for now you can use ambient modules. To do this use `module` setting. (Set it for example to `my-module-ambient`.) Does this work for you?

**Comment by lonnelars** [comment]
Thank you for your time. I'll refactor and give it a try as soon as possible.

**Comment by vojtechhabarta** [comment]
I created table which shows different module/namespace combinations in TypeScript and support in typescript-generator
http://vojtechhabarta.github.io/typescript-generator/doc/ModulesAndNamespaces.html

**Comment by vojtechhabarta** [comment]
[Version 1.6.171](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.6.171) adds support for modules with top-level `export` declarations.

**Comment by lonnelars** [comment]
Perfect :+1:
