### ISSUE TITLE
typescript-generator and Script4J

### ISSUE THREAD

**Issue by PavelKastornyy** [vojtechhabarta/typescript-generator#292]
I started a new project [Script4J](https://github.com/PavelKastornyy/script4j) that will be a set of libraries to write programs and libraries in TypeScript/JavaScript using Java API. Although it is a very new project (I am just doing first collections) I think it can be interesting for users and developers of typescript-generator. Maybe we can cooperate somehow.

**Comment by PavelKastornyy** [comment]
Yes, I know about JSweet and tested it. JSweet is a transpiler and for serious things it works badly because JavaScript and Java are very different. Script4J is ready library that can be used as it is.

I will try typescript-generator and maybe I can suggest something interesting.

**Comment by vojtechhabarta** [comment]
I wish you good luck with your new project 🤞
