### ISSUE TITLE
Cannot set jackson2Configuration using gradle

### ISSUE THREAD

**Issue by rhandersen** [vojtechhabarta/typescript-generator#293]
I would like to configure the visibility options for jackson2 but I'm having a hard time figuring out how the jackson2configuration property should be used.

I tried adding this:
`jackson2Configuration = [fieldVisibility: 'ANY']`

But get this error:

> Could not set unknown property 'jackson2Configuration' for task ':admin:generateTypeScript' of type cz.habarta.typescript.generator.gradle.GenerateTask.

What am I doing wrong?

**Comment by rhandersen** [comment]
I actually see now that it is missing the generateTask properties. It is however stated in the documentation that options can be passed with this option.

**Comment by vojtechhabarta** [comment]
Which typescript-generator version are you using? (It is printed when `generateTypeScript` task is executed.)

**Comment by rhandersen** [comment]
Generated using typescript-generator version 2.5.423

**Comment by vojtechhabarta** [comment]
Great it works for you now.
`jackson2Configuration` parameter was added in [v2.7.447](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.7.447).
