### ISSUE TITLE
Question: Partials.

### ISSUE THREAD

**Issue by YozhEzhi** [vojtechhabarta/typescript-generator#294]
Could I get generated interface like below?
```
export interface PageableRequest<F> {
    filter: Partial<F>;
    ...
}
```

**Comment by vojtechhabarta** [comment]
If you had following interfaces in Java
``` java
interface PageableRequest<F> {
    Partial<F> getFilter();
}
interface Partial<F> {
}
```
then generated TypeScript declarations would be
``` typescript
interface PageableRequest<F> {
    filter: Partial<F>;
}
interface Partial<F> {
}
```

But what exactly is `Partial` in your Java code?

**Comment by YozhEzhi** [comment]
I'm not backend developer. But here's Java code:
```
@ApiModel(description = "PageableRequest model")
public class PageableRequest<F> {
    ...
    @ApiModelProperty("Filter for entity request")
    @Nullable
    private F filter;
    ...
}
```

This code generates following `ts`:
```
/**
 * PageableRequest model
 */
export interface PageableRequest<F> {
    filter?: F;
    ...
}
```

So `filter` should have **all** the properties that exists in `F`.
But I want to use **some** of properties in `F`. That means that `F` should be `Partial<F>` in generated `ts`.

And this is my question. :)

**Comment by vojtechhabarta** [comment]
Unfortunately transforming `F` into `Partial<F>` is not currently possible.

I think closest solution would be to generate all properties in all `F` classes optional. This could be done in several ways depending on `optionalProperties` parameter.

**Comment by YozhEzhi** [comment]
To bad. Thanks fo response!
