### ISSUE TITLE
Classes from `java-library` subprojects not included on classpath

### ISSUE THREAD

**Issue by milosonator** [vojtechhabarta/typescript-generator#295]
I have a multi project Gradle setup, with a `webapp` project that has a `generateTypeScript` configuration and a `common` project that holds some classes that are referenced inside my data classes that I'm generating TypeScript for. The dependency is declared as followed in the webapp project:
```groovy
dependencies {
  compile project(':common')
}
```
and the common project itself changed from `java` plugin build to the `java-library` plugin.
Now its classes are no longer found when generating typescript:
```
java.lang.ClassNotFoundException: my.common.package:MyClass
```
I'm looking at the way the plugin loads classes, and it seems to refer to tasks and configurations with the name `compile`. With the `java-library` plugin, I have a feeling this might no longer be the case, and these classes are somehow no longer included. It does not seem (easily) possible to extend what classes need to be loaded in the task configuration.

If I change my `common` project to the `java` plugin instead of `java-library` the error goes away.

With the `java-library` becoming more standard in Gradle projects this should probably be supported out-of-the box, but also another way to manually add these dependencies to the configuration would be helpful. In addition, any currently available way to make this work with `java-library` dependencies would be welcome.

**Comment by vojtechhabarta** [comment]
Could any Gradle expert help with this issue?
How can this be solved in `build.gradle` file with current typescript-generator version?
What can we improve in typescript-generator to make this use case easier?

**Comment by mduft** [comment]
I have exactly the same issue. Might be related with
https://github.com/vojtechhabarta/typescript-generator/blob/0ba72ba2c68d788ec6b996db1f230c9e21cdbe9c/typescript-generator-gradle-plugin/src/main/java/cz/habarta/typescript/generator/gradle/GenerateTask.java#L108 
The configuration "compile" is deprecated, and "implementation" should be used AFAIK.

I had to:
- remove 'java-library' plugin from all projects
- switch back to using 'compile' dependencies instead of 'implementation' and 'api'.

**Comment by mduft** [comment]
I managed to get this to work by ignoring the gradle plugin and doing things manually in groovy. This looks something like this:

```
task genDtos() {
    dependsOn 'compileJava'
    doLast {
        def cfg = new cz.habarta.typescript.generator.Jackson2Configuration();
        cfg.fieldVisibility = com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility.ANY;
        cfg.getterVisibility = com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility.NONE;
        cfg.setterVisibility = com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility.NONE;

        def settings = new cz.habarta.typescript.generator.Settings();
        def classes = [
            'my.ClassName',
        ]
        settings.customTypeMappings.put('java.net.URI', 'string');
        settings.customTypeNaming.put('my.ClassName', 'ProperName');
        def excludeClasses = [
            'java.lang.Comparable',
            'java.io.Serializable',
        ]
        settings.setExcludeFilter(excludeClasses, null);
        settings.outputFileType = 'implementationFile'
        settings.outputKind = 'module'
        settings.mapEnum = 'asEnum'
        settings.nonConstEnums = true
        settings.jsonLibrary = 'jackson2'

        def outputFile = "${webappDir}/src/app/models/gen.dtos.ts"

        // add the compile classpath to see the classes dirs of other projects as JAR files are not yet built.
        def uris = configurations.compileClasspath.files.asType(List).collect { it.toURI().toURL() };
        // and add the runtime classpath as well to get our OWN classes.
        uris.addAll(sourceSets.main.runtimeClasspath.collect { it.toURI().toURL() });
        uris.unique();
        def cl = settings.createClassLoader("dummy", uris as URL[], Thread.currentThread().getContextClassLoader());

        settings.classLoader = cl;
        settings.setJackson2Configuration(cl, cfg);

        new cz.habarta.typescript.generator.TypeScriptGenerator(settings).generateTypeScript(
            cz.habarta.typescript.generator.Input.fromClassNamesAndJaxrsApplication(classes, [], [], [], null, false, settings.getExcludeFilter(), cl, false),
            cz.habarta.typescript.generator.Output.to(file(outputFile)));
    }
}
```

The most notable difference to the gradle plugin is the handling of the classpath...

**Comment by mduft** [comment]
TBD: inputs and outputs so the generator is not run /always/

**Comment by vojtechhabarta** [comment]
In [2.14.505](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.14.505) release I added support for dependencies from `compileClasspath` configuration which should solve this issue.

@milosonator you probably somehow solved the issue already but anyway any feedback would be welcomed.

And @mduft: thanks again for alternative which might be useful for users too.

**Comment by milosonator** [comment]
@vojtechhabarta 
That's great to hear, I wasn't able to find a solution for the issue, so reverted my 'java-library' projects back to plain 'java' to work around the problem. We will upgrade soon to get rid of this workaround.

**Comment by mduft** [comment]
Our generator was set to 2.+ and suddenly stopped working today as it picked up the new plugin version it seems :| I did not have time to investigate yet though... For now, we restricted plugin version to 2.13.+

**Comment by vojtechhabarta** [comment]
@mduft sorry for that. Could you please share more info once you have time?

**Comment by mduft** [comment]
No worries, we're just staying on 2.13.+ for now :) The problem is:

> No signature of method: static cz.habarta.typescript.generator.Input.fromClassNamesAndJaxrsApplication() is applicable for argument types: (ArrayList, ArrayList, ArrayList, ArrayList, null, Boolean, cz.habarta.typescript.generator.Settings$1...) values: [[io.bdeploy.interfaces.descriptor.application.ApplicationDescriptor, ...], ...]

This is due to us working around the issues we had by directly reaching into the internal APIs of your plugin ;) sorry xD

You can look at our `genDtos` task here: https://github.com/bdeployteam/bdeploy/blob/master/ui/build.gradle

Thanks for the good work :)

**Comment by vojtechhabarta** [comment]
I always try to maintain compatibility as much as reasonable for build plugins (Maven, Gradle). For direct invocation I was thinking that some incompatibility can be easily detected and fixed in IDE but that's not the case for `build.gradle`.

Having `Input.fromClassNamesAndJaxrsApplication()` method with ever growing list of parameters probably wasn't a good idea. In 2.14 release there was added `classesExtendingClasses` parameter so you just need to pass `[]` once more (or `null`).

**Comment by milosonator** [comment]
resolved issue for me.
