### ISSUE TITLE
How can I generate .ts file with JSDoc comments?

### ISSUE THREAD

**Issue by yutou527** [vojtechhabarta/typescript-generator#307]
sorry about my poor English .
i want to generate .d.ts file with the annotations that i wrote in java files. could i do that?

**Comment by vojtechhabarta** [comment]
Hi @yutou527, generating TypeScript decorators from Java annotations is not currently supported and I don't have plans to add it in near future. For more info see my comment here: https://github.com/vojtechhabarta/typescript-generator/issues/164#issuecomment-446491604.

BTW thanks for your interest in typescript-generator.

**Comment by yutou527** [comment]
@vojtechhabarta  ok , got it , thank you very much !

**Comment by yutou527** [comment]
/**
\* like this
*/
i just want to support the static annotations, 
but , anyway , this is a awsome project 👍

**Comment by yutou527** [comment]
@vojtechhabarta  yes! just JavaDoc comments ,i'm sorry that didn't explain clearly.
Java code:
```java
/**
* my point
*/
private Long point;
```
.d.ts:
```ts
/**
* my point
*/
point: number;
```

**Comment by yutou527** [comment]
@vojtechhabarta   
found it !
https://github.com/vojtechhabarta/typescript-generator/wiki/Javadoc
thanks!

**Comment by yutou527** [comment]
last question i think, 😂
the comments of Java Classes is working ,
but the member variables is not，
java:
```Java
/**
 * some comments
 * 
 * @author 123
 * 
 */
public class OrgData extends RootDataBase implements Replacable
{
	/**
	 * member variable comments
	 */
	private OrgMetaData org;
}

```
ts:
```typescript
/**
* some comments
* @author 123
*/
interface OrgData extends RootDataBase, Replacable {
        org: OrgMetaData;
}
```
pom.xml
```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-javadoc-plugin</artifactId>
		<version>2.10.3</version>
		<executions>
			<execution>
				<id>xml-doclet</id>
				<phase>process-classes</phase>
				<goals>
					<goal>javadoc</goal>
				</goals>
				<configuration>
					<show>private</show>
					<!-- -Xdoclint:none -->
					<additionalparam>-d ${project.build.directory}</additionalparam>
					<doclet>com.github.markusbernhardt.xmldoclet.XmlDoclet</doclet>
					<useStandardDocletOptions>false</useStandardDocletOptions>
					<docletArtifact>
						<groupId>com.github.markusbernhardt</groupId>
					<artifactId>xml-doclet</artifactId>
					<version>1.0.5</version>
				</docletArtifact>
							
			</configuration>
		</execution>
	</executions>
</plugin>
```
and i checked the javadoc.xml ,the comments are exported. 
javadoc.xml
```xml
<field name="org" qualified="cn.h5game.legend2.org.data.OrgData.org" scope="private" volatile="false" transient="false" static="false" final="false">
      <type qualified="cn.h5game.legend2.org.data.OrgMetaData"/>
      <comment>member variable comments</comment>
</field>
```
sorry for bothering you

**Comment by vojtechhabarta** [comment]
Is there an getter for `OrgData.org`? I would guess that this property is based on getter so comment is also taken from Javadoc on getter.

**Comment by yutou527** [comment]
yes , there is a getter for OrgData.org without comments.....

**Comment by yutou527** [comment]
and then , i'll try to generate comments for all getters automatically. 😀
or, deal with the javadoc.xml, copy all the properties's comments  to their getters .😀
