### ISSUE TITLE
Passing enums directly to the generator doesn't work

### ISSUE THREAD

**Issue by ryan10132** [vojtechhabarta/typescript-generator#31]
If I pass an enum directly to the generator, it doesn't generate. Seems like it only generates enums that are referenced by classes that are passed to the generator. It'd be nice to have this use case supported, thanks!

**Comment by ryan10132** [comment]
I'll push up a test to illustrate this in a bit

**Comment by ryan10132** [comment]
Actually it seems like this is fixed in master but not on the latest release? Can we just get another release, then?

**Comment by vojtechhabarta** [comment]
@ryan10132 thanks for reporting this.
Yes, it should work now.
I plan release this week.

**Comment by vojtechhabarta** [comment]
Version 1.6.171 [release notes](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.6.171).

**Comment by ryan10132** [comment]
thanks!
