### ISSUE TITLE
Feature suggestion: null | undefined as OptionalPropertiesDeclaration

### ISSUE THREAD

**Issue by rhandersen** [vojtechhabarta/typescript-generator#310]
I would like to be able to generate an interface with properties that are not optional to implement, but can have both the values null and undefined, along with the type, i.e.:

`name: string | null | undefined;`

What do you think of this idea?

**Comment by vojtechhabarta** [comment]
I think current options cover JSON contracts well.
I guess you want to ensure that the client goes through all properties and doesn't forget about some optional property. But it this case you will not be able to add new property in a compatible manner.

Anyway I can add this option once I finish other work.

**Comment by rhandersen** [comment]
It would be of great value to have more options at least :-) 

I opened this PR with the suggestion:
https://github.com/vojtechhabarta/typescript-generator/pull/311

**Comment by rhandersen** [comment]
@vojtechhabarta When do you plan to make the next release?

**Comment by vojtechhabarta** [comment]
@rhandersen I plan to make the release in the beginning of April. There are bigger changes in `master` branch now so I want to have some time for stabilization before release.

**Comment by vojtechhabarta** [comment]
I released [v2.13.489](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.13.489) with this feature.
