### ISSUE TITLE
Basic support for Type Script decorator

### ISSUE THREAD

**Issue by jjoslet** [vojtechhabarta/typescript-generator#312]
Can you consider adding a feature that allows a custom `Extension` to write lines between the comments and the declaration of a `TsBeanModel`.

The idea is to allow a custom extension to add a decorator to the Type Script model. This can be used to implement the feature described in https://github.com/vojtechhabarta/typescript-generator/issues/164 for example.

Thank you.

**Comment by vojtechhabarta** [comment]
I will consider adding model (and implement emitting) and allow extensions to add these objects (instead of text).

**Comment by lpandzic** [comment]
Any update on this?
My case is to map bean validation annotations to [class validator](https://www.google.com/search?client=firefox-b-d&q=%22bean+validation%22+%22class+validator%22) decorators.

**Comment by vojtechhabarta** [comment]
It is lower priority but I still plan to implement it.

**Comment by gokgozf** [comment]
Deserialization fails when I use json2typescript package with generated classes.
I was trying to find a way to add custom decorators to plugin to generate
something like following as it was mentioned at the packages page https://www.npmjs.com/package/json2typescript 

 
```
import {JsonObject, JsonProperty} from "json2typescript";
@JsonObject("City")
export class City {
 
    // This property has no @JsonProperty. 
    // It will not be mapped.
    id: number = 123;
 
    // This maps the value of the JSON key "name" to the class property "name".
    // If the JSON value is not of type string (or missing), there will be an exception.
    @JsonProperty("name", String)
    name: string = `undefined;......`
```

how should approach this problem?

**Comment by vojtechhabarta** [comment]
I added decorators to model classes and implemented emit so now it should be possible to create an extension which would decorate classes and properties. There is also test with example extension: [DecoratorsTest](https://github.com/vojtechhabarta/typescript-generator/blob/418125c1d9e161e8e62c2d4159b1a2137f5f6211/typescript-generator-core/src/test/java/cz/habarta/typescript/generator/DecoratorsTest.java).

Decorators are still experimental feature in TypeScript and standard [proposal](https://github.com/tc39/proposal-decorators) is relatively different (and doesn't progress much) so I don't want to invest much into it right now. But let me know if you miss something important.

**Comment by vojtechhabarta** [comment]
This was [released](https://github.com/vojtechhabarta/typescript-generator/releases) in 2.19.
