### ISSUE TITLE
Unable to load class 

### ISSUE THREAD

**Issue by baao** [vojtechhabarta/typescript-generator#313]
I'm having a problem with the plugin, tried all versions from 2.7. to latest. Here's the gradle buildscript

    generateTypeScript {
        jsonLibrary = 'jackson2'
        classPatterns = [
            'com.foo.**'
        ]
        excludeClasses = [
            'org.springframework.data.mongodb.repository.ReactiveMongoRepository'
        ]
        excludeClassPatterns = [
            'java.io.Serializable',
            'com.foo.**Repository',
            'com.foo.**Builder',
            'org.springframework.data.mongodb.repository.**',
            'java.lang.Compareable',
            'org.bson.types.ObjectId'
        ]
        outputFile = 'build/customers.d.ts'
        outputKind = 'global'
        namespace = 'Customers'
        optionalProperties = 'all'
        customTypeMappings = [
            'java.time.LocalDateTime:string',
            'org.bson.types.ObjectId:string'
        ]
    }

The error is 

`Unable to load class 'org.springframework.data.mongodb.repository.ReactiveMongoRepository'.`

The class that could not be found is on the classpath, compiling the project works fine. Omitting the class either in excludeClasses or excludeClassPatterns doesn't make a difference. 

None of the classes that should be converted (rules from classPatterns + excludedClasses(Patterns)) implement ReactiveMongoRepository. 

What am I doing wrong and how to solve this?

**Comment by vojtechhabarta** [comment]
I am not sure where this error message comes from. Probably it is not directly from typescript-generator. Is there a stacktrace?

Probably some of your classes require `ReactiveMongoRepository` class. In this case the problem is that somehow dependency with `ReactiveMongoRepository` class is missing. Could you try to add it?

**Comment by vojtechhabarta** [comment]
Hopefully it works for you now.
