### ISSUE TITLE
Custom headers

### ISSUE THREAD

**Issue by krejciOndrej** [vojtechhabarta/typescript-generator#314]
Hello, 
can i use some custom property (to add headers) in httpClient request? For example if I want use ajax call in request promise and add ifModified flag to headers.

![image](https://user-images.githubusercontent.com/44830947/53939704-2628a680-40b4-11e9-99e1-a6a55104d7c3.png)

Now i have to create new httpClient for every method in class which have different ajax call params.
Can I use a different better way of doing this? for example generate optional custom param to every request?

Thank you

**Comment by vojtechhabarta** [comment]
Yes, you can use `restOptionsType` and generate additional `options` parameter of specified type to all methods. Value of this parameter is then passed to `HttpClient.request` function.
See [restOptionsType](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#restOptionsType).

**Comment by krejciOndrej** [comment]
Oh sorry i didn't notice this option. 
Thank you for answer.

**Comment by vojtechhabarta** [comment]
No problem, thanks for asking, might be useful for others too.
