### ISSUE TITLE
Proposal: Add customTypeNamings similar to customTypeMappings

### ISSUE THREAD

**Issue by ChristianIvicevic** [vojtechhabarta/typescript-generator#317]
In our project we use multiple custom mappings and namings such as

```xml
<customTypeMappings>
    <customTypeMapping>java.time.LocalDate:LocalDate</customTypeMapping>
    <customTypeMapping>java.time.LocalTime:LocalTime</customTypeMapping>
</customTypeMappings>
```

However we are using exported Swagger classes and have some name collisions and need to use multiple customTypeNaming directives. Unfornatunately there is no intuitive way to create multiple custom type namings besides writing a comma separated list as follows:

```xml
<customTypeNaming>com.foo.resorts.api.model.ResortClimate$TypeEnum:ResortClimateTypeEnum,com.foo.resorts.api.model.ActivityOfferListItem$TypeEnum:ActivityOfferListItemTypeEnum</customTypeNaming>
```

I'd like to propose a customTypeNamings element to denote a list of customTypeNaming objects akin to the first example.

**Comment by vojtechhabarta** [comment]
This is already possible, for example:

``` xml
<customTypeNaming>
    <naming>com.foo.resorts.api.model.ResortClimate$TypeEnum:ResortClimateTypeEnum</naming>
    <naming>com.foo.resorts.api.model.ActivityOfferListItem$TypeEnum:ActivityOfferListItemTypeEnum</naming>
</customTypeNaming>
```
The name of nested element (in this example `<naming>`) is not significant, you can use whatever you like.

It might be confusing since `customTypeNaming` parameter name is not in plural but I don't think it is worth changing.

**Comment by vojtechhabarta** [comment]
Hopefully it works for you now.
