### ISSUE TITLE
Improve `BeanParam` handling

### ISSUE THREAD

**Issue by vojtechhabarta** [vojtechhabarta/typescript-generator#318]
According to this comment https://github.com/vojtechhabarta/typescript-generator/pull/291#issuecomment-470505100 current solution is not ideal in all cases. Let's investigate it and come up with better solution.

**Comment by vojtechhabarta** [comment]
I committed support for `@QueryParam`s specified using parameter annotated with `@BeanParam`.
Let's say we have following method:
``` java
@GET
public List<String> getItems(
        @BeanParam SearchParams1 params1,
        @BeanParam SearchParams2 params2,
        @QueryParam("message") String message
) {
    return Collections.emptyList();
}
```
and following param classes:
``` java
public class SearchParams1 {
    @QueryParam("id")
    private Integer id;

    @QueryParam("name")
    private String name;
}

public class SearchParams2 {
    private String description;
    @QueryParam("description")
    public void setDescription(String description) {
        this.description = description;
    }
}
```
Following TypeScript code will be generated:
``` typescript
getItems(queryParams?: SearchParams1QueryParams & SearchParams2QueryParams & { message?: string; }): RestResponse<string[]>;

interface SearchParams1QueryParams {
    id?: number;
    name?: string;
}
interface SearchParams2QueryParams {
    description?: string;
}
```

In this example `queryParams` parameter's type is intersection of all param interfaces and params specified directly.

Note that there is a `QueryParams` suffix added to param interfaces because these java classes can also contain other fields than `@QueryParam` but it this case we are only interested in `@QueryParam`s.

@krezovic is it good solution for you?

**Comment by elkrejzi** [comment]
Looks good. As soon as you publish a release with these changes I can test it on our code base and report back.

**Comment by krezovic** [comment]
Looks good. As soon as you publish a release with these changes I can test it on our code base and report back.

**Comment by vojtechhabarta** [comment]
Released in [2.14.505](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.14.505), @krezovic could you please try it?

**Comment by krezovic** [comment]
@vojtechhabarta this solution works, but I'm not happy that it renames the backend class on the client. I now have FooSearchParamsQueryParams generated from FooSearchParams.class.

**Comment by vojtechhabarta** [comment]
Yes, that's not nice. But the same Java class can be used for multiple purposes and we need to somehow distinquish it. The class can containt query params, path params and other params and it can even be used as a JSON data class and processes by Jackson.

So in case of query params we just need to pick fields and setters annotated with `@QueryParam`. In case of path params we would need to pick members annotated with `@PathParam` and generate interface with different name. And if the same class would also be used as a JSON class it would have original name.

Maybe what you could do is to write type alias if you are sure you will not have name conflict:
```
type SearchParams1 = SearchParams1QueryParams;
```

**Comment by krezovic** [comment]
That still requires me to update the whole code base manually to change import location for aliases, sadly (30+ files).

Wonder how difficult would be to use original name if there's only one annotation used (all @QueryParam, all @PathParam, etc ...).

**Comment by vojtechhabarta** [comment]
Using original name if there's only one annotation can cause problems because somebody can later add another annotation and thus break the code which would be very surprising.

Maybe you can use `customTypeAliases` parameter (which I added in [2.15](https://github.com/vojtechhabarta/typescript-generator/releases)) and add for example type alias `SearchParams1` for `SearchParams1QueryParams`. In this case the type alias will be in generated file instead of regular source file.

Maven example:
``` xml
<configuration>
    <customTypeAliases>
        <alias>SearchParams1:SearchParams1QueryParams</alias>
    </customTypeAliases>
</configuration>
```
