### ISSUE TITLE
Support for Jackson JsonClassDescription and JsonPropertyDescription

### ISSUE THREAD

**Issue by jjoslet** [vojtechhabarta/typescript-generator#319]
Retrieve comments from Jackson annotation `JsonClassDescription` and `JsonPropertyDescription`

**Comment by jjoslet** [comment]
Here is an extension that do the job for the moment: [JacksonDescriptionExtension](https://github.com/vojtechhabarta/typescript-generator/files/2977671/JacksonDescriptionExtension.txt)

**Comment by vojtechhabarta** [comment]
I committed support for these annotations used on classes and their properties and also used on enums and their constants.

**Comment by vojtechhabarta** [comment]
I released [v2.13.489](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.13.489) with this feature.
