### ISSUE TITLE
GSON annotation SerializedName is ignored

### ISSUE THREAD

**Issue by glfp** [vojtechhabarta/typescript-generator#321]
It seems that GSON support is not already well supported.

A similar annotation 

```
@SerializedName("ID")
  private String ID = null;
```

is ignored and generated interface is 

```
export interface Task {
    id: string;
}
```

Any suggestion ? 
Thanks.

**Comment by vojtechhabarta** [comment]
Unfortunately GSON is not supported, see #222. Currently only Jackson 2, Jackson 1 and JAXB libraries are supported.

Till now nobody has been willing to implement it, so maybe sometime I will try it.

**Comment by glfp** [comment]
The GSON @SerializedName is identical to Jackson @JsonProperty.

I just converted all the classes (all the Docker API model !!) in typescript using the library. So I suppose that GSON structure is quite equal to Jackson2, the only difference is related to the property annotation. 

Can you suggest me where to modify the @JsonProperty annotation in your sources in order to create by myself  a local build with SerializedName annotation support ? Just because all works but not the annotation.

Thanks.

**Comment by vojtechhabarta** [comment]
Typescript-generator uses Jackson library to get list of properties of some bean. So `@JsonProperty` is not processed directly by typescript-generator but instead it is read by Jackson library. Jackson library is called in `Jackson2Parser` class to get list of `BeanPropertyWriter`s.

For GSON, I think, we would need some `GsonParser` class that would call GSON to get list of properties (with their JSON names) or it could get this list using reflections.

**Comment by glfp** [comment]
ok, I just workaround the impasse creating a temporary folder with all the Docker API class and renaming all the @SerializedName with @JsonProperty (and relative import) and then revert all just after the typescript generation.

Thank you for your support.
