### ISSUE TITLE
Better entity parameter names for "generateJaxrsApplicationClient"

### ISSUE THREAD

**Issue by stenzengel** [vojtechhabarta/typescript-generator#322]
Thank you very much for your helpful project. We have been using it for more than a year with great success for generating TypeScript interfaces. We have just started to use it for generating client classes (for Angular's "HttpClient" with our own subclass of "Extension") as well.

This also works well so far, but for entity parameters we only get non-speaking names at the moment (e.g. "arg2", "arg3"). Is there a way to get the "right" Java parameter names for this? If this is not possible, is there a workaround, e.g. annotate these entity parameters with a "name" annotation?

Simplified example:
Java-Source:
```java
@POST
@Path("/")
public ResultValue myMethod(@PathParam("myPathParam") final String myPathParam, @QueryParam("myQueryParam") final String myQueryParam, final String myEntityParam)
```

Currently generated TypeScript-Code:
```typescript
myMethod(myPathParam: string, arg3: string, queryParams?: { myQueryParam: string; }): RestResponse<ResultValue> {
```

Desired TypeScript-Code (e.g. "arg3" is replaced by "myEntityParam"):
```typescript
myMethod(myPathParam: string, myEntityParam: string, queryParams?: { myQueryParam: string; }): RestResponse<ResultValue> {
```

Best regards
Winfried

**Comment by vojtechhabarta** [comment]
Yes, it is possible to have original parameter names.

However the problem with parameter names is that by default Java compiler (`javac`) doesn't put these names into generated class files. You have to enable it by passing `-parameters` switch to `javac`.

Typescript-generator then reads parameter names using `java.lang.reflect.Parameter.getName()` which returns original name (if available) or `argN`.

**Comment by stenzengel** [comment]
Thank you very much. Works like a charm.
