### ISSUE TITLE
eslint support

### ISSUE THREAD

**Issue by slavikdenis** [vojtechhabarta/typescript-generator#325]
Hi! Wondering if there would be a possible way to add custom option instead of `noTslintDisable` as we are using https://github.com/typescript-eslint/typescript-eslint instead of TSLint so we need

`/* eslint-disable */`

instead of given

`/* tslint:disable */`

Thanks

**Comment by vojtechhabarta** [comment]
I believe generated files should not be checked by linters so I added `/* eslint-disable */` to generated files.

On the other hand I know that some people still want to check these files so I also added `noEslintDisable` option.

**Comment by slavikdenis** [comment]
Sounds great, thanks :)

**Comment by vojtechhabarta** [comment]
Released in [2.14.505](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.14.505).
