### ISSUE TITLE
Support "classesExtending" for candidate superclasses

### ISSUE THREAD

**Issue by antch** [vojtechhabarta/typescript-generator#328]
Similar to the recent addition of `classesImplementingInterfaces`, it'd be useful to have a `classesExtending` configuration option, where we can include all classes that extend from some list of superclasses.

This is easy to implement, but since I am currently reviewing my options for contributing with my employer, I'm not sure when it would be able to be submitted.

**Comment by vojtechhabarta** [comment]
Yes, this could be useful for some people so feel free to submit pull request if you can.
For consistency I would name this parameter `classesExtendingClasses`.

**Comment by antch** [comment]
I submitted a PR but it did not get linked to the issue.

**Comment by vojtechhabarta** [comment]
No problem, I just edited description. Thanks.

**Comment by antch** [comment]
Would you consider doing a release that includes the fixes for this and #327 ?

**Comment by vojtechhabarta** [comment]
I will make release next week.

**Comment by vojtechhabarta** [comment]
Released [2.14.505](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.14.505).
