### ISSUE TITLE
Failure to find cz.habarta.typescript-generator:typescript-generator-maven-plugin

### ISSUE THREAD

**Issue by pedy711** [vojtechhabarta/typescript-generator#333]
I tried to use the plugin, but got two errors which the first one I found the solution on your repo with setting phase to package, but the following still persists:

> Failure to find cz.habarta.typescript-generator:typescript-generator-maven-plugin:jar:2.13.496 in https://repo.maven.apache.org/maven2 was cached in the 
 local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

`<plugin>
				<groupId>cz.habarta.typescript-generator</groupId>
				<artifactId>typescript-generator-maven-plugin</artifactId>
				<version>2.13.496</version>
				<executions>
					<execution>
						<id>generate</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<phase>package</phase>
					</execution>
				</executions>
				<configuration>
					<jsonLibrary>jackson2</jsonLibrary>
					<classes>
						<class>com.jdisc.webui.server.App</class>
					</classes>
					<outputKind>module</outputKind>
				</configuration>
			</plugin>`

**Comment by vojtechhabarta** [comment]
Latest release is currently 2.13.489 - see https://github.com/vojtechhabarta/typescript-generator/releases/latest (not all tags are released to Maven central repository).
You can also check directly in Maven central repository: https://repo1.maven.org/maven2/cz/habarta/typescript-generator/typescript-generator-core
