### ISSUE TITLE
Only supports 'compile' dependencies

### ISSUE THREAD

**Issue by rinami** [vojtechhabarta/typescript-generator#334]
As per comment [https://github.com/vojtechhabarta/typescript-generator/issues/295#issuecomment-464775642](https://github.com/vojtechhabarta/typescript-generator/issues/295#issuecomment-464775642) the 'compile' dependency directive has been deprecated and support for 'api' and 'implementation' should be added. https://github.com/vojtechhabarta/typescript-generator/blob/0ba72ba2c68d788ec6b996db1f230c9e21cdbe9c/typescript-generator-gradle-plugin/src/main/java/cz/habarta/typescript/generator/gradle/GenerateTask.java#L108

**Comment by vojtechhabarta** [comment]
I guess we need to retain `"compile"` for compatibility and in addition also use `"api"` or `"implementation"`. But which one? Or both?
Any comments also from other Gradle users?

**Comment by rinami** [comment]
"api" is basically a direct replacement of "compile". "implementation" is basically designed so that you can limit the impact that nested dependencies have on large projects. For the purposes of this plugin you would want to support both. Technically, for "api" imports, you should also include the dependencies of the child but that may be pushing it.
I'd also suggest that the gradle library dependency be updated at the same time. Gradle 5.x has changed significantly since 2.1.

**Comment by vojtechhabarta** [comment]
I think we cannot update gradle dependency because it would break builds not using version 5.

Is `"api"` superset of `"implementation"`? If yes, we could use union of `"compile"` and `"api"`.

**Comment by vojtechhabarta** [comment]
I tried to use `api` and `implementation` configurations but I realized that we actually need to use `compileClasspath` configuration (which should provide dependencies from mentioned configurations).

So in [2.14.505](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.14.505) release I added support for dependencies from `compileClasspath` configuration, could you please try it?

**Comment by bschlosser** [comment]
Your change to use `compileClasspath` works for me. I can now specify my dependencies as `implementation`. For good measure I temporarily made them `api` and that worked as well.

**Comment by vojtechhabarta** [comment]
@bschlosser thanks for the feedback.
