### ISSUE TITLE
using typescript-generator with kotlin multiplatform projects

### ISSUE THREAD

**Issue by beyondeye** [vojtechhabarta/typescript-generator#340]
Hi,
thanks for this very useful library.
I have used it in regular kotlin gradle projects without issues. 

Lately I tried to use it  in a kotlin multiplatform project and when running the generateTypeScript task I got the error:
```
Execution failed for task ':generateTypeScript'.
> Configuration with name 'compile' not found.
```
I checked the list of configurations defined by the jetbrains gradle plugin for kotlin-multiplatform
with the following gradle task
```
task printConfigs {
    configurations.each { println it.name }
}
```

And I found out that the name of the equivalent configuration is apparently jvmCompile

If you want a test kotlin multiplatform project to look at, you can try this
[atomicfu](https://github.com/Kotlin/kotlinx.atomicfu)
Any ideas about some gradle hack that I can use to make your plugin works?

**Comment by beyondeye** [comment]
I have tried copying the compiled class files the subdirectory of the the ```build``` directory where thery are usually found in a normal kotlin gradle project with this gradle task
```
task copyToCompileKotlin(type: Copy,dependsOn: [compileKotlinJvm]) {
    from(compileKotlinJvm.destinationDir)
    into file("$buildDir/kotlin/compileKotlin")
}
```
but obviously this is not enough since without the compile configuration your plugin will failed even before getting to the class files

**Comment by vojtechhabarta** [comment]
In [2.14.505](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.14.505) release I added support for dependencies from `compileClasspath` configuration which might be helpful for you but otherwise I don't know how this issue should be solved.

**Comment by beyondeye** [comment]
thanks I will take a look
