### ISSUE TITLE
Does not manage RegExp like {id: [0-9]{1,99}}

### ISSUE THREAD

**Issue by iriikoad** [vojtechhabarta/typescript-generator#344]
Hi,
I have re resource with a Path containing a RegExp:

    @GET
    @Path({id: [0-9]{1,99}})
    @Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
    public T getWithId(@PathParam("id") long id) {
...
     }

the generation is:

        getWithId(): RestResponse<T> {
            return this.httpClient.request({ method: "GET", url: uriEncoding`objects/{id: [0-9]{1,99}}` });
        }

instead of

        getWithId(id : number): RestResponse<T> {
            return this.httpClient.request({ method: "GET", url: uriEncoding`objects/${id}');
        }

Is there a way to fix it?
Thanks!

**Comment by vojtechhabarta** [comment]
I committed fix for this particular case - `{}` characters used as quantifier. This commit still doesn't handle `{}` characters used elsewhere in regexp for which we would first need to find end of regexp by counting `{` and `}` characters.

@iriikoad workaround for your case is `{id: [0-9]+}` (till new release).

**Comment by vojtechhabarta** [comment]
Released in [2.15](https://github.com/vojtechhabarta/typescript-generator/releases).
