### ISSUE TITLE
How to add a questionmark to the generated typescript interface properties?

### ISSUE THREAD

**Issue by pl1307** [vojtechhabarta/typescript-generator#347]
Hello,

I'm trying to generate typescript inferfaces with optional properties. Furthermore I want to mark these properties with a question mark as optional.
I'm well aware of these documentation:
http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#optionalPropertiesDeclaration

I'm already using the @JsonProperty(required = false) annotation. But I'm not able to generate the question mark after the respective property in the generated typescript file.

Any help is much appreciated.

**Comment by vojtechhabarta** [comment]
Hello, short answer is `optionalProperties` parameter (http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#optionalProperties).

There are two parts in optional properties processing:
1. determining which properties are optional
2. marking optional properties in output

Typescript-generator can determine optional properties annotated with `@JsonProperty(required = false)`, just set `optionalProperties` parameter to `useLibraryDefinition` value. Unfortunatelly for historicat reasons this is not a default.

Output can be controlled using `optionalPropertiesDeclaration` parameter, exactly as you mentioned.

**Comment by pl1307** [comment]
Thank you for the fast response! 
I have added
optionalProperties = cz.habarta.typescript.generator.OptionalProperties.useLibraryDefinition
to the gradle file.
Now every attribute gets an question mark in the generated typescript interface. How do I specify that only attributes with the @JsonProperty annotation are getting a question mark?

**Comment by vojtechhabarta** [comment]
`@JsonProperty.required` is by default `false` (https://github.com/FasterXML/jackson-annotations/blob/cdff4658e4e735b5a121e76bb1846d99ed547bdb/src/main/java/com/fasterxml/jackson/annotation/JsonProperty.java#L78).

You have to set it to `true` if you don't want property to be optional.
