### ISSUE TITLE
translate Java varargs to TypeScript varargs

### ISSUE THREAD

**Issue by ispringer** [vojtechhabarta/typescript-generator#350]
The generator currently translates:

```
void foo(String ...args);
```

to:

```
foo(args: string[]): void;
```

rather than:

```
foo(...args: string[]): void;
```

**Comment by vojtechhabarta** [comment]
In which case these methods are generated? Do you use some extension?

**Comment by ispringer** [comment]
Yeah, we have a fork that generates TypeScript functions for Java methods. Sorry, I thought we had contributed those changes back, but apparently we have not.

**Comment by vojtechhabarta** [comment]
That's ok, thanks for the info.
