### ISSUE TITLE
Configurability dealing with @Deprecated annotations

### ISSUE THREAD

**Issue by shzhng** [vojtechhabarta/typescript-generator#352]
Thanks for this project, this has saved us a bunch of headache by typechecking our api communication

It would be great if there was a way to treat classes, fields, methods that are annotated with `@Deprecated` - for example choosing to exclude such fields from the compilation output

**Comment by vojtechhabarta** [comment]
If your deprecated properties are annotated using `@Deprecated` annotation you can exclude them when you add `java.lang.Deprecated` value to `excludePropertyAnnotations` parameter.

If you are generating JSDoc comments from Javadoc comments (which is relatively hard to [set up](https://github.com/vojtechhabarta/typescript-generator/wiki/Javadoc)) then Javadoc `@deprecated` tags are carried over to JSDoc.

**Comment by shzhng** [comment]
amazing, thank you

**Comment by shzhng** [comment]
@vojtechhabarta so i tried out this approach - it seems like the compile only suppresses outputs for **properties** of an object class annotated with `@Deprecated`, but not **methods** on a JAX-RS application or enum values annotated with `@Deprecated` - is this expected behavior?

**Comment by vojtechhabarta** [comment]
`excludePropertyAnnotations` is only ment for _properties_.

If you want to exclude JAX-RS _method_ and you don't mind using Swagger annotations you can annotate the method with `io.swagger.annotations.ApiOperation` and set `hidden` to `true`.

I don't think there is anything similar for excluding _enum_ values.
