### ISSUE TITLE
Inheritance from Java interfaces

### ISSUE THREAD

**Issue by vojtechhabarta** [vojtechhabarta/typescript-generator#36]
Typescript-generator currently supports **class** inheritance but not **interface** inheritance.

For java `class B extends A {}` it generates `interface B extends A {}`. This preserves relationship between A and B.

But when class or interface inherits from **interface** C the `extends C` is not generated and relationship is lost.

It would be nice if typescript-generator is able to work with interface inheritance the same way as with class inheritance but the problem is that some interfaces does not have meaning for JSON data. For example when class or interface inherits from interfaces `MyInterface`, `Serializable` and `Comparable` we probably only want to consider interface `MyInterface`. So the tricky part is how to determine "relevant" interfaces.

Suggestion what "relevant" interface means is roughly:
- interface from which some properties are inherited or
- interface which is explicitly mentioned anywhere (need to define precisely)

**Comment by ryan10132** [comment]
What do you think the timeline for this is?

I would vote for giving a blacklist of "interfaces I don't care about". Can probably have a reasonable default (Serializable, Comparable, etc). Should probably be customizable.

**Comment by vojtechhabarta** [comment]
It is probably not needed to typescript-generator be smart and try to determine which interfaces are relevant and which not. I will do it simple way. All interfaces will be processes unless excluded using `excludeClasses` parameter.
