### ISSUE TITLE
Inject Angular HttpClient implementation into RestApplicationClient

### ISSUE THREAD

**Issue by cristic83** [vojtechhabarta/typescript-generator#362]
Hey Vojtech,
I'd like to know if there is any way that we can instruct the generator to add an @Inject annotation to the constructor of the generated RestApplicationClient class. 
Our application is an Angular 7 one, which does not allow to inject classes into fields declared as interfaces (or abstract classes), unless we specify the implementing class. We've tried making the HttpClient an abstract class and define a provider like this: {provide: HttpClient, useClass: HttpClientAdapter}, but still it did not inject the adapter.
The generated code for the RestApplicationClient should have the constructor looking like this:
`
    constructor(@Inject('HttpClientAdapter')protected httpClient: HttpClient) {
    }
`
This would be very helpful for us, as we wouldn't need to change the generated class ourselves.
Thanks,
Cristi

**Comment by vojtechhabarta** [comment]
Hi,
I think that currently it is not good solution to generate `@Inject` decorator for two reasons: 1. decorators are still experimental and 2. it would be Angular specific.

I think it is better to use generated client as is (without modifications). You can write class that inherits from it and has required injectable constructor like this:

``` typescript
export class InjectableRestApplicationClient extends RestApplicationClient {
    constructor(@Inject('HttpClientAdapter') protected httpClient: HttpClient) {
        super(httpClient);
    }
}
```

**Comment by cristic83** [comment]
That solves our issue, thanks.
