### ISSUE TITLE
example using generics in type mappings

### ISSUE THREAD

**Issue by zhuker** [vojtechhabarta/typescript-generator#366]
i want to map
`class ListWrapper<T>` to typescript `T[]`
how do i do it?

Finally I returned to this issue and it is now possible to use generics in `customTypeMappings` parameter.
Released in [v2.10.466](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.10.466).

_Originally posted by @vojtechhabarta in https://github.com/vojtechhabarta/typescript-generator/issues/197#issuecomment-443884674_

**Comment by vojtechhabarta** [comment]
I thing you can map `ListWrapper<T>` Java class to `Array<T>` TypeScript type (which is the same as `T[]`).
Maven configuration example:
``` xml
<customTypeMappings>
    <mapping>com.package.ListWrapper:Array</mapping>
</customTypeMappings>
```
This should work since both `ListWrapper` and `Array` have exactly one generic parameter.

**Comment by vojtechhabarta** [comment]
Please note that in [2.16.538](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.16.538) release I changed `customTypeMappings` parameter format (#384) so it is now needed to specify generic classes including their generic parameters:
``` xml
<customTypeMappings>
    <mapping>com.package.ListWrapper[T]:Array[T]</mapping>
</customTypeMappings>
```
