### ISSUE TITLE
Javadoc property parsing is more limited than the jackson parsing

### ISSUE THREAD

**Issue by tjwilson90** [vojtechhabarta/typescript-generator#37]
Javadoc.enrichProperty currently works by looking for a java Field with the same name as the property. This does not work if no such field exists (e.g., the property was generated from a method with no corresponding field, the property was renamed with @JsonProperty, etc.)

Ideally, the PropertyModel would already know about the Field or Method it was generated from and this would be fairly trivial.

**Comment by vojtechhabarta** [comment]
Thanks for this request, now I know that somebody is using Javadoc feature (or at least tried). 😄
