### ISSUE TITLE
String "is" stripped from beginning of class member variable

### ISSUE THREAD

**Issue by nonconceptual** [vojtechhabarta/typescript-generator#373]
Given the following class:

```
public class Apple {
    private boolean isRed;
    public boolean isRed() {
        return isRed;
    }
}
```

I am seeing the following output:

```
export class Apple {
    red: boolean;
}
```

Is there any way I can stop "is" from being stripped off my class member variable?

**Comment by vojtechhabarta** [comment]
Yes, but it depends on JSON library. Which JSON library are you using in your code and how did you set `jsonLibrary` typescript-generator parameter?

When you serialize `Apple` instance into JSON how does it look like?

**Comment by nonconceptual** [comment]
Sure enough, jackson outputs `{"red":false}`. I tried with jackson 2.9.5 and 2.9.9  I gave it a shot with Gson and it works perfectly `{"isRed":false}`.

It looks like you've started adding support for Gson - I gave it a try with the maven plug in but it looks like it's not quite there yet.

**Comment by vojtechhabarta** [comment]
Ideally you should set typescript-generator to the same library you are using in your code.

The error probably means you are using older typescript-generator than 2.15.

**Comment by nonconceptual** [comment]
Definitely - I would have used gson if I had realized it was supported!

I upgraded to 2.15+ and everything looks good. Thanks so much for your help - this plugin is a huge time saver for my team.
