### ISSUE TITLE
Use Gradle configuration avoidance in Gradle Plugin

### ISSUE THREAD

**Issue by rbrindl** [vojtechhabarta/typescript-generator#382]
The gradle plugin currently directly creates the task and iterates over the tasks collection. By doing so it materializes all tasks in the project.
The task should be added via `tasks.register` and the dependent tasks should be found via `tasks.withType(JavaCompile)`

**Comment by vojtechhabarta** [comment]
I cannot decide how this is important but anyway PR is welcomed.

**Comment by rbrindl** [comment]
It does not break anything right now. However, we are just in the process of making all our builds fit for gradle 5.x and most notably implement task configuration avoidance. The typescript-generator plugin immediately materializes all tasks in the project, rendering all efforts for configuration avoidance useless. 
I will file a PR ASAP.

**Comment by vojtechhabarta** [comment]
Please note that `typescript-generator-gradle-plugin` still works with Gradle 2.1 but I think it's time to move to version 3.

**Comment by rbrindl** [comment]
Ok, that's what I just wanted to ask. The task configuration avoidance facility was introduced in gradle 4.9. https://docs.gradle.org/4.9/userguide/task_configuration_avoidance.html.
Gradle 5.5 has just been released, by the way.

So I guess, this one will have to wait. However, I did a workaround in our builds which at least solves my problem.

**Comment by vojtechhabarta** [comment]
Thanks for offering help and understanding that I want to support older versions of Gradle.
