### ISSUE TITLE
Use @ApiModelProperty value for JavaDoc in generated file

### ISSUE THREAD

**Issue by ChristianIvicevic** [vojtechhabarta/typescript-generator#386]
Assume the following sample class:

```java
@Data
@AllArgsConstructor
@ApiModel(description = "This response contains the details of a particular burger")
public class BurgerResponse {
    @ApiModelProperty(value = "Database generated burger ID",
                      required = true)
    private final Long id;

    /* ... */
}
```

The generator yields the following interface:

```typescript
/**
 * This response contains the details of a particular burger
 */
interface BurgerResponse {
    readonly id: number;
}
```

As you can see the `@ApiModel` description is being picked up properly, but I expected the output to look like this:

```typescript
/**
 * This response contains the details of a particular burger
 */
interface BurgerResponse {
    /**
     * Database generated burger ID
     */
    readonly id: number;
}
```

I'd appreciate it if `@ApiModelProperty` can be used to retrieve JavaDoc for the generated Typescript code in order to prevent code/text duplication (e.g. using `@JsonPropertyDescription` with the same literal description below `@ApiModelProperty`).

I am using the Gradle plugin if that makes any difference compared to Maven.

**Comment by vojtechhabarta** [comment]
Thanks for detailed description of the issue.

`@ApiModelProperty` is already supported when it is used on class **member that defines the property**.
Here are some examples:
### ✔️ public field
``` java
public class BurgerResponse {
    @ApiModelProperty("Database generated burger ID")
    public Long id;
}
```
### ✔️ public getter
``` java
public class BurgerResponse {
    private Long id;

    @ApiModelProperty("Database generated burger ID")
    public Long getId() {
        return id;
    }
}
```
### ❌ private field
In this case property is defined by getter but annotation is on field.
``` java
public class BurgerResponse {
    @ApiModelProperty("Database generated burger ID")
    private Long id;

    public Long getId() {
        return id;
    }
}
```
### ✔️ private field with `@JsonProperty`
In this case property is defined by private field while public getter is annotated with `@JsonIgnore`.
``` java
public class BurgerResponse {
    @ApiModelProperty("Database generated burger ID")
    @JsonProperty
    private Long id;

    @JsonIgnore
    public Long getId() {
        return id;
    }
}
```
### ✔️ class annotated with `@JsonAutoDetect`
In this case properties are defined by fields.
``` java
@JsonAutoDetect(fieldVisibility = ANY, getterVisibility = NONE, isGetterVisibility = NONE, setterVisibility = NONE, creatorVisibility = NONE)`
public class BurgerResponse {
    @ApiModelProperty("Database generated burger ID")
    private Long id;
}
```

**Comment by ChristianIvicevic** [comment]
I am using Lombok to reduce the boilerplate of writing getters and setters myself, that is why I have only private fields in my classes and Dtos. So it seems you're suggesting me to annotate all Dto classes with `@JsonAutoDetect` I guess? Is there any possibility that your plugin picks up `@ApiModelProperty` even on private fields for that purpose? Maybe using a new flag `privateLombokFields` or so?

**Comment by vojtechhabarta** [comment]
I would not like to add parameter specific to Lombok if it's not absolutely necessary. 

In your case, I think, it is actually "correct" to use `@JsonAutoDetect.fieldVisibility` because you "define" properties using those private fields. That's what is manually written and what matters.

**Comment by ChristianIvicevic** [comment]
Thank you very much for the clarification and explanation. I tried out your suggestion and it works as expected, closing this issue since it's resolved.
