### ISSUE TITLE
Jackson2 support for EXISTING_PROPERTY

### ISSUE THREAD

**Issue by croser** [vojtechhabarta/typescript-generator#390]
hi, 
is there any particular reason why `cz.habarta.typescript.generator.parser.Jackson2Parser.isSupported(JsonTypeInfo)` does not support `JsonTypeInfo.As.EXISTING_PROPERTY`? 
thanks,
j!

**Comment by vojtechhabarta** [comment]
Hi,

`JsonTypeInfo.As.EXISTING_PROPERTY` uses regular property to determine sub-types so this property can have arbitrary value. There is no guarantee that specified property will have needed value. Whereas `JsonTypeInfo.As.PROPERTY` specifies property which values are computed by Jackson.

So I do not consider `EXISTING_PROPERTY` mechanism reliable enough to provide tagged unions. I think it is better to stay conservative and generate tagged unions only for classes where we are quite confident that it is correct.

**Comment by olegshtch** [comment]
@vojtechhabarta  What about support `EXISTING_PROPERTY` on enum type? It has finite values which can be checked if `JsonSubTypes` decribed all.

**Comment by vojtechhabarta** [comment]
In #582 I added support for `EXISTING_PROPERTY`, it is released in [v2.28.785](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.28.785).
