### ISSUE TITLE
Provide outputs property in gradle task

### ISSUE THREAD

**Issue by olegshtch** [vojtechhabarta/typescript-generator#391]
Currently `generateTypeScript` task doesn't declare its outputs in inputs so task is rerun every time even if source files wasn't changed.

**Comment by vojtechhabarta** [comment]
How this issue relates to #393?

**Comment by vojtechhabarta** [comment]
And also #338? Could I close this issue as duplicate?

**Comment by olegshtch** [comment]
Yes, I think so. It related to #393 as it requires both inputs and outputs to support incremental build.
