### ISSUE TITLE
Multiproject support

### ISSUE THREAD

**Issue by olegshtch** [vojtechhabarta/typescript-generator#394]
I have a similar structure of gradle project:

```
project
|- java-subproject1
|- java-subproject2 depends on java-subproject1
|- node-subproject depends on java-subproject1:generateTypeScript and java-subproject2:generateTypeScript
```

If I generate interface of class from java-subproject2 which extends class from java-subproject1, I gets two definitions of this interface in generated typescript code, which later conflicts in typescript compilation.

Is there a way to generate typescript definition which depends on typescript definition from other subproject?

**Comment by vojtechhabarta** [comment]
Yes, it is possible (if you are generating modules - `outputKind` parameter has `module` value) but it is little bit complicated, see [Dependent modules](https://github.com/vojtechhabarta/typescript-generator/pull/276).

**Comment by olegshtch** [comment]
I get issues with providing those dependencies to `node-subproject` so I found other solution.
I've made those dependencies with `java` plugin and then call `generateTypeScript` in `node-subproject`:
```gradle
apply plugin 'java'
dependencies {
    compile project(':java-subproject1')
    compile project(':java-subproject2')
}
```

With it I have single generated file in the known place.
