### ISSUE TITLE
RequiredPropertyConstructorExtension doesn't order constructor fields correctly when OptionalAnnotations is used.

### ISSUE THREAD

**Issue by mikeporterdev** [vojtechhabarta/typescript-generator#395]
Given two Java classes
```java
public class TestSuper {
    private String requiredSuperField;
    @Nullable
    private String optionalSuperField;
}

public class TestSubClass extends TestSuper {
    private String requiredSubField;
}
```

The following output is given

```typescipt
export class TestSuper {
    readonly requiredSuperField: string;
    readonly optionalSuperField?: string;

    constructor(requiredSuperField: string, optionalSuperField?: string) {
        this.requiredSuperField = requiredSuperField;
        this.optionalSuperField = optionalSuperField;
    }
}

export class TestSubClass extends TestSuper {
    readonly requiredSubField: string;

    constructor(requiredSuperField: string, optionalSuperField?: string, requiredSubField: string) {
        super(requiredSuperField, optionalSuperField);
        this.requiredSubField = requiredSubField;
    }
}
```

This gives the following typescript compiler error:
error TS1016: A required parameter cannot follow an optional parameter. on the requiredSubField parameter to the constructor.

Maven settings.
```xml
ions>
    <extension>cz.habarta.typescript.generator.ext.RequiredPropertyConstructorExtension</extension>
</extensions>
<declarePropertiesAsReadOnly>true</declarePropertiesAsReadOnly>
<optionalAnnotations>
    <annotation>javax.annotation.Nullable</annotation>
</optionalAnnotations>
```

**Comment by vojtechhabarta** [comment]
@nivertius do you have any comment?

I think purpose of this extension was to generate constructors with just _required_ properties so there should not be `optionalSuperField?: string` parameter.

**Comment by nivertius** [comment]
I agree that there is a problem with that: Property is defined as `readonly`, so it can be only initialized in constructor. It is added to the parameters list with its exact type, making it a optional _parameter_, but required _property_.

This is possibly solved by reordering parameters for each generated constructor, with required parameters going in first, before optional parameters.

I could do the change this weekend.

**Comment by vojtechhabarta** [comment]
@nivertius thanks for quick response.
You are right about `readonly` properties, good catch.
