### ISSUE TITLE
Possibility to write one serviceClient per RestController?

### ISSUE THREAD

**Issue by Antibrumm** [vojtechhabarta/typescript-generator#398]
Hello 
I was wondering if it is possible to write a service declaration inside (or instead) the `RestApplicationClient` per `RestController`.
Currently the generator outputs one "big" client declaration, when using `<generateSpringApplicationClient>true</generateSpringApplicationClient>`, containing all found controller methods. In my case this means that the method names are changed as I have a lot of time just a "get(), find() or post()" method name in the controller.

Example:

```
export class RestApplicationClient {

    constructor(protected httpClient: HttpClient) {
    }

    get$GET$rest_admin_Scope(): RestResponse<T> {
        return this.httpClient.request({ method: "GET", url: uriEncoding`rest/admin/Scope` });
    }

    get$GET$rest_admin_User() RestResponse<T> {
        return this.httpClient.request({ method: "GET", url: uriEncoding`rest/admin/User` });
    }

}
```

My ideal target would be to get such an output:

```
export class AdminUserEditService {
   constructor(protected httpClient: HttpClient) {
   }

   get(): RestResponse<T> {
        return this.httpClient.request({ method: "GET", url: uriEncoding`rest/admin/User` });
    }
}

export class AdminScopeEditService {
   constructor(protected httpClient: HttpClient) {
   }

   get(): RestResponse<T> {
        return this.httpClient.request({ method: "GET", url: uriEncoding`rest/admin/Scope` });
    }
}
```

I was digging into the `ModelCompiler's` method `groupingByMethodContainer` but couldnt find a way to trigger such behavior. 

Do you have an idea how to achieve that? I would be fine if I need to write my own Compiler for example, but that seemed to extreme for now :)

Thanks

**Comment by Antibrumm** [comment]
Nevermind :) I found that this is possible with `<restNamespacing>perResource</restNamespacing>`.

**Comment by vojtechhabarta** [comment]
Yes, you are right 🙂
