### ISSUE TITLE
Separate output files for each class

### ISSUE THREAD

**Issue by vanditamathur** [vojtechhabarta/typescript-generator#402]
Currently I am using the maven plugin with "classPatterns" to convert all Java classes in a package to typescript. This generates the typescript implementaitons - however, all of them are in a single file. I would like that a different .ts file is created for each Java class being processed. Is that possible currently?

**Comment by vojtechhabarta** [comment]
No, it's not possible. Typescript-generator supports many output types ([Modules and Namespaces](http://www.habarta.cz/typescript-generator/doc/ModulesAndNamespaces.html)) and allowing to split output into multiple files would make it even more complex. My opinion is that it isn't so important to have each class in separate file. It is standard in Java, but in JavaScript world it is not necessary.

**Comment by vanditamathur** [comment]
Ok. Thanks for your comment. Closing this issue.
