### ISSUE TITLE
HAL resources Jackson2HalModule

### ISSUE THREAD

**Issue by kambo** [vojtechhabarta/typescript-generator#403]
Hi I am trying to generate typescript interfaces from classes extending `org.springframework.hateoas.ResourceSupport` 

Default behaviour does not give the correct JSON format.

I've tired to add 

``` 
<jackson2Modules>
       <module>org.springframework.hateoas.hal.Jackson2HalModule</module>
</jackson2Modules>
```
but get this error

```
Execution generate of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.15.527:generate failed: Class org.springframework.hateoas.hal.Jackson2HalModule$HalLinkListSerializer has no default (no arg) constructor
```

Is there a way to get this to work ?

**Comment by vojtechhabarta** [comment]
I tried to add `Jackson2HalModule` in some test but I am not able to reproduce this issue. Could please paste here stack trace (run maven with `-e` parameter)? Also sample class would help.
