### ISSUE TITLE
Duplicate properties in generated interfaces when using @JsonProperty

### ISSUE THREAD

**Issue by krezovic** [vojtechhabarta/typescript-generator#409]
I have the following class definition on the backend

```
public class ApiResultInfoProjection {
  private String status_;

  @JsonProperty("nRecords")
  private Integer numberOfRecords_;

  @JsonProperty("totalNRecords")
  private Integer totalNrRecords_;

  public String getStatus() {
    return status_;
  }

  public void setStatus(String status) {
    status_ = status;
  }

  public Integer getNumberOfRecords() {
    return numberOfRecords_;
  }

  public void setNumberOfRecords(Integer numberOfRecords) {
    numberOfRecords_ = numberOfRecords;
  }

  public Integer getTotalNrRecords() {
    return totalNrRecords_;
  }

  public void setTotalNrRecords(Integer totalNrRecords) {
    totalNrRecords_ = totalNrRecords;
  }
}
```

This is a consumer projection for JAX-RS client, which handles data received from another system we don't control. Thir JSON property names don't fit into our Java Coding Conventions, so we renamed two of them and annotated them with @JsonProperty and it works just fine on the JAX-RS client side. Our JSON provider is Jackson2.

When this projection is processed by typescript-generator, the following interface is generated on the client

```
export interface ApiResultInfoProjection {
    status: string;
    numberOfRecords: number;
    totalNrRecords: number;
    nRecords: number;
    totalNRecords: number;
}
```

Is it possible to not have these duplicates generated on the client?

**Comment by vojtechhabarta** [comment]
If you are using Jackson `ObjectMapper` with changed _visibility_ (for example by calling `setVisibility` method) you can use [jackson2Configuration](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#jackson2Configuration) parameter to configure typescript-generator consistently with your `ObjectMapper`.

You can also annotate Java class with `@JsonAutoDetect` to specify _visibility_ as you need - this is then used by Jackson and also typescript-generator.

You can also use `@JsonIgnore` annotation.
