### ISSUE TITLE
Support for java.math.BigDecimal

### ISSUE THREAD

**Issue by thamacher** [vojtechhabarta/typescript-generator#41]
Currently java.math.BigDecimal is not supported in typescript-generator in a useable way, but new TS-interfaces are created with no real value.
As this is a very commonly used class, I´d rather like to see something useful. Best case, same structure as 'com.fasterxml.jackson.databind.ser.std.NumberSerializer' creates as output, but at least something close to what toString() returns.

**Comment by vojtechhabarta** [comment]
Yes, currently `BigDecimal` is not supported and the mapping is useless.

I think `BigDecimal` should be mapped to TypeScript `number`. Jackson2 by default also produces number in JSON.
