### ISSUE TITLE
Custom values from enum

### ISSUE THREAD

**Issue by eirikaho** [vojtechhabarta/typescript-generator#411]
Is it possible to generate typescript enum types based on a method on a java enum? In my example, can i configure the typescript-generator to use method `getCode` for all enums implementsing WithCode?

My java enum:
``` java
public enum Direction implements WithCode {
  NORTH("N"),
  EAST("E"),
  SOUTH("S"),
  WEST("W");

  final string code;

  private Direction(String code) {
    this.code = code;
  }

  public String getCode() {
    return this.code;
  }
}
```

desired typescript enum:
`
export type Direction = "N" | "E" | "S" | "W";
`

actual typescript enum:
`
export type Direction = "NORTH" | "EAST" | "SOUTH" | "WEST";
`

**Comment by olegshtch** [comment]
I suppose it would be incompatible with Jackson library.

**Comment by vojtechhabarta** [comment]
@eirikaho if you are using Jackson you can annotate `getCode()` method with `@JsonValue` annotation. This tells Jackson how it should serialize enum constants to JSON and this is also supported by typescript-generator.
