### ISSUE TITLE
Error "generate failed: No input classes found" when package is empty

### ISSUE THREAD

**Issue by anbaran** [vojtechhabarta/typescript-generator#413]
When I specify 

```
<classPatterns>
<pattern>com.some.package.dto.**Dto</pattern>
<classPatterns>
```
and this location doesn't have classes yet but will have in the future (it is a multi module java application) the goal fails.It would be good it it still proceeded successfully.

Using version:  cz.habarta.typescript-generator:2.16.538 with maven

**Comment by olegshtch** [comment]
I've made subproject with classes are dependencies of this project: https://github.com/vojtechhabarta/typescript-generator/issues/394

**Comment by anbaran** [comment]
Thanks for you hint, the answer from #394 solved my issue
