### ISSUE TITLE
Java enums to emulated typescript object enums extension

### ISSUE THREAD

**Issue by nuth** [vojtechhabarta/typescript-generator#417]
Hello, I'd like to be able to generate enums with fields and values (like in java). Typescript doesn't support this, so it would need to be emulated like this:
``` typescript
export class PizzaSize {
  static readonly SMALL  = new PizzaSize('SMALL', 'A small pizza');
  static readonly MEDIUM = new PizzaSize('MEDIUM', 'A medium pizza');
  static readonly LARGE  = new PizzaSize('LARGE', 'A large pizza');

  // private to disallow creating other instances of this type
  private constructor(private readonly key: string, public readonly value: any) {
  }

  toString() {
    return this.key;
  }
}
```
Taken from: https://stackoverflow.com/a/51398471/5639571

If I get time, I'll look into myself and attempt to create an extension, but in the mean time any feedback on the purposed method would be great.

**Comment by vojtechhabarta** [comment]
Hello,
primary purpose of typescript-generator is to describe JSON data or REST service. Transferring all data from Java enum to TypeScript is not needed for this. If you need to transfer these data to client for other purposes I would expose them through REST service. But if you like to generate TypeScript class with all data in it you could create an extension (as you are suggesting).
