### ISSUE TITLE
Support for java.util.UUID

### ISSUE THREAD

**Issue by thamacher** [vojtechhabarta/typescript-generator#42]
Currently java.util.UUID is not supported in typescript-generator in a useable way, but new TS-interfaces are created with no real value.
As this is a very commonly used class, I´d rather like to see something useful. Best case, same structure as 'com.fasterxml.jackson.databind.ser.std.UUIDSerializer' creates as output, but at least something close to what toString() returns.

**Comment by vojtechhabarta** [comment]
I agree.

Jackson2 produces by default something like this: `"df7c263b-64f0-4660-bd21-ba35cc3a986f"` so it should be mapped to `string` in TypeScript. It is also possible to define type alias and use it like this:
``` typescript
type UUID = string;

interface Test {
    value: UUID;
}
```
but I prefer to map `java.util.UUID` directly to `string` now.
