### ISSUE TITLE
Converting boolean from Java to Typescript

### ISSUE THREAD

**Issue by ghassen1khalil** [vojtechhabarta/typescript-generator#422]
### [Given] :electric_plug:
Java POJO with some boolean attributes following the naming convention :
```
public class ClaimAuto extends Claim {
    ...
    private boolean isPolicyholderDriving;
    ...
 }
```
### [Exptected] :airplane:
Converted POJO into Typescript interface having the same attribute 
```
interface ClaimAuto extends Claim {
    ...
    isPolicyholderDriving: boolean ;
    ...
}
```
### [Actual] :ambulance:
Wrong boolean attribute name : 
```
interface ClaimAuto extends Claim {
    ...
    policyholderDriving: boolean ;
    ...
}
```

**Comment by vojtechhabarta** [comment]
Are you using Jackson JSON library?

If yes, typescript-generator produces properties consistent with what Jackson writes to JSON. Jackson uses annotations like `@JsonProperty` and `@JsonAutoDetect` to get properties from Java class. It is also possible to change "visibility" in Jackson's `ObjectMapper`. If you are not using default "visibility" in `ObjectMapper` you can set [jackson2Configuration](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#jackson2Configuration) parameter in typescript-generator to match your `ObjectMapper` settings.

If you are using Gson JSON library set [jsonLibrary](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#jsonLibrary) parameter to `gson` value (which was added recently and it's not still mentioned in description).
