### ISSUE TITLE
Extension to generate JSON.parse revivers

### ISSUE THREAD

**Issue by joshiste** [vojtechhabarta/typescript-generator#427]
I've Instants in my api that are serialized as `"2019-10-21T05:27:53.816344Z"` but the generated type is `Date` which is good so far, but When using a plain `Json.parse(...)` the string isn't converted. 
I wonder if the generator can generate functions which do convert all the date using `new Date(...)` by using  `JSON.parse()` with a generated reviver function (second argument)?

Or is there already an extension doing this? Is it somehow possible to write our own extensions?

**Comment by vojtechhabarta** [comment]
My first comment is that to describe your JSON data you could set parameter `mapDate` to `asString` value (unfortunately for historical reasons it has default value `asDate`). In this case the property would have type `string` and you would know that you have to convert it yourself.

If you want dates to be converted automatically that's harder. There is no possibility to generate `reviver` function. Related thing is `JsonDeserializationExtension` which recursively transforms object tree into classes, maybe it could be improved to transform also dates.

**Comment by joshiste** [comment]
> My first comment is that to describe your JSON data you could set parameter mapDate to asString value (unfortunately for historical reasons it has default value asDate). In this case the property would have type string and you would know that you have to convert it yourself.

no I exactly want them as dates but converted. currently my revivers are handcrafted...

> Is it somehow possible to write our own extensions?

is this somehow possible (e.g. by adding a custom dependency to the plugin)?
