### ISSUE TITLE
Allow null for values marked with @Nullable annotation

### ISSUE THREAD

**Issue by olegshtch** [vojtechhabarta/typescript-generator#430]
Currently in `2.17.558` `@Nullable` annotation makes field is `Type | undefined` type.

Could it generate type for it is `Type | null | undefined` because it in Java's Jackson it is same to not set a field or set field to `null`?

**Comment by vojtechhabarta** [comment]
Yes that's possible, set [optionalPropertiesDeclaration](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#optionalPropertiesDeclaration) parameter to `questionMarkAndNullableType` or `nullableAndUndefinableType` value.

**Comment by olegshtch** [comment]
Thanks!
