### ISSUE TITLE
Number based enum with predefined values

### ISSUE THREAD

**Issue by lpandzic** [vojtechhabarta/typescript-generator#431]
Currently I have an enum like:
```java
public enum Type {
    A(1),
    B(5),
    C(2),

    private final int value;

    Type(int value) {
        this.value = value;
    }
}
```
and I'd like to get something like:
```ts
enum Type {
    A = 1,
    B = 5,
    C = 2,
}
```
Can mapping for a case like this be added?

**Comment by vojtechhabarta** [comment]
Are you using Jackson? If yes, there are some possibilities how to produce enum with numbers. For example annotating `value` field with `@JsonValue` which is supported by typescript-generator. Sample enum:
``` java
public enum Type {
    A(1),
    B(5),
    C(2);

    @JsonValue
    private final int value;

    private Type(int value) {
        this.value = value;
    }
}
```

**Comment by lpandzic** [comment]
It works with `<mapEnum>asEnum</mapEnum>`, thanks!

**Comment by vojtechhabarta** [comment]
Yes, I forgot to mention it.
