### ISSUE TITLE
Discussion group

### ISSUE THREAD

**Issue by lpandzic** [vojtechhabarta/typescript-generator#432]
Would it make sense to open a discussion group somewhere? https://gitter.im/ seems quite popular or even a google group?
Right now I feel like I have to open an issue just to get some feedback on an idea.

**Comment by vojtechhabarta** [comment]
I think this project doesn't have such a big community to have some discussion group. In fact I think it's good that people share their comments/questions/answers here on github. In this project it's totally fine to use issues for questions.
