### ISSUE TITLE
Feature request: generate TS constructor in classes

### ISSUE THREAD

**Issue by beatjost** [vojtechhabarta/typescript-generator#434]
Wouldn't it be handy to be able to generate also an all-args TS constructor if you use the option to generate classes instead of interfaces (asClasses)?

This should be consider also the option 'optionalProperties'. Alternatively to 'all-args' it could also be done by considering the Java-Constructor-Signatures as a generation-source.

Result somehow like:

```
class Item {
  constructor({
    public id: number,
    public createdAt: number,
  }) {}
}
```

Furthermore it would here also be nice to configure the generally used access modifier...

**Comment by vojtechhabarta** [comment]
There is an extension [cz.habarta.typescript.generator.ext.RequiredPropertyConstructorExtension](https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/ext/RequiredPropertyConstructorExtension.java) which generates constructors. You can add it using `extensions` or `extensionsWithConfiguration` parameter. Is it helpful for you?

**Comment by beatjost** [comment]
Thank you for your quick and helpful answer - yes, this should do the trick :)
