### ISSUE TITLE
Possible to define something like <requiredAnnotations> in maven plugin?

### ISSUE THREAD

**Issue by Q-Man** [vojtechhabarta/typescript-generator#443]
In the typescript generator maven plugin it's possible to define `<optionalAnnotations>`

I need the opposite: All generated properties should be optional, except the ones with `@NotNull` annotations.

Is it possible to configure the generator to achieve this?

**Comment by vojtechhabarta** [comment]
Currently this is not possible.
When using Jackson it is possible to set `optionalProperties` configuration parameter to `useLibraryDefinition` and use `@JsonProperty(required = true)` annotation.
But I think something like `requiredAnnotations` could be added to typescript-generator.

**Comment by vojtechhabarta** [comment]
Released in [v2.21.588](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.21.588).
