### ISSUE TITLE
Gradle plugin doesn't declare inputs, outputs

### ISSUE THREAD

**Issue by Sboddd** [vojtechhabarta/typescript-generator#445]
The Gradle plugin doesn't declare its inputs or outputs, so Gradle can't detect when the generated file is UP-TO-DATE.
As a workaround, I was able to add 
`outputs.file('my_filename')`
`inputs.files(tasks.compileTestJava.classpath).withPropertyName('classpath').withNormalizer(ClasspathNormalizer)` 
to my build.gradle, and that appears to have fixed it - the generator only runs when I change one of the classes it depends on.

(I'm a total Gradle neophyte, so I'm not sure how to fix this in the project's gradle plugin).

**Comment by vojtechhabarta** [comment]
Sorry for late response and thank you for sharing your workaround.
I will merge #393, let's see if it helps in your case.

**Comment by vojtechhabarta** [comment]
Released [2.19.575](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.19.575).
