### ISSUE TITLE
JSON-B support

### ISSUE THREAD

**Issue by rmannibucau** [vojtechhabarta/typescript-generator#446]
Hi,

I just discovered this tool and it is literally awesome!
Do you think JSON-B support could be added natively even if currently jackson2 works not bad for several cases.

**Comment by vojtechhabarta** [comment]
Sorry for late response and thanks for your interest.

Support for JSON-B would be very good addition to this tool but I would leave it to anybody else for contribution. See also #354.

**Comment by rmannibucau** [comment]
(just to link) here is a PR doing it: https://github.com/vojtechhabarta/typescript-generator/pull/465

**Comment by vojtechhabarta** [comment]
Released in [v2.22.595](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.22.595). Thanks!
