### ISSUE TITLE
Support for constructors?

### ISSUE THREAD

**Issue by phudson** [vojtechhabarta/typescript-generator#447]
As far as I can tell, no matter what options I choose, the output doesn't include constructors. Is this correct?  Are there any plans to address this in future versions?

**Comment by vojtechhabarta** [comment]
There is a `RequiredPropertyConstructorExtension` which generates constructors - #324, #336.
And I am considering to add possibility to generate "copy" constructors.

**Comment by phudson** [comment]
Thanks. I'm not sure how to use extensions, but I'll do some reading and give it a go.
Does this synthesise constructors based on the properties, or does it replicate any constructors that exist in the  Java class files?

**Comment by vojtechhabarta** [comment]
Are you using Maven? If yes, here is sample configuration:
``` xml
<configuration>
    <extensions>
        <extension>cz.habarta.typescript.generator.ext.RequiredPropertyConstructorExtension</extension>
    </extensions>
    ...
</configuration>
```

This extension creates constructor based on properties (not Java constructors).

**Comment by vojtechhabarta** [comment]
From version [2.20.583](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.20.583) it is possible to generate constructors using `generateConstructors` parameter, see #451.
