### ISSUE TITLE
Support for org.joda.time.DateTime

### ISSUE THREAD

**Issue by thamacher** [vojtechhabarta/typescript-generator#45]
Currently org.joda.time.DateTime is not supported in typescript-generator in a useable way, but new TS-interfaces are created with no real value.
As this is a very commonly used class, I´d rather like to see something useful.
We currently use the format "yyyy-MM-dd'T'HH:mm:ss'Z'" for date-processing, but as this is probably a highly customizable topic, maybe a general date-format should be configurable.

**Comment by vojtechhabarta** [comment]
I don't want to add Joda-Time dependency to typescript-generator. Currently you can implement custom `TypeProcessor` to handle `org.joda.time.DateTime` class. I also plan to add possibility to specify custom type mappings in configuration so it will be possible to map this class to TypeScript `string`.

**Comment by vojtechhabarta** [comment]
#60 covers this request.
