### ISSUE TITLE
optionalAnnotations annotation not getting picked up

### ISSUE THREAD

**Issue by caguthrie** [vojtechhabarta/typescript-generator#452]
Using version 2.18.565

Sometimes it seems that annotations I defined in `optionalAnnotations` are not getting picked up and I'm not sure why:

I have the config set up like this:
```java
                    <optionalProperties>useSpecifiedAnnotations</optionalProperties>
                    <optionalAnnotations>
                        <annotation>com.lib.models.Nullable</annotation>
                    </optionalAnnotations>
```

The library I'm using is using Immutables and has this structure:

```java
@JsonSerialize(
    as = ImmutableFoo.class
)
@JsonDeserialize(
    builder = Builder.class
)
@Immutable
public interface Foo {
    @Nullable
    String name();
}
```

`ImmutableFoo` does carry over the `@Nullable annotations to but the instance variable and the method:

```java
public final class ImmutableFoo implements Foo {
      @Nullable
    private final String name;

    // ...

    @JsonProperty("name")
    @Nullable
    public String name() {
        return this.name;
    }
}
```

The `@Nullable` annotation that this library uses is in the same package as both of these files, not sure if that would matter.

**Comment by vojtechhabarta** [comment]
How does your Nullable annotation look like? I am specifically interested in its `@Target` because annotations with `TYPE_USE` are handled differently.
Do you generate TypeScript declaration for Foo or ImmutableFoo (or both)?

**Comment by caguthrie** [comment]
I discovered adding `@Retention(RUNTIME)` fixes this issue.  Closing.

**Comment by serv-inc** [comment]
FYI: https://github.com/vojtechhabarta/typescript-generator/pull/846 provides the code to find this problem earlier
