### ISSUE TITLE
Problem with defining extra Union types in typescript when using inheritance in java

### ISSUE THREAD

**Issue by jchobantonov** [vojtechhabarta/typescript-generator#454]
While I was playing around with the playground (https://jechlin.github.io/ts-gen-aws/) I have noticed the following behavior when using the Car class hierarchy example:

The typescript will generate extra CarUnion type like this:
type CarUnion = DieselCar | ElectricCar;

The problem is when in the groovy source I change the ElectricCar to be called CarUnion - then the playground can't update the typescript output most likely because of the duplicate type CarUnion that will occur

Also another thing:
Probably this is issue only with the playground, but if I want to introduce following class into the groovy code:
```
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include=JsonTypeInfo.As.PROPERTY, property="@class")
class Person {
    public String name
}
```
at the end then the typescript will not have this type Person - if I put it on top of the file then only this Person type will be generated into the typescript - so I can't test to see if I introduce CarUnion class after the Car hierarchy if it is going to break the generation as well

**Comment by jchobantonov** [comment]
I have just saw that there is following property 
        "disableTaggedUnions" : true,
that could disable the union type generation, then I could have a class names CarUnion 

The issue would be only when this dissabledTaggedUnions is false

**Comment by jchobantonov** [comment]
ok I have opened the browser network console and saw that there is following error generated:

HTTP 200:
```
{"errorMessage":"Multiple classes are mapped to the same name. You can use 'customTypeNaming' or 'customTypeNamingFunction' settings to resolve conflicts or exclude conflicting class if it was added accidentally.","errorType":"cz.habarta.typescript.generator.compiler.SymbolTable$NameConflictException","stackTrace":["cz.habarta.typescript.generator.compiler.SymbolTable.reportConflicts(SymbolTable.java:106)","cz.habarta.typescript.generator.compiler.SymbolTable.resolveSymbolNames(SymbolTable.java:92)","cz.habarta.typescript.generator.compiler.ModelCompiler.javaToTypeScript(ModelCompiler.java:95)","cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:52)","cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:43)","cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:38)","cz.habarta.typescript.generator.TypeScriptGenerator$generateTypeScript.call(Unknown Source)","org.jamieechlin.ts.Lambda.myHandler(Lambda.groovy:70)","sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)"]}
```

but this exception do not replace the typescript source code in playground so unless someone checks the network traffic you won't know what it happening

**Comment by vojtechhabarta** [comment]
@jchobantonov thank you for your interest in typescript-generator. Unfortunately playground is unsupported. If you had time I would recommend you to try typescript-generator on your project using Maven or Gradle.

BTW I think tagged unions are useful concept in TypeScript so would recommend not to disable this feature in typescript-generator.
