### ISSUE TITLE
Better optional properties with Jackson

### ISSUE THREAD

**Issue by danielkaneider** [vojtechhabarta/typescript-generator#455]
Hi,

I'm creating a follow-up of #250. The current possibilities still feel very limiting to me. 

### Current pain points
1. Currently a primitive property is not considered as non-optional when using `useLibraryDefinition`
2. It is not possible to use `useLibraryDefinition` and `useSpecifiedAnnotations` at the same time

How it should work
- primitives such as `int getNumber()` should not be optional
- all other objects eg `String getText()` should default to library
- annotations specified (`NonNull`/`Nullable`) could overrule this 

### Suggestions
1. `Jackson2Parser` line 229 should be rather `!beanPropertyWriter.isRequired() && !beanPropertyWriter.getType().isPrimitive()`
2. It would be nice if there is a `OptionalProperties.useLibraryAndAnnotations`

**Comment by vojtechhabarta** [comment]
Hi,

your proposal seems good. Problem is with primitive types because changing how they are handled would be breaking change.

I am thinking about adding `requiredAnnotations` parameter (see #443). Properties would be optional by default when using `requiredAnnotations` and required by default when using `optionalAnnotations` (as it is now). Only one of `optionalAnnotations` and `requiredAnnotations` could be used. Would that help you somehow or would it change your proposal?

**Comment by danielkaneider** [comment]
Yes, #443 sounds exactly like our use-case. I'd suggest to name it `nonNullAnnotations` (rather than requiredAnnotations) as there is a `javax.annotation.NonNull` and a `org.checkerframework.checker.nullness.qual.NonNull` already. Please also keep in mind that checking for `(required|optional)Annotations.isEmpty()` is not really straight-forward for the user. I'd bind it to an additional setting (eg. OptionalProperties).

Regarding primitives, I know about backwards-compatibility. Thats why I suggested `OptionalProperties.useLibraryAndAnnotations` which could introduce also the change with the primitives.

**Comment by vojtechhabarta** [comment]
Regarding configuration parameter naming: I think we are dealing with two things from TypeScript:
1. **properties** that can be _optional_ or _required_ (this is TypeScript terminology)
2. _nullability_ of **types** (also TypeScript terminology)

For example `lib.es5.d.ts` TypeScript file contains types `Required<T>` and `NonNullable<T>`.

So for properties I would use `optionalAnnotations` and `requiredAnnotations` while for types I would use `nullableAnnotations` (and leave `nonNullableAnnotations` for non-nullable types should we need it in the future).

**Comment by vojtechhabarta** [comment]
Parameter `requiredAnnotations` is released in [v2.21.588](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.21.588).
