### ISSUE TITLE
Targeting only specific java types

### ISSUE THREAD

**Issue by BudWhiteStudying** [vojtechhabarta/typescript-generator#459]
I'd like to target all Java enums under a certain package, without converting classes and interfaces. Package matching can be done through the `classPatterns` attribute and works like a charm, but I couldn't find a way to process enums only.

Does such an option exist?

Astounding work by the way.

**Comment by vojtechhabarta** [comment]
Thanks. Unfortunately it's not possible to generate just enums and not other classes. But if your enums follow some naming convention (like for example `FistEnum`, `SecondEnum` etc.) you can use `classPatterns` parameter to specify enums by name. (Or you can always specify all your enums one by one using `classes` parameter which is not much convenient but it is possible.)

**Comment by BudWhiteStudying** [comment]
Thanks for your reply, understood. It would be an interesting addition imho, since I believe a common use case for this neat work of yours is exactly sharing enums between client and server (even I found it from a SO question tackling that issue exactly).

**Comment by vojtechhabarta** [comment]
Another possibility is to extend your enums from some marker interface or mark them with some annotation and then use `classesImplementingInterfaces` or `classesWithAnnotations` parameter (instead of `classPatterns`). But probably you are already aware of this.
