### ISSUE TITLE
Support for joda Money

### ISSUE THREAD

**Issue by thamacher** [vojtechhabarta/typescript-generator#46]
Joda Money is a widely used class in the java-world.
Currently the Money-class is serialized into a very detailled way, which is not very straightforward and useful. I would rather like to see a more minimalistic way of serializing Money. E.g. something like

value:number, //e.g. 1000, where last 2 digits are used for fraction to avoid rounding.
currency:string //e.g. EUR
formatted:string //useful as sometimes the currency-symbol is before the amount (e.g. $10.-) and sometimes after (e.g. 10,-€) and also the formatting is different in each currency.

But this would only be one suggestion.

**Comment by vojtechhabarta** [comment]
#60 covers this request.
