### ISSUE TITLE
GernericTypes customMapping

### ISSUE THREAD

**Issue by melistik** [vojtechhabarta/typescript-generator#460]
How to map different generic types. In my API is use different Types of map like:

```java
Map<String, List<String>> keyValuesMap;
Map<String, Map<String, Integer>> keyTreeMap;
Map<String, Translation> keyTranslationMap;
Map<String, String> keyValueMap;
```

I would like to configure the generator so that the result looks like
```typescript
keyValuesMap: Record<string, string[]>;
keyTreeMap: Record<string, Record<string, number>>;
keyTranslationMap: Record<string, Translation>;
keyValueMap: Record<string, string>;
```

How to achieve this configuration. The documentation only describes a general Generic representation with T, T1, T2...

Thx in advance

**Comment by vojtechhabarta** [comment]
It is possible to translate all Java `Map` types to `Record` type in TypeScript using `customTypeMappings` parameter by adding `java.util.Map<K,V>:Record<string,V>` mapping. If your configuration is in XML file (Maven) you can use `[]` instead of `<>` (to avoid escaping).
