### ISSUE TITLE
Configuration help, there is a way to inlude the static fields of java classes on the generation?

### ISSUE THREAD

**Issue by p4535992** [vojtechhabarta/typescript-generator#463]
There is a way to include on the output typescript the static fields of java classes without convert the class to a enum?

For example these are a java interface and a java class:

```java

public interface MyInterface {
	public static String TEST = "TEST";
}

public class MyClass {
	public static String TEST = "TEST";
}
```

i want on the typescript module generated something like this:

```
export class MyInterface {
  public static readonly TEST = "TEST";
}
export class MyClass {
  public static readonly TEST = "TEST";
}
```

there is some configuration of the plugin for accomplish this?

Greetings.

**Comment by vojtechhabarta** [comment]
This is not possible. See my [comment](https://github.com/vojtechhabarta/typescript-generator/issues/426#issuecomment-546348797).

**Comment by p4535992** [comment]
Ok , ty for the info.
