### ISSUE TITLE
Jetbrains Nullable don't working in Java

### ISSUE THREAD

**Issue by evgeniy-logvinov** [vojtechhabarta/typescript-generator#464]
I am using org.jetbrains.annotations.Nullable in a project to set nullable fields.
I am trying to use:
```
<optionalAnnotations>
  <annotation>org.jetbrains.annotations.Nullable</annotation>
</optionalAnnotations>
 <optionalPropertiesDeclaration>
   nullableAndUndefinableType
</optionalPropertiesDeclaration>
```
or:
```
<nullableAnnotations>
  <annotation>javax.annotation.Nullable</annotation>
</nullableAnnotations>
```
But it doesn't work in the generated file.
With javax.annotation.Nullable all fine.
This is how I use it in dto.
```
@Nullable
@Column(name = "room3")
private String room3;
```
And result in generated file when I use jetbrains
```
export interface Area {
    id: number;
    name: string;
    room3: string;
    streets: Street[];
}
```
And when I use javax
```
export interface Area {
    id: number;
    name: string;
    room3: string | null | undefined;
    streets: Street[];
}
```

**Comment by vojtechhabarta** [comment]
By default Jackson uses public fields and properties. Do you have public getter for `room3` field? Is it written by hand or generated?

**Comment by RobbinBaauw** [comment]
I think this will not work because the annotation is not present at runtime

**Comment by vojtechhabarta** [comment]
@RobbinBaauw you are right, there is `RetentionPolicy.CLASS`.

**Comment by evgeniy-logvinov** [comment]
Thanks a lot! I will close the issue.
