### ISSUE TITLE
Support for custom JsonSerializer

### ISSUE THREAD

**Issue by thamacher** [vojtechhabarta/typescript-generator#47]
It would be great, if a property annotated with @JsonSerializer will be considered.
As a first approach only generating "any" would be even better, that returning the serialized-object as this is surely not used.
An even more honourable way would be to somehow create a TypeScript-mapping that matches to the same structure, as the one generated through JsonSerializer.

**Comment by vojtechhabarta** [comment]
#60 covers this request.
