### ISSUE TITLE
Make all primitives non nullable?

### ISSUE THREAD

**Issue by mellson** [vojtechhabarta/typescript-generator#472]
Is it possible to make all Java primitives non nullable without having to decorate an existing code base with annotations?

I have seen that requiredAnnotations have been added, but I don't think I can use that to say that I want all the primitives to be non null (without annotations). But maybe I'm wrong.

**Comment by vojtechhabarta** [comment]
Currently this is not possible. If I understand it correctly you would like to have all properties optional except for those with primitive type and except for those annotated with some "required" annotations. Is that right?

**Comment by mellson** [comment]
@vojtechhabarta that is correct!

**Comment by vojtechhabarta** [comment]
I think this feature is implemented in #632 which was released in [2.30.840](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.30.840).

**Comment by mellson** [comment]
@vojtechhabarta neat, thanks 😊
