### ISSUE TITLE
Cannot generate method signature of class

### ISSUE THREAD

**Issue by changchengqin** [vojtechhabarta/typescript-generator#473]
Following a simple example and wiki tried it.

why the method signature of the class cannot be generated?

my original java class:

![image](https://user-images.githubusercontent.com/3336443/78562410-de8ec400-784b-11ea-93aa-a5f82c67fc34.png)

the generated file 
![image](https://user-images.githubusercontent.com/3336443/78562435-ea7a8600-784b-11ea-83d4-19c055746ff8.png)

**Comment by vojtechhabarta** [comment]
This tool treats your `Test` class as a JSON class so it uses just its _properties_. In case of Jackson library it usually means public fields and public getters. You can try for example following class:
``` java
public class Person {
    public String name;
    public int age;
    public boolean hasChildren;
    public List<String> tags;
    public Map<String, String> emails;
}
```

**Comment by changchengqin** [comment]
ok
