### ISSUE TITLE
HttpClient inheritance 

### ISSUE THREAD

**Issue by RobbinBaauw** [vojtechhabarta/typescript-generator#474]
Hi,

Currently it is possible to generate HttpClients. But in those clients, inheritance on the server is not taken into account. It would be nice if this was possible, as you can have services that extend each other.

For example, you may have an abstract `BaseEntityService` class and make derivatives based on that, and on the client you might want to refer to this base class to make a more generic environment.

How hard would it be to support this? I would be able to help implementing it!

**Comment by vojtechhabarta** [comment]
Thanks for your effort to improve this tool.
I think that would be rather complicated. I would prefer not to add this feature (at least not now) because it brings just better structure to generated clients.

**Comment by RobbinBaauw** [comment]
Hm I have tried to implement it and it is indeed complex. If it gets implemented in the future, my suggestion would be something like: 
- Implement every method for the service in the "leaf" - the actual service. This is required so that the URI is correct
- Make every class / interface from which a method is derived an interface without an implementation. If a service extends another service you can extend that service, as every method is implemented in the leaf as well
My implementation can currently do this correctly, but it is missing inheritance and generics support. I'll see if I can find out how to do that.

**Comment by vojtechhabarta** [comment]
Closing this issue, I can reopen it if needed.
