### ISSUE TITLE
Example with ClientExtension

### ISSUE THREAD

**Issue by evgeniy-logvinov** [vojtechhabarta/typescript-generator#475]
Hi, everyone!
I tried to understand how HttpClient inheritance working, but I cannot understand how it works when I want to customize something at my generated file. For example, I don't want to pass the base URL at the first parameter.
![image](https://user-images.githubusercontent.com/5665076/79128699-a5ef6d00-7dac-11ea-9326-8a23ecef6385.png)

I found one first solution - it passes some parameters inside the pom file, and the second solution to inherit custom client. 
At first solutions, I don't found some ability to do this.
At second solution, when I add it to my project where I tried to use your plugin I cannot use it. 
Which is the best way to do this? 
Or maybe you have some example of how I can inherit Client for my app?

**Comment by vojtechhabarta** [comment]
Hi,
how do you want to provide `baseUrl`? Do you want to fill it somewhere statically?
You can inherit generated class like this:
``` typescript
export class MyAxiosAuthControllerClient extends AxiosAuthControllerClient {
    constructor() {
        super("https://myserver/myservice/api");
    }
}
```
and create instance `const client = new MyAxiosAuthControllerClient()` without passing the URL.
Is that what you want?

**Comment by evgeniy-logvinov** [comment]
I mean add a new parameter to a constructor at AxiosAuthControllerClient. 

> This interface can be implemented in typescript-generator extension (like cz.habarta.typescript.generator.ext.AxiosClientExtension) or in user code.

 but that enough for me. It will help me. Thanks a lot.
