### ISSUE TITLE
Overwrite Axios version in AxiosClientExtension

### ISSUE THREAD

**Issue by agaengel** [vojtechhabarta/typescript-generator#479]
Is it possible to define the axios version for the package.json

would this some how be possible via maven ?

<extensionsWithConfiguration>
  <extension>
    <className>cz.habarta.typescript.generator.ext.AxiosClientExtension</className>
  </extension>
</extensionsWithConfiguration>

Currently the axios clinet is set to 0.19.0 and version 0.19.2 is available.

Regards
Alex

**Comment by vojtechhabarta** [comment]
Hello Alex,

I changed axios version used by `AxiosClientExtension` to 0.19.2. I also made this configurable but only for emergency situations, `AxiosClientExtension` should use latest version.

So for anybody: each time new axios version is released (and you think it is worth upgrading) please ping me (or submit PR) and I will update it.

**Comment by agaengel** [comment]
Hi Vojtěch, 
sounds great.

do you habe any plans to release this version to maven central?

Regards
Alex

**Comment by vojtechhabarta** [comment]
Hi, sorry for late response.
This change is now released in version [2.23.603](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.23.603).
