### ISSUE TITLE
Is there an option to exclude private properties?

### ISSUE THREAD

**Issue by Guilherme8482** [vojtechhabarta/typescript-generator#482]
I'm trying to describe objects with public properties in my front-end application, but when I start generating all the properties appear in the final interface, even properties that shouldn't be in the final object.
I need an option to hide all private properties.
Tahanks

**Comment by vojtechhabarta** [comment]
Are you using Jackson2 and have you set `jsonLibrary` parameter to `jackson2` value? By default Jackson uses only public fields and properties (getters, setters) and typescript-generator gets list of properties from Jackson. So there should not be private properties generated.
