### ISSUE TITLE
Jackson 2 named subtypes are not used as discriminator literals

### ISSUE THREAD

**Issue by clamothe** [vojtechhabarta/typescript-generator#485]
Jackson 2 allows subtypes to be registered 
using `ObjectMapper#registerSubtypes(com.fasterxml.jackson.databind.jsontype.NamedType...).` instead of defining a `JsonTypeName` annotation.

Subtypes registered using this method are not recognized by `Jackson2Parser#getTypeName`. It resorts to using a class's simplified name, which is inconsistent with the discriminator literal that Jackson will serialize with.

**Comment by vojtechhabarta** [comment]
Released in [2.24.612](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.24.612).
