### ISSUE TITLE
Do not create constructors for Typescript interfaces

### ISSUE THREAD

**Issue by manstis** [vojtechhabarta/typescript-generator#489]
If `generateConstructors` is set to `true` Java interfaces result in Typescript interfaces with a constructor. This is invalid. 

As an aside, to also explain my second commit on the PR, if using `generateConstructors` and the `JsonDeserializationExtension` together, the extension attempts to call zero-parameter constructors. I've updated the extension to pass the `data` parameter passed to the JSON related helper method to the object constructor; matching that of the generated constructor.

**Comment by manstis** [comment]
See https://github.com/vojtechhabarta/typescript-generator/pull/490 for a fix.

**Comment by vojtechhabarta** [comment]
Released in [2.24.612](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.24.612).
