### ISSUE TITLE
Handle bad field names

### ISSUE THREAD

**Issue by ryan10132** [vojtechhabarta/typescript-generator#49]
Have an interesting edge case for the typescript-generator

given a java declaration like:

```
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
public static interface BadFieldClass {
}
```

note the property value “@class”. Nothing wrong with this in jackson polymorphism land, however the typescript-generator outputs:

```
export interface BadFieldClass {
    @class?: string;
}
```

which does not compile. This *can* be made to compile by instead outputting

```
export interface BadFieldClass {
    “@class”?: string;
}
```

which is a little weird, but the typescript compiler actually supports it pretty well. 

Can we get the generator to output the latter? I’m not sure the best way to do this, you could handle the case for @JsonType explicitly or perhaps more generally change the emitter so that if it were going to output a field name that was not valid in typescript, it wraps it in quotes.

Thanks!

**Comment by vojtechhabarta** [comment]
Yes, I think emitter is the right place to handle this.
