### ISSUE TITLE
Support for JSON classes written using JAXB

### ISSUE THREAD

**Issue by vojtechhabarta** [vojtechhabarta/typescript-generator#5]

**Comment by vojtechhabarta** [comment]
Opened for a year and it seems there is no interest in this feature.

**Comment by vojtechhabarta** [comment]
Reopening...

Typescript-generator should be able to generate for following Java class:
``` java
import javax.xml.bind.annotation.*;

@XmlRootElement
public class MyJaxbBean {

    @XmlElement(name = "king")
    public String name;

    @XmlTransient
    public int age;
}
```
this TypeScript interface:
``` typescript
interface MyJaxbBean {
    king: string;
}
```

**Comment by unnamed224** [comment]
What about if I have something like this -> @XmlElement(name = "Country3CharISOCode", required = true) ?? That seems to be ignored. And I can't make it right even if I add javax.xml.bind.annotation.XmlElement to optionalAnnotations cause then every property that has this annotation is optional, no matter if the required parameter inside the brackets is true or false.

**Comment by unnamed224** [comment]
Yes I do.

**Comment by unnamed224** [comment]
<configuration>
                    <jsonLibrary>jaxb</jsonLibrary>
			<customTypeNamingFunction>function(name, simpleName) { return name; }</customTypeNamingFunction>
			<customTypeMappings>
				<element>javax.xml.datatype.XMLGregorianCalendar:Date</element>
			</customTypeMappings>
			<outputFileType>implementationFile</outputFileType>
			
			
			<sortTypeDeclarations>true</sortTypeDeclarations>
                    <outputKind>module</outputKind>
                </configuration>



Here is the configuration part of my pom.xml without the classPatterns.

**Comment by unnamed224** [comment]
https://pastebin.com/9tayRCme

Here is the configuration part of my pom.xml without the classPatterns

**Comment by vojtechhabarta** [comment]
It should work.
There is a test for JAXB class: [JaxbTest.java](https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-core/src/test/java/cz/habarta/typescript/generator/JaxbTest.java). It also works with `required = true`.
Do you have some different case?

**Comment by unnamed224** [comment]
I have more cases actually but I am using the same pom.xml. I am generating the java classes from wsdl files and they all use the same annotations.
Can you send me a working example where your pom.xml is configured to use jaxb and where you use required=true in your classes? I still can't get it to work :\

**Comment by vojtechhabarta** [comment]
I pushed example to `jaxb-sample` branch in this repo. You can try it using:
``` bash
git clone -b jaxb-sample https://github.com/vojtechhabarta/typescript-generator.git typescript-generator-jaxb-sample
cd typescript-generator-jaxb-sample
cd sample-maven
mvn install
cat target/typescript-generator/sample-maven.d.ts
```
I tried it on Java 1.8.0_112 using Maven 3.3.9.

**Comment by unnamed224** [comment]
Hi vojtechhabarta,
Sorry it took so long for me to respond, I was away for 5 days. 
This all looks okay but actually I already had this working. My problem was that every property is required no matter if it has required=true or not.
For example if I have this class 

public class Person {

    @XmlElement(name="name")
    public String name;
    @XmlElement(name="age")
    public int age;
    @XmlElement(name="hasChildren", required = true)
    public boolean hasChildren;
    

}

I would like the properties name and age to be optional. So my output would look like this 

export interface Person {
    name?: string;
    age?: number;
    hasChildren: boolean;
}

**Comment by vojtechhabarta** [comment]
Sorry, I was thinking that you meant whole property is ignored.
I think I can implement this but I am not sure if we can change current behavior without some configuration switch.

**Comment by unnamed224** [comment]
It would be great if you can implement it.. no matter if the configuration needs to be changed too. Anything is better than doing it by hand :)))
Thank you :))))

**Comment by sanja224** [comment]
Hi vojtechhabarta
Can you just tell me if you have decided to implement this or not? And if yes, how long will it take?
Great job on everything else btw :)

**Comment by vojtechhabarta** [comment]
Hi @sanja224, I plan to implement this but currently I have lot of things in the queue.
