### ISSUE TITLE
Add support for "has" prefix

### ISSUE THREAD

**Issue by jantimon** [vojtechhabarta/typescript-generator#505]
It looks like function prefixed with `has` are ignored.  
Would it be possible to allow them somehow?

```java
public class Foo { 
    public boolean hasChildren() {
        return false;
    }
}
```

Generated typings:

```ts
interface Foo {

}
```

**Comment by vojtechhabarta** [comment]
It depends on Jackson library. Typescript-generator gets list of properties from Jackson.

If you try to serialize instance of following class:
``` java
public class Foo {
    public boolean hasChildren() {
        return false;
    }
    public boolean getHasChildrenGetter() {
        return false;
    }
}
```
only second method is used: `{"hasChildrenGetter":false}`.

You need to tell Jackson what is property. You can write for example:
``` java
public class Foo {

    public boolean hasChildren = false;

    // or

    @JsonProperty
    public boolean hasChildren() {
        return false;
    }

    // or

    public boolean getHasChildren() {
        return false;
    }
}
```

In all 3 case you will get JSON/TypeScript property named `hasChildren`.

**Comment by jantimon** [comment]
thanks @vojtechhabarta for the quick response!  
it works perfectly with the solutions you described - we will go with:

```java
import com.fasterxml.jackson.annotation.JsonProperty;

public class Foo {
    @JsonProperty
    public boolean hasChildren() {
        return false;
    }
\
```
