### ISSUE TITLE
Bug with implemented interfaces

### ISSUE THREAD

**Issue by ryan10132** [vojtechhabarta/typescript-generator#51]
See https://github.com/vojtechhabarta/typescript-generator/pull/50

Interestingly, the generated `IA` interface has the x property on it, so you might think it's ok to not generate the parent interface `IB`, but it's note quite, because it's at least missing the `type` property

**Comment by vojtechhabarta** [comment]
Thanks for the test.
Closing this issues as it is duplicate of #36.
