### ISSUE TITLE
Defining custom generators in code

### ISSUE THREAD

**Issue by tstavinoha** [vojtechhabarta/typescript-generator#540]
We are trying to use a Java enum (which is already being generated into a Typescript enum) to also generate a Record object based on another property.

Java enum has two properties: an id (@JsonValue) and human-readable name.
```
public enum Language{ 

    ENGLISH("en", "English"),
    ...

    private final String code;
    private final String label;

    ...
}
```

Typescript enum is generated as expected (eg. `ENGLISH="en"`), but we also want to generate a Record for a display name, such as
```
export const LanguageToDisplayName: Record<Language, string> = {
    [Language.ENGLISH]: 'English',
    ...
```

For this purpose we have created a custom emitter extension that implements an `emitElements` method. It outputs the desired code correctly, but it is done in a pretty low-level way, with direct calls to Writer interface to output the generated code.

Are there any plans to create some sort of DSL for defining custom generators in code, in a simple and fluent manner?
Is it possible to introduce support for Typescript's Record, Exclude, Include and other utility types?

**Comment by vojtechhabarta** [comment]
This kind of feature seem to me as more like JSON data generator than TypeScript generator. For this I would suggest to create REST resource that could return such JSON but I understand that you probably want to have this data static and bundled in client application.

I don't have any plans for some DSL or template engine, I would rather keep typescript-generator simple.

What kind of support for Record and other types would you expect or suggest?

**Comment by rajesh99** [comment]
@tstavinoha
Hi,
I am not able to generate the enum as expected as you said eg. ENGLISH="en"

What optional params should be used.  Do we have to do annotate anything in Java?

**Comment by rajesh99** [comment]
Found what I required: 
https://github.com/vojtechhabarta/typescript-generator/issues/426#issuecomment-546348797
