### ISSUE TITLE
Allow non-const enums in declaration files

### ISSUE THREAD

**Issue by achimmihca** [vojtechhabarta/typescript-generator#542]
My config is
```
<mapEnum>asEnum</mapEnum>
<nonConstEnums>true</nonConstEnums>
<outputFileType>declarationFile</outputFileType>
```

I get the following error message:
`Non-const enums can only be used in implementation files but 'outputFileType' parameter is not set to 'implementationFile'`

However, in *.d.ts files it is ok to write
```
declare enum RoundingMode {
    CEILING = "CEILING",
    FLOOR = "FLOOR",
}
```
(instead of `declare const enum RoundingMode {...}` )

Thus, the typescript-generator should allow this as well.

Is there a reason why it is not allowed to mix these options?

**Comment by vojtechhabarta** [comment]
If `declare enum` is used in `d.ts` file then it means that this enum should somewhere exist in JavaScript but it doesn't and error is thrown in runtime. For example this code `console.log(RoundingMode.CEILING)` throws `ReferenceError: RoundingMode is not defined`.

**Comment by vojtechhabarta** [comment]
I just read your issue #543 so I will close this one and comment on your use case there.
