### ISSUE TITLE
Provide an option to not output enums at all

### ISSUE THREAD

**Issue by achimmihca** [vojtechhabarta/typescript-generator#543]
The parameter [mapEnum](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#mapEnum) allows to configure different styles of the generated output for enums.

I am missing an option like `none` where enum declarations are not output at all.
However, the enum classes should still be used when a type is needed.

Example:
```
public class MyClass {
    public MyEnum myEnumValue;
}

public enum MyEnum {
    Yes, No;
}
```

This should result in
```
interface MyClass {
    myEnumValue: MyEnum
}
```

Motivation:
We already have most enums written down manually (in a large old legacy code base). The auto-generated enum declaration is messing with the TypeScript Compiler. TypeScript is giving the error message: `TS2567: Enum declarations can only merge with namespace or other enum declarations.`
However, Declaration Merging with interfaces works and would be valuable for us to have.

**Comment by vojtechhabarta** [comment]
The goal of typescript-generator is to produce valid output. So it needs to generate all declarations it references.

But it is possible to explicitly map `mypackage.MyEnum` Java class to **existing** `MyEnum` TypeScript type using [customTypeMappings](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#customTypeMappings) parameter. I think this could solve your use case.
