### ISSUE TITLE
Filter types that are written to the output

### ISSUE THREAD

**Issue by achimmihca** [vojtechhabarta/typescript-generator#544]
I want to specify separately
    - the Java classes that are used to specify types in TS.
    - the Java classes that are written as interface (or enum) in the output file.

This might be a configuration issue on my side. Is there already a solution for this?
This might be more powerful solution also for #543.

For example the following should be possible:
```
public class MyCoolClass {
    public MyExistingOldClass myExistingOldClass ;
}

public class MyExistingOldClass {
    public int bla;
}
```
This should result in
```
interface MyCoolClass {
    myExistingOldClass : MyExistingOldClass 
}
```
Note that MyExistingOldClass is used as a type, but it is not declared in the file.

With this feature, it would be possible to mix existing (legacy) definitions of classes and still use some auto-generated ones.
Furthermore, it would make it possible to execute the plugin multiple times without creating redundant declarations. For example, to create multiple output files for different packages (parsing would be redundant but that does not matter as long as the output is as desired).

Motivation:
We have a complex legacy folder structure with lots of Data classes. Many of these have been ported manually to JavaScript already. These already existing classes should be used by the typescript-generator plugin when a type is needed (instead of any). But no new declaration of these should be created by the typescript-generator plugin.

**Comment by vojtechhabarta** [comment]
One solution is to use `customTypeMappings` parameter as I suggested in #543 to map `MyExistingOldClass` Java class to existing `MyExistingOldClass` TypeScript type.

There might be also another solution if you are generating _modules_. It is possible to generate one TypeScript module from some packages and then run typescript-generator again and generate another module from other packages while referencing types from the first module. This, I think, behaves exactly as you described but it only works with modules.

It is little bit harder to configure but I can help you. First you need to use `generateInfoJson` parameter which generates JSON file with list of classes in the module. Then you need to use `moduleDependencies` parameter to reference previously generated module (with its companion info JSON). Here is more detailed description: [Dependent modules](https://github.com/vojtechhabarta/typescript-generator/pull/276). You can combine more modules this way, not just two. BTW you suggested to specify list of classes that should be generated while info JSON lists classes that should NOT be generated again.

**Comment by achimmihca** [comment]
After specifying every existing class and enum definition in customTypeMappings, it is compiling now without errors.
Sadly, we are not (yet) using any module system in our webapp.

But customTypeMappings works, thanks. So I will close the issue.

**Comment by achimmihca** [comment]
No wait, I have a bonus question: is it possible to prevent empty interfaces to be generated.
In our output there are about 260 of these.
It is not doing any harm, but it is also not really necessary.

**Comment by vojtechhabarta** [comment]
Unfortunately it is not possible to exclude all empty interfaces. I just wanted to recommend you to exclude them using `excludeClasses` parameter. But 260? That's a lot. Maybe you can try to exclude them using [excludeClassPatterns](https://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#excludeClassPatterns) parameter. Or narrow input classes using different `classes...` parameters.
