### ISSUE TITLE
Duplicate Typescript attribute generation, when working with JsonTypeInfo

### ISSUE THREAD

**Issue by thamacher** [vojtechhabarta/typescript-generator#55]
Given a class with a JsonTypeInfo, which has an additional getter for the same property as shown in the following example:

> import com.fasterxml.jackson.annotation.JsonSubTypes;
> import com.fasterxml.jackson.annotation.JsonTypeInfo;
>
>@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
>@JsonSubTypes({
>  @JsonSubTypes.Type(value = ClassA.class, name = "classA")
>})
>public class InheritedClass {
>
>  public String getType() {
>    return "";
>  }
>}

then an invalid TypeScript is generated:

`interface InheritedClass {
        type?: string;
        type: string;
    }`

**Comment by vojtechhabarta** [comment]
Thanks for reporting this issue. I fixed it and now only bean property is used if there is conflict with `@JsonTypeInfo` property.

Consider also using [`EXISTING_PROPERTY`](http://fasterxml.github.io/jackson-annotations/javadoc/2.7/com/fasterxml/jackson/annotation/JsonTypeInfo.As.html#EXISTING_PROPERTY) in this case.
