### ISSUE TITLE
support custom type mapping for JsonNode

### ISSUE THREAD

**Issue by cameronbraid** [vojtechhabarta/typescript-generator#553]
I see that JsonNode is excluded https://github.com/vojtechhabarta/typescript-generator/issues/289 and will map to `any`

I want to use my own JsonValue type like this :

json.ts
```
export type JsonValue = null | string | number | boolean | JsonObject | JsonArray
export type JsonObject = { [key: string]: JsonValue }
export interface JsonArray extends Array<JsonValue> {}
```

I would like to map the JsonNode java type like the following :

```
settings.importDeclarations = List.of("import { JsonValue } from 'src/json';");

settings.customTypeNamingFunctionImpl = (fullName, shortName) -> {

      if ("com.fasterxml.jackson.databind.JsonNode".equals(fullName)) {
        return "JsonValue";
      }
      ...
}
```

but it always comes back as `any`

**Comment by cameronbraid** [comment]
Sorry, just discovered that I can use
```
    settings.customTypeMappings = Map.of(
      "com.fasterxml.jackson.databind.JsonNode", "JsonValue"
    );
```

**Comment by vojtechhabarta** [comment]
Yes, similarly named `customTypeNamingFunctionImpl` is for naming generated interfaces for specified classes. In your case no interface should be generated for `JsonNode` class. It just need to be mapped to some existing type.
