### ISSUE TITLE
JAXB generated typescript properties with lowercase

### ISSUE THREAD

**Issue by landal79** [vojtechhabarta/typescript-generator#555]
Hi,

I'm generating typescript interfaces from jaxb generated classes, with the following configuration:

```
<plugin>
	<groupId>cz.habarta.typescript-generator</groupId>
	<artifactId>typescript-generator-maven-plugin</artifactId>
	<executions>
		<execution>
			<id>generate</id>
			<goals>
				<goal>generate</goal>
			</goals>
			<phase>process-classes</phase>
		</execution>
	</executions>
	<configuration>
		<jsonLibrary>jaxb</jsonLibrary>
		<classPatterns>io.module.classes.*</classPatterns>					
		<outputKind>module</outputKind>
		<optionalProperties>useLibraryDefinition</optionalProperties>
		<outputFile>src/main/web/src/app/model/model.d.ts</outputFile>
	</configuration>
</plugin>
```

In the generated classes I have something like this:
```
public class Outer {

    private String element1;
    private String element2;
    @XmlElement(name = "Inner", required = true)
    private Inner inner;

}
```
The xml schema has an uppercase `Inner` element.

The generated typescript interface is:
```
export interface Outer {
    element1: string;
    element2: string;    
    Inner : Inner;
}
```

Is it possible to generate lowercase properties instead of uppercase one (as per typescript style guide), even if the @XmlElement annotation has the name value uppercase?

**Comment by vojtechhabarta** [comment]
Hi,

one thing is code style but the goal is to describe real data. When I serialize `Outer` class using following code:
``` java
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.registerModule(new JaxbAnnotationModule());
Outer outer = new Outer();
outer.inner = new Inner();
System.out.println(objectMapper.writeValueAsString(outer));
```
resulting JSON contains uppercase `Inner` for example like this:
``` json
{"Inner":{"s":"a"}}
```

Does your JSON really contain lowercase `inner` element or do you have other reason to generate it in such form?

**Comment by landal79** [comment]
Hi,

Thank you for the answer, 
Your suggestion fixed the problem.
