### ISSUE TITLE
Java class name readonly property on generated TS class

### ISSUE THREAD

**Issue by Matthewloughton** [vojtechhabarta/typescript-generator#558]
First off, this library was a massive timesaver for me not having to roll my own - thank you! 

We have a requirement where we need to generate an attribute on all of our ts models which contains the java class name - preferably canonical name. 

I really tried to implement this but have hit a dead-end. Can you send me in the right direction?

**Comment by vojtechhabarta** [comment]
I don't know what you mean by attribute? Could you please provide some example what you want to achieve?

**Comment by Matthewloughton** [comment]
Sorry, bad wording. Let me explain by example:

``` java
public class Animal{
     private int age;
}

```
Becomes:

``` js
export class Animal{
     age: number
     readonly class?: string = 'com.mycompany.Animal'
}

```
or with simple name

``` js
export class Animal{
     age: number
     readonly class?: string = 'Animal'
}
```

**Comment by vojtechhabarta** [comment]
Thanks for the examples.
Unfortunately this is not supported. That would be case for some extension.
There is support for discriminated unions (#81) for Jackson classes which can generate discriminant property with specified name or class name but it is not probably what you need.

**Comment by Matthewloughton** [comment]
Ok cool no problem - thanks for your time.

I'll write my own generator from the ground up.
