### ISSUE TITLE
Emitting a readonly field

### ISSUE THREAD

**Issue by lpandzic** [vojtechhabarta/typescript-generator#559]
For a class Foo
```
class Foo {
private final FooType type = FooType.FOO;
}
```
is it possible to generate typescript that contains:
```
export class Foo {
readonly type = FooType.FOO;
}
```
? 
I've tried to create such an expression using TsPropertyModel but was unable to do so.
The furthest I got is `readonly type: FooType`.

**Comment by vojtechhabarta** [comment]
Currently it is not possible to generate property with initializer.
Do you think it would be sufficient to add `initializer` field of type `TsExpression` to `TsPropertyModel` class?

**Comment by lpandzic** [comment]
I believe main obstacle is actually [this line](https://github.com/vojtechhabarta/typescript-generator/blob/357c5668eb1fe41b8e12d780092c86db22731242/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/emitter/Emitter.java#L207):
```
writeIndentedLine(staticString + readonlyString + quoteIfNeeded(property.getName(), settings) + questionMark + ": " + tsType.format(settings) + ";");
```
The problem is that `:` is emitted for every `TsPropertyModel`. This needs to be overridable or modeled differently altogether.

**Comment by lpandzic** [comment]
If adding `initializer` will also take care of `:` then yes, I'd say it's sufficient.

**Comment by vojtechhabarta** [comment]
I think there could be also type (after `:`). It should be know when generating this property. Like this:
``` typescript
export class Foo {
    readonly type: string = FooType.FOO;
}
```
But yes, when adding initializer to `TsPropertyModel` it could be changed to expect at least one of them (type or initializer).

**Comment by lpandzic** [comment]
Yes, you are right! 
With that fact in mind, nothing actually has to change in typescript-generator as this use case can be achieved with something as simple as (and appropriate extension that uses it):
```
@Value
public class EnumInitializerType<E extends Enum<E>> extends TsType {

    private final Class<E> type;
    private final E value;

    @Override
    public java.lang.String format(Settings settings) {
        var enumName = type.getSimpleName();
        return enumName + " = " + enumName + '.' + value ;
    }
}
```
