### ISSUE TITLE
Lombok `NonNull` annotation can't be used in requiredAnnotations

### ISSUE THREAD

**Issue by APshenkin** [vojtechhabarta/typescript-generator#561]
Lombok `NonNull` annotation can't be used in `requiredAnnotations`:
```
requiredAnnotations = [
            'lombok.NonNull',
            'javax.validation.constraints.NotNull'
    ]
```

```
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MyClass {

    @NonNull
    private String myString;

    private Boolean myBoolean;
}
```

produce
```
export class CreateWarmKey {
    myString?: string;
    myBoolean?: boolean;
}
```

**Comment by vojtechhabarta** [comment]
I think `lombok.NonNull` annotation doesn't work because it has retention set to `CLASS`.
Such annotations are not accessible using reflections in runtime.
It would require to use some other technology to read this annotation.

**Comment by FlorianCassayre** [comment]
...so? Does that mean there is no support for Lombok's `@NonNull`? This is a requirement for us, and if that's the case then we cannot use this library.
