### ISSUE TITLE
Please support Custom mappings for @JsonSerialize when using contentsUsing

### ISSUE THREAD

**Issue by cameronbraid** [vojtechhabarta/typescript-generator#564]
Support `serializerTypeMappings` / `deserializerTypeMappings` when using `@JsonSerialize(contentUsing = XSerializer.class)`

For example

Java Model
```
@JsonSerialize(contentUsing = XSerializer.class)
@JsonDeserialize(contentUsing = XDeserializer.class)
public List<X> param;
```

Config :
```
Jackson2Configuration c = new Jackson2Configuration();
c.serializerTypeMappings = List.of(
  "XSerializer:string"
);
c.deserializerTypeMappings = List.of(
  "XDeserializer:string"
);
s.setJackson2Configuration(getClass().getClassLoader(), c);
```

produces typescript
```
param: any[];
```

I would expect

```
param: string[];
```

**Comment by cameronbraid** [comment]
FYI I have this working when using `@JsonSerialize(using = XSerializer.class)` but not when using the `contentUsing` variant

**Comment by vojtechhabarta** [comment]
There is support for `@JsonSerialize(contentUsing)`, here is a [test](https://github.com/vojtechhabarta/typescript-generator/blob/13fa08394b5837830669b6f957c9b1015fbac4f0/typescript-generator-core/src/test/java/cz/habarta/typescript/generator/Jackson2ParserTest.java#L462).
I cannot see why your case is not working, so I have just few hints:
- compare your case with mentioned test
- verify your `List` is `java.util.List`
- verify your real configuration contains package of `XSerializer` and `XDeserializer`
- check if you are using latest version of typescript-generator

**Comment by cameronbraid** [comment]
@vojtechhabarta Thanks - I figured it out, the X class was being matched by settings.excludeFilter, removing it from there solved the issue.
