### ISSUE TITLE
excludePropertyAnnotations not respected when using gson

### ISSUE THREAD

**Issue by robin-xyzt-ai** [vojtechhabarta/typescript-generator#569]
Problem can be reproduced with the `IncludeExcludePropertyTest` if you replace
```
final Settings settings = TestUtils.settings();
```
with
```
final Settings settings = TestUtils.settings();
settings.jsonLibrary = gson;
```

**Comment by vojtechhabarta** [comment]
Released in [v2.27.744](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.27.744).
