### ISSUE TITLE
Q: how to export methods for manager classes?

### ISSUE THREAD

**Issue by oerlenkaemper** [vojtechhabarta/typescript-generator#575]
Hi,

I'm struggeling to create ts interface definitions for one of my manager classes. While the types are correctly exported, the manager methods seem to not be considered at all or modified.

_Simplified example:_

`
public class Manager
{
	private final long		startTime	= RandomUtils.currentTimeMillis();
	private final String	username;
	private ArrayList		list;

	public Manager()
	{
		this.username = "myUser";
	}

	public String getUsername()
	{
		return username;
	}

	public long getStartTime()
	{
		return startTime;
	}

	public UUID newUUID()
	{
		return UUID.randomUUID();
	}

	public List getOrCreateList()
	{
		if (this.list == null)
		{
			this.list = new ArrayList<>();
		}
		return this.list;
	}

}
`

is actually translated to

`export interface Manager {
    orCreateList: any[];
    startTime: number;
    username: string;
}`

However, there are some deviations between the two representations I really would like to remove:

1. the method **getOrCreateList** is translated to **orCreateList**, the "get" seems to be stripped away
2. the **newUUID** method is completely missing

As the manager is injected into a JS engine those (gateway) methods are inevitable for proper JS integration into the JAVA spring backend.

I played a lot with the settings, the extensions, and the different json libs, but I had no success. Am I doing something wrong?
Any help would be appreciated! :)

Thanks in advance!
Oliver

Maven Configuration:
<groupId>cz.habarta.typescript-generator</groupId>
<artifactId>typescript-generator-maven-plugin</artifactId>
<version>2.26.723</version>
<jsonLibrary>jackson2</jsonLibrary>
<outputKind>module</outputKind>
<mapClasses>asInterfaces</mapClasses>
<outputFileType>declarationFile</outputFileType>

**Comment by vojtechhabarta** [comment]
Hi,
the goal of typescript-generator is to describe JSON data. In this case it is data processed by Jackson2 library. So if we try to serialize instance of Manager class for example using `new ObjectMapper().writeValueAsString(new Manager())` Jackson produces JSON data for which typescript-generator produces declarations.

That's core use case of typescript-generator but it is also possible to generate REST client. If you have for example some Spring controllers it is possible to generate TypeScript code that calls this API using HTTP requests.

In general it is not possible to call Java code running on server directly from TypeScript code running on client. Thanks why typescript-generator expects processed classes to be serialized or deserialized by JSON library (Jackson in this case).

**Comment by oerlenkaemper** [comment]
Thanks for your quick reply. I'm actually running JS code in a GraalVM on the server. The VM allows me to inject a Java context object which again can be called by the JS script. For the development I thus wanted to provide TS interface descriptions for the Java context so that any developer can directly code against it before the TS code is compiled to JS code (to run in the cloud VM).

Thanks also for the explaination with Jackson which makes totally sense, unfortunately. I will try to give the REST client a shot, maybe this one can help me to create some stub-ish TS code which I can then manually polish to match the context.

Nevertheless, thanks for this great tool and the support! :)

**Comment by vojtechhabarta** [comment]
I see, this is different use case which is not specifically supported by typescript-generator. I would rather leave this to GraalVM community, they know better how objects and types are made interoperable between Java and JavaScript/TypeScript (despite the fact that "typescript-generator" name could give impression that it can generate anything 😏).

Anyway, thanks for your interest in typescript-generator and sharing your use case.
