### ISSUE TITLE
Use Lombok `Builder.Default` parameters

### ISSUE THREAD

**Issue by wdroste** [vojtechhabarta/typescript-generator#578]
As part of the translation from jackson/lombok to typescript, is working well, though one part we continue to do manually is translate the default values we have in our DTO objects to the corresponding TypeScript objects. The use case here is pretty simple we want to create a client side object that will be used to fill-in a form, the defaults we'd like to come from the Typescript object which have the corresponding values set. This would greatly reduce any manually prone errors and keep the objects in sync.

Example:

```
@Value
@Builder(toBuilder = true)
@JsonDeserialize(builder = MyObj.MyObjBuilder.class)
public class MyObj {
  @Default
  int x = 2;
 
  @Default
  long y = 4L;

  String description;
  String expression;
  @JsonPOJOBuilder(withPrefix = "")
  public static final class MyObjBuilder {
  }
}

```

So based on my research you can't get to a default field in Java.. but if its generated by Lomok which ours are.. there's private methods generated for each default field of the following pattern.

```
  private static int $default$x() {
    return 2;
  }
```

So that leaves how to generate the Typescript file w/ default values, based on this StackOverflow article.. I see two basic options for interface and class.
https://stackoverflow.com/questions/35074365/typescript-interface-default-values

Having the extra interface or just generating a constructor with the values set would be awesome. Any direction on how I could make a PR for this would be helpful.

**Comment by vojtechhabarta** [comment]
In 18840db24db8a1e7276c55919b307bbfef2af2d6 I did some improvements to core module and implemented example extension [DefaultsFromInstanceExtension](https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/ext/DefaultsFromInstanceExtension.java) which generates TypeScript classes with default property values. It creates instance of Java class and gets default values from it. So for example for following Java class:
``` java
public class A {
    public String text = "hello";
    public long number = 42L;
}
```
this extension will generate following TypeScript class:
``` typescript
class A {
    text: string = 'hello';
    number: number = 42;
}
```

I am not sure if generating classes with defaults is what you need but I think it could be used. It should be now possible to create similar extension which would get default values from different source. If you would like to create your extension you can submit it in PR. But I really don't want to add new compile dependencies so if your extension requires for example dependency on Lombok you could implement it outside typescript-generator or you could have your own fork of typescript-generator.

**Comment by vojtechhabarta** [comment]
Released in [v2.28.785](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.28.785).

**Comment by wdroste** [comment]
@vojtechhabarta ty this appears to be just what i need.

**Comment by wdroste** [comment]
Basic extension 
https://gist.github.com/wdroste/8ec44d4baa599cf24a5dc4e0d6fce203

**Comment by vojtechhabarta** [comment]
@wdroste thanks for sharing your extension

**Comment by dcrousset** [comment]
@vojtechhabarta [DefaultsFromInstanceExtension](https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/ext/DefaultsFromInstanceExtension.java) is awesome !!! thank you very much
