### ISSUE TITLE
Change generated file comment only, when content within file has changed

### ISSUE THREAD

**Issue by thamacher** [vojtechhabarta/typescript-generator#59]
As we included the typescript-generator during our build-phase in grade, the file comment always changes, which results into a change of the generated file and thus the file shows up in the next commit, although nothing else has changed.

I'd rather see an option to add this file comment only, when the content has changed - otherwise leave the comment as it was.

**Comment by vojtechhabarta** [comment]
There is `noFileComment` option for use cases where generated file is committed.

**Comment by thamacher** [comment]
yes. I used that one. But this removes this comment completely. I would rather prefer to see the latest changes.
