### ISSUE TITLE
Mark non-final class members as nullable

### ISSUE THREAD

**Issue by xprt64** [vojtechhabarta/typescript-generator#598]
Is there any possibility to mark the non-final class members as nullable? 

For example, to provide a custom TypeProcessor or extension?

**Comment by vojtechhabarta** [comment]
Marking properties as nullable based on whether the member is final or not is not possible using core functionality but it should be possible to create an extension for it.

By the way are you aware of possibility to use annotations to specify nullability ([nullableAnnotations](https://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#nullableAnnotations))?

**Comment by xprt64** [comment]
> By the way are you aware of possibility to use annotations to specify nullability

Yes, I'm aware, but I don't want to modify the Pojos. 

Thank for your reply!
