### ISSUE TITLE
Custom type mapping

### ISSUE THREAD

**Issue by vojtechhabarta** [vojtechhabarta/typescript-generator#60]
This is continuation of #56 with some changes:
- in addition to referenced files also add possibility to `import` modules with types
- add test

Settings will be:
- `customTypeMappings` - specifies mapping from Java class to TypeScript type
- `referencedFiles` - list of references files
- `importDeclarations` - list of import declarations

**Comment by vojtechhabarta** [comment]
@thamacher this should solve your issues #45, #46, #47. Can you close those issues if custom type mapping meets your needs?

**Comment by thamacher** [comment]
Yes, definately! 

I will do it! 

Thanks! 

Am 28.04.2016 12:06,
schrieb Vojtěch Habarta: 

> @thamacher [1] this should solve your
issues #45 [2], #46 [3], #47 [4]. Can you close those issues if custom
type mapping meets your needs? 
> 
> --
> You are receiving this because
you were mentioned.
> Reply to this email directly or view it on GitHub
[5]

 

Links:
------
[1] https://github.com/thamacher
[2]
https://github.com/vojtechhabarta/typescript-generator/issues/45
[3]
https://github.com/vojtechhabarta/typescript-generator/issues/46
[4]
https://github.com/vojtechhabarta/typescript-generator/issues/47
[5]
https://github.com/vojtechhabarta/typescript-generator/issues/60#issuecomment-215375777
