### ISSUE TITLE
Constructors with Partials

### ISSUE THREAD

**Issue by UsernameIsReallyNotAlreadyTaken** [vojtechhabarta/typescript-generator#614]
I personally like the following concise pattern for a constructor, where you avoid assigning properties individually and are not forced to provide values.

```
export class A {

    prop1: number;
    prop2: string[];
    ...

    constructor(o: Partial<A> = null) {
        Object.assign(this, o);
    }

}
```

This way all properties are still not optional but you can construct an instance with only a subset of properties. 

Also the assignment is nullsafe, so the instance can be constructed without a value at all. 

Background is here that I want to use this in conjunction with class-transformer which requires objects to be instantiated naked and later be populated while from within the business logic I often want to construct parameter objects using the partial Options pattern. 

Is it possible to introduce this pattern?

Best regards

**Comment by vojtechhabarta** [comment]
Hello,

currently it is possible to generate following constructor using `generateConstructors` parameter:
``` typescript
class FooBar {
    foo?: string;
    bar: number;

    constructor(data: FooBar) {
        this.foo = data.foo;
        this.bar = data.bar;
    }
}
```

This allows to pass just required properties with any combination of optional fields:
``` typescript
new FooBar({bar: 42})
```

For creating "naked" instance it is possible to use:
``` typescript
Object.create(FooBar.prototype)
```
which doesn't call constructor.

Is this suitable for you?

**Comment by UsernameIsReallyNotAlreadyTaken** [comment]
Thanks for the quick response and an awesomly adaptable plugin. 

The problem is that the constructor is called (by class-transformer) with no data which gives an error dereferencing data. It must be possible to provide no data. To be more precise the constructors are mainly needed not for data returned by services but for data sent as params to services. my proposed pattern with Partials is just a general approach which always worked in my usecases so far.

```
       constructor(data: FooBar) {
              this.foo = data.foo; // data might be undefined 
       }
```

I guess you also provided the extensions mechanism for exactly these kinds of requirements. I tried implement my idea with an extension inspired by RequiredPropertyConstructorExtension. Here is a first hacky sketch which does appromimately what I what, I still have to find out how to construct those TsExpressions more robustly:

```
private static Optional<TsConstructorModel> createConstructor(TsBeanModel bean, TsModel model,
			Map<String, TsConstructorModel> generatedConstructors)
	{
		List<TsStatement> body = new ArrayList<>();
		List<TsParameterModel> parameters = new ArrayList<>();

		String simpleName = bean.getName().getSimpleName();
		String typeParams = "";
		if (!bean.getTypeParameters().isEmpty())
		{
			typeParams = "<" + bean.getTypeParameters().stream().map(v -> v.name).collect(Collectors.joining(",")) + ">";
		}
		TsParameterModel tsParameterModel = new TsParameterModel("o", new BasicType("Partial<" + simpleName + typeParams + "> = null"));

		parameters.add(tsParameterModel);
		if (bean.getParent() != null)
		{
			body.add(new TsExpressionStatement(new TsCallExpression(new TsSuperExpression())));
		}
		body.add(new TsExpressionStatement(new TsIdentifierReference("Object.assign(this, o)")));

		TsConstructorModel constructor = new TsConstructorModel(TsModifierFlags.None, parameters, body, null);

		new TsConstructorModel(TsModifierFlags.None, parameters, body, null);
		return Optional.of(constructor);
	}

```

**Comment by vojtechhabarta** [comment]
I realized that your example class `A` is not compilable using TypeScript compiler with `strict` flag. If you are not using `strict` mode you could use `generateConstructors` parameter and then it should be possible to create an extension which would just insert condition if `data` was passed to constructor and skip constructor execution if it wasn't. Example:
``` typescript
class FooBar {
    foo?: string;
    bar: number;

    constructor(data: FooBar) {
        if (!data) {  // inserted by a new extension
            return;
        }
        this.foo = data.foo;
        this.bar = data.bar;
    }
}
```

**Comment by UsernameIsReallyNotAlreadyTaken** [comment]
Thank you very much!
