### ISSUE TITLE
Custom decorators

### ISSUE THREAD

**Issue by UsernameIsReallyNotAlreadyTaken** [vojtechhabarta/typescript-generator#615]
Is it possible somehow to add custom sourcecode - for instance decorators like @Injectable() in front of the API-Client-implementations? 

If not, would you consider adding this feature?

The mechanism may similar to the one by which we are able to add imports. 

Or is there a mechanisms to introduce decorators for certain attributes like they are for instance expected by the class-transformer library?

Thank you very much for any ideas.

**Comment by vojtechhabarta** [comment]
Typescript-generator doesn't have any transformation of Java annotations to TypeScript decorators. But it has support for decorators in model and emitter so it is possible to write some extension which produces decorators.

For example see [ClassNameDecoratorExtension](https://github.com/vojtechhabarta/typescript-generator/blob/44741e6164741a64eb20bc0d20ea1190164fc893/typescript-generator-core/src/test/java/cz/habarta/typescript/generator/DecoratorsTest.java#L37).

**Comment by UsernameIsReallyNotAlreadyTaken** [comment]
Thanks a lot. That is exactly what I needed.

**Comment by UsernameIsReallyNotAlreadyTaken** [comment]
I would conclude that it would be nice if TsParameterModel was able to define decorators similar to what TsBeanModel does.

**Comment by vojtechhabarta** [comment]
I added support for decorators in `TsParameterModel` and `TsMethodModel`.

**Comment by UsernameIsReallyNotAlreadyTaken** [comment]
Thanks you very much.

**Comment by vojtechhabarta** [comment]
Released in [2.29.814](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.29.814).
