### ISSUE TITLE
Config doubt

### ISSUE THREAD

**Issue by panxiaohong** [vojtechhabarta/typescript-generator#616]
Hi
 Thank you very much for provide this project. It is so good.  There is a small doubt. Can I generate SuperClass  and Interfaces to single file and auto import dependencies.

**Comment by vojtechhabarta** [comment]
Hi, typescript-generator produces one TypeScript file (either `.d.ts` or `.ts`) with all needed superclasses and interfaces.
I am not sure if that answers your question.
