### ISSUE TITLE
Using typescript-generator without GPL 1

### ISSUE THREAD

**Issue by Herr-Sepp** [vojtechhabarta/typescript-generator#628]
Hi, is it possible to use the typescript-generator without its dependency to [com.sun.xml.bind:jaxb-impl:jar:2.3.1 ](https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-impl/2.3.1) ?

Because it brings the GPL 1.1 license with it.
I dont need support for the old JAXB, is there a way to build / use Typescript-generator without it? Or only using [com.sun.xml.bind:jaxb-impl:jar:3.0.0](https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-impl/3.0.0) what also dont have the GPL license anymore.

Sorry if this is a stupid question. I have no experience in the area and thanks for your great software.

**Comment by vojtechhabarta** [comment]
Hi, it is not possible to build typescript-generator without JAXB. At least dependency on JAXB annotations should be present (moreover it is in some Jackson and Jersey dependencies transitively).

JAXB is also used internally in typescript-generator to load Javadoc comments from XML files. I checked if it would be possible to upgrade JAXB dependency to 3.0.0 but there is no update for JAXB plugin https://github.com/highsource/maven-jaxb2-plugin/issues/199 yet.

But main problem with JAXB 3 is that annotations were moved from `javax.xml.bind.annotation` package to `jakarta.xml.bind.annotation` so even if there is updated JAXB plugin it will still be needed to have dependency to JAXB 2 annotations to support present user code.

However I realized that there is newer version of JAXB (2.3.2) which has different license than 2.3.1. So I updated JAXB version and changed `javax.xml.bind:jaxb-api` dependency to `jakarta.xml.bind:jakarta.xml.bind-api`, see #629. Maybe this could solve your issue, what do you think?

**Comment by Herr-Sepp** [comment]
Yes thank you very much, that solved my problem.
I never expected such a quick solution.

Thanks a million

**Comment by vojtechhabarta** [comment]
PR: #629, released in [2.29.814](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.29.814).

**Comment by vojtechhabarta** [comment]
@Herr-Sepp just a heads up: in order to support both JAXB 2 and JAXB 3 in [v2.34.976](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.34.976) it was needed to change dependencies (8b7ef48f5d8462be1cecd7eb4bc8941e61bbb893). Hopefully it is acceptable for you.
