### ISSUE TITLE
Generics aren't properly exported/utilized when using jsonInfo functionality

### ISSUE THREAD

**Issue by antch** [vojtechhabarta/typescript-generator#631]
I am currently trying to split my configuration into multiple executions using the `jsonInfo` functionality, but it doesn't seem to handle generics properly.

For example, let's say I have the following Java classes:

```
class MyModel<T> {}

class MyClass<T> {
  MyModel<T> model;
}

class AnotherClass<T> {
 MyModel<T> model;
}
```

Now let's assume the first plugin execution has the following Maven config:
```
<outputFile>${project.build.directory}/ts/first.ts</outputFile>
<classes>
  <class>com.mypackage.MyClass</class>
</classes>
<infoJson>true</infoJson>
```

The second execution has this config:
```
<outputFile>${project.build.directory}/ts/second.ts</outputFile>
<classes>
  <class>com.mypackage.AnotherClass</class>
</classes>
<moduleDependencies>
  <moduleDependency>
    <importFrom>./first</importFrom>
    <importAs>first</importAs>
    <infoJson>${project.build.directory}/ts/typescript-generator-info.json</infoJson>
  </moduleDependency>
</moduleDependencies>
```

In this case, `first.ts` will properly generate `MyClass`, like:

```
export interface MyClass<any> {
  model: MyModel<any>;
}
```

However, `second.ts` doesn't get the generics carried over:

```
export interface AnotherClass<any> {
  model: first.MyModel;
}
```

Because of this the TS (3.9) complilation fails.

**Comment by vojtechhabarta** [comment]
That's strange, I tried your example classes in [ModuleDependenciesTest](https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-core/src/test/java/cz/habarta/typescript/generator/ModuleDependenciesTest.java) and it produced `a.d.ts` with:
``` typescript
export interface MyClass<T> {
    model: MyModel<T>;
}
export interface MyModel<T> {
}
```
and `b.d.ts` with:
``` typescript
export interface AnotherClass<T> {
    model: a.MyModel<T>;
}
```
which I think is correct.
First suspicious think is that in your case there is `any` as generic parameter.
Could you try to narrow the problem? For example using mentioned unit test?

**Comment by antch** [comment]
Yes, I will recreate with a unit test. I was taking the concepts from my large project and trying to produce an example based on that, but I clearly missed something.

**Comment by antch** [comment]
After being unable to reproduce this in a sandbox, I un-stashed the stuff I was working on and everything seems to be working as it should (though the `<any>` is still there throughout). I'm going to close this -- if I have to re-open I will make sure to include a reproduction.
