### ISSUE TITLE
Annotation Based generator

### ISSUE THREAD

**Issue by ArtemZip** [vojtechhabarta/typescript-generator#637]
Hi, 

What about to use annotation processing for this ? It can reduce mvn/gradle configuration and be more clear by adding only dependencies.

**Comment by vojtechhabarta** [comment]
Hi, using annotation processing would mean to change this tool from the ground. Current solution using runtime reflection has advantage of using implementations from JSON and REST libraries so it is easier to achieve behavior close to those libraries thus providing more accurate declarations.

**Comment by lpandzic** [comment]
> Hi, using annotation processing would mean to change this tool from the ground. Current solution using runtime reflection has advantage of using implementations from JSON and REST libraries so it is easier to achieve behavior close to those libraries thus providing more accurate declarations.

Not necessarily, [I've created a project that leverages this one](https://github.com/infobip/infobip-typescript-generator-extension) and provides annotation processor support, among other things.

**Comment by vojtechhabarta** [comment]
@lpandzic thanks for sharing your usage of typescript-generator and annotation processor. I was wondering how you are invoking Jackson from annotation processor and then I found that

> model classes and generator configuration have to be compiled before annotation processor is run

So if I understand it correctly annotation processor is used only for invocation but runtime reflection is still used for processing (of pre-compiled classes). That's significant complication for build configuration but great to hear that it works in your case.

**Comment by lpandzic** [comment]
Yes, it's just a thin wrapper around typescript generator. Annotation processor in general is just a side feature of that project with more focus being on bean validation translation.
I agree it's a significant complication but rewriting whole typescript generator is not trivial.
