### ISSUE TITLE
No way to output a nullable type in Kotlin as an optional

### ISSUE THREAD

**Issue by Idane** [vojtechhabarta/typescript-generator#648]
My goal here is to be able to convert from:

```kotlin
class Example(
        var nullableString: String?,
        var nonNullableString: String
)
```
to 
```typescript
export interface Example(
        nullableString?: string;
        nonNullableString: string;
)
```

In practice, what I actually get is:
```typescript
export interface Example {
        nullableString: string | null;
        nonNullableString: string;
}
```

Per #419 this should be possible unless I've read it wrong.

**Comment by vojtechhabarta** [comment]
I think you need to set `nullabilityDefinition` parameter to `undefinedInlineUnion`. The trick is that if resulting type of the property is  union which contains `undefined` the property is changed to optional. (You can also try other [values](https://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#nullabilityDefinition).)

**Comment by Idane** [comment]
`nullabilityDefinition ` to `undefinedInlineUnion` did the trick, thank you!
