### ISSUE TITLE
Generate typescript enum instead of a type

### ISSUE THREAD

**Issue by dparish** [vojtechhabarta/typescript-generator#65]
Given this java class:

public enum Test {
    ONE,TWO,THREE
}

I'm getting this ts:

export type Test = "ONE" | "TWO" | "THREE";

I would have expected:

enum Test {
  ONE, TWO, THREE
}

**Comment by vojtechhabarta** [comment]
TypeScript enums are number based so `Test.ONE = 0`, `Test.TWO = 1`, `Test.THREE = 2`.

However Java enum values are sent as string values in JSON (`Test.ONE = "ONE"`, `Test.TWO = "TWO"`, `Test.THREE = "THREE"`).

So `type Test = "ONE" | "TWO" | "THREE"` means that value is of type string and can be "ONE" or "TWO" or "THREE" which exactly describes data in JSON.

**Comment by dparish** [comment]
UGGG. I should have put that together.  You're right of course.  I don't get quite the code I want but my contract with my server is still correct. I bet there's a custom way for me to handle this but not in a way that a tool like this could easily abstract.

I appreciate the tool by the way. It's been very useful.
