### ISSUE TITLE
Map primitive types to a custom type (e.g.: long to BigInt)

### ISSUE THREAD

**Issue by nanella** [vojtechhabarta/typescript-generator#650]
Hi,
thanks for your awesome library. I've found only one case where I can't find a solution:

The Java API returns a `long`, which gets represented as a `number` in typescript per default. Sadly, a `number` is not enough in this case and I would like to map the type to `BigInt`. This works seamlessly with the class `Long`, but I can't get it to work with the primitive type. 

Is there any way to configure this? If not, could this be implemented in some way?

**Comment by vojtechhabarta** [comment]
Hi, you are right, mapping `Java` long to TypeScript `BigInt` is not currently possible but it should be possible.
Just for curiosity: how are you parsing numbers in JSON into BigInt?

**Comment by nanella** [comment]
Since I'm using axios, I'm planning on using `transformResponse` in combination with a `BigInt` JSON library to parse the json `long`s to `BigInt`. (For a simpler usecase, I could also convert the `long` to string in the same way if I would be able to map the `long` to `string` in the generator configuration.)

**Comment by krotim** [comment]
I have the same problem, I did fix it with converting to string, but I am interested do you plan on fixing this soon?

**Comment by vojtechhabarta** [comment]
There was already support for custom mapping of _arrays_ of primitive types (done in #636) so I just made it work also for this case.

**Comment by vojtechhabarta** [comment]
Released in [v2.32.889](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.32.889).
