### ISSUE TITLE
Handling `DateAsString` type with infoJson

### ISSUE THREAD

**Issue by antch** [vojtechhabarta/typescript-generator#658]
I think this is a bug, but perhaps there's a workaround that I'm not thinking of.

Previously I was generating one huge definitions file, but have since split it into multiple executions (using the infoJson functionality) and then exporting from a barrel file like so:

```
export * from './generated/moduleA';
export * from './generated/moduleB';
```

If I set the option `mapDate` to `DateAsString` for both of the executions both files are exporting definitions for `DateAsString` which causes a TypeScript error: `'./generated/moduleA' has already exported a member named 'DateAsString'. Consider explicitly re-exporting to resolve the ambiguity.`.

If I hand-modify the type definition in `moduleB.ts`, everything works properly:
`type DateAsString = moduleA.DateAsString;`

Is there any way for moduleA to export the definition for `DateAsString`, and moduleB to use that type, in this case? Or perhaps another workaround?

**Comment by antch** [comment]
I was able to work around this by defining the type in my barrel file and then setting up a `customTypeMapping` and `importDeclaration`:

```
<customTypeMappings>
  <customTypeMapping>java.util.Date:DateAsString</customTypeMapping>
</customTypeMappings>
<importDeclarations>
  <declaration>import { DateAsString } from '../barrel'</declaration>
</importDeclarations>
```

Would that be the recommended way to work around the issue?

**Comment by vojtechhabarta** [comment]
Sorry for late response.

This feature is intended not only for providing reusability of common types but it also provides separate "namespaces" for declarations. So combining generated modules can cause even more name conflicts than what you solved.

So my recommendation would be to not reexport those modules in barrel. Or maybe you could name those exports like this:
``` typescript
import * as moduleA from './generated/moduleA';
export { moduleA };
```
but I understand that this would require changing all client code.
