### ISSUE TITLE
Support "cross-compilation" with gradle toolchains

### ISSUE THREAD

**Issue by JamesGuthrie** [vojtechhabarta/typescript-generator#659]
Since 6.7, gradle has offered [toolchains](https://docs.gradle.org/current/userguide/toolchains.html). These allow gradle to automatically fetch and use a different JVM for task execution than it is using to run on itself. This can be used to "cross-compile" java sources using the jdk 16 compiler while only having a system jdk of 11 installed.

The `typescript-generator-gradle-plugin` does not work with gradle toolchains when the version of the system JVM is lower than the target JVM as configured using gradle toolchains. My understanding for this is that the plugin runs in the same context as gradle, which runs on the system JVM. The classes which it attempts to load were compiled with a more recent JVM, so cannot be interpreted by the older JVM, failing with the following exception: 

```
Caused by: java.lang.UnsupportedClassVersionError: SomeClass has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 58.0
```

It is possible for plugin authors to [add support for toolchains](https://docs.gradle.org/current/userguide/toolchains.html#sec:plugins)

**Comment by vojtechhabarta** [comment]
Currently `typescript-generator-gradle-plugin` supports Gradle versions from 4.0. It seems to me that to support Gradle toolchains we would need to use classes that were added in mentioned version 6.7 thus end support for Gradle versions 4, 5, 6.x.

**Comment by vojtechhabarta** [comment]
I will close this issue for now because I don't know how to implement this feature without loosing compatibility with older Gradle versions.

**Comment by danielkaneider** [comment]
We also see an increased benefit of using Gradle toolchains. Before you had to change the running Java version (eg. by changing ENV setting, or specifying an absolute Java binary path), now you can compile using a Java version which doesn't need to be installed on your machine. 
This makes it easier for local development, as different projects/libraries could require different Java versions, as well as CI, were it also happens, that different target versions are required.
Would you accept contributions for supporting toolchains? It will likely mean, that older Gradle versions (< Oct 2020) would not be supported any more. But IMO people can always stick to a TS generator version supporting this.
