### ISSUE TITLE
Enums and Jackson.

### ISSUE THREAD

**Issue by IRus** [vojtechhabarta/typescript-generator#66]
```java
@JsonFormat(shape = JsonFormat.Shape.NUMBER_INT)
public enum SomeCode {
    VALUE0(0),
    VALUE1(1)

    private final Integer jsonValue;

    SomeCode(final Integer jsonValue) {
        this.jsonValue = jsonValue;
    }

    @JsonValue
    public Integer getJsonValue() {
        return this.jsonValue;
    }
}
```

I think following code should be generated into
```typescript
enum SomeCode {
    VALUE0 = 0,
    VALUE1 = 1
}
```

instead of:
```typescript

    type SomeCode = "VALUE0" | "VALUE1" ;
```

Because of jackson's JsonFormat and JsonValue annotations (also looks like we should run method annotated with JsonValue against every enum to get number for enum).

**Comment by vojtechhabarta** [comment]
Typescript-generator should support this and I will implement it.

Current workaround is to exclude such enum and thus mapping it to `any` type but this is not much helpful.

I have a concern about determining enum constant values dynamically by running user code because typescript-generator uses (and shoud use) static types and annotations but I don't see any other usable way how to do it.

**Comment by IRus** [comment]
I doesn't like idea of execution user's code too.
Another possible solution is to define meta data in annotations, or to define enums manually in configuration.

**Comment by vojtechhabarta** [comment]
Yes, I was thinking about defining enum values using annotations but this would require changing user code. So I decided to support standard Jackson 2 way even if it requires invoking user code.

Can you try it before I make release or do you need release?

**Comment by vojtechhabarta** [comment]
Part of [1.10.212 release](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.10.212).

**Comment by IRus** [comment]
Sorry, forget to write feedback. Works well in my use-cases.

Thanks a lot!
