### ISSUE TITLE
Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.31.861:generate (default-cli) on project rest: Execution default-cli of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.31.861:generate failed: No input classes found.

### ISSUE THREAD

**Issue by stefanLarie** [vojtechhabarta/typescript-generator#669]
<plugin>
				<groupId>cz.habarta.typescript-generator</groupId>
				<artifactId>typescript-generator-maven-plugin</artifactId>
				<version>2.31.861</version>
				<executions>
					<execution>
						<id>generate</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<phase>process-classes</phase>
					</execution>
				</executions>
				<configuration>
					<jsonLibrary>jackson2</jsonLibrary>
					<classes>
						<class>com.wout.user.RestUser</class>
					</classes>
					<outputKind>module</outputKind>
				</configuration>
			</plugin>

I have this added to my maven blugin and I want to do a rest, running generate typescript  task it gives me this error Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.31.861:generate (default-cli) on project rest: Execution default-cli of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.31.861:generate failed: No input classes found.
how to generate a typescript interface from my DTO project?   some help?

**Comment by vojtechhabarta** [comment]
Is your class `com.wout.user.RestUser` part of the project where `typescript-generator-maven-plugin` is run? If not you can add corresponding dependency. Or you can move typescript generator to project where are your DTO classes.

**Comment by stefanLarie** [comment]
yes it is! somehow the input classes are not funded

**Comment by vojtechhabarta** [comment]
I really don't know why it couldn't find your class. Maybe you could try different parameter for specifying input classes like [classPatterns](https://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#classPatterns) or [classesWithAnnotations](https://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#classesWithAnnotations).
