### ISSUE TITLE
gson parser doesn't insert optional parameters.

### ISSUE THREAD

**Issue by mr83-uw** [vojtechhabarta/typescript-generator#676]
When I add the optional parameters for the gson parser, nothing happens. When I look at the source code, it appears that the gson parser is not setup to look for the optionalProperties flag.

optionalProperties = 'all'
optionalPropertiesDeclaration = 'questionMark'

**Comment by vojtechhabarta** [comment]
I implemented this in 0841f94c6a5e2de85e6323a51140a5e3b2934feb. Gson parser now supports optional properties in a same way as other parsers. So not only `optionalProperties` set to `all` but also `useLibraryDefinition` (same as `all` in case of Gson) and also `useSpecifiedAnnotations`. Here is a description: [optionalProperties](https://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#optionalProperties).

**Comment by vojtechhabarta** [comment]
Released in [v2.32.889](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.32.889).
