### ISSUE TITLE
Please further clarify the code formatting part in README

### ISSUE THREAD

**Issue by linduan-textiq** [vojtechhabarta/typescript-generator#678]
I have some questions about the code formatting part in your readme:
1. `do not use wildcards`, what do you mean `wildcards` here. Is this something related to [wildcards in Java](https://www.geeksforgeeks.org/wildcards-in-java/) or importing wildcard?
2. `do not reformat whole files in IDE` what kind of reformat is this? 

Thanks a lot!

**Comment by vojtechhabarta** [comment]
1. wildcard (star) imports
2. preventing accidental changes to unrelated lines (indentation, spaces etc.)

I updated this in README.

**Comment by linduan-textiq** [comment]
Thanks for your quick response!
