### ISSUE TITLE
Order of Interface (base first, extension later) in the "implementationFile"

### ISSUE THREAD

**Issue by manish5377** [vojtechhabarta/typescript-generator#68]
Looking for switch to control the order of generated Interfaces in a way that would put "Base" interfaces before "Extended" interfaces.

Note: We are generating "implementationFile".

**Comment by vojtechhabarta** [comment]
So for these classes:
``` java
public class A {
}
public class B extends A {
}
```
you want generated interfaces to be in this order:
``` typescript
interface A {
}
interface B extends A {
}
```
Right?

Unfortunately there is no parameter for this but you can do it manually: If you want some interface to appear before other interfaces you can specify it using `classes` parameter and corresponding TypeScript interface will be before interfaces from `classPatterns`, `classesFromJaxrsApplication` and `classesFromAutomaticJaxrsApplication`.

**Comment by manish5377** [comment]
Sorry for the delayed reply.

Yes. What you have depicted is right. We have a complex hierarchy of java classes with single parent. So I just specify the top level parent and compete hierarchy is generated automatically by "typescript-generator" which is excellent. 

Over and above, I need "classes" to be generated (not interfaces), as I need to extend those in our Angular-2 front-end. This I can do with maven-replace plugin (just replace "interface" word with "class"). Now to enable this "Typescript" requires "Super" class to be defined before "Sub-class".

Hence the request. Thanks.

**Comment by vojtechhabarta** [comment]
I added [testInterfaceOrder()](https://github.com/vojtechhabarta/typescript-generator/blob/master/typescript-generator-core/src/test/java/cz/habarta/typescript/generator/Jackson2PolymorphismTest.java#L23) that demonstrates (and guarantees for future) that if root class is specified as input then it will appear before derived classes in generated file.

Example: for this Java class hierarchy:
``` java
@JsonSubTypes({
        @JsonSubTypes.Type(Y.class),
        @JsonSubTypes.Type(X.class)
})
public class Z {
}
public class Y extends Z {
}
public class X extends Z {
}
```
interfaces are generated in following order when class `Z` is specified as input using `classes` parameter
``` typescript
interface Z {
}
interface Y extends Z {
}
interface X extends Z {
}
```
Is your use case similar to this example? And does specifying root class using `classes` parameter work for you?

**Comment by manish5377** [comment]
This works for me. Thanks a lot.
