### ISSUE TITLE
Is it possible to generate multiple .d.ts files in a gradle build?

### ISSUE THREAD

**Issue by epernice** [vojtechhabarta/typescript-generator#70]
I have a large project where the server may have multiple classes with the same name.  Is it possible to configure multiple generateTypeScript tasks in my gradle build?  Then I could scope each task to certain files, and a different .d.ts file to avoid naming collisions in TS.

**Comment by vojtechhabarta** [comment]
Yes, that should be possible.
In Maven it is possible to configure multiple `<execution>` elements. I don't use Gradle but I would guess that calling `generateTypeScript` multiple times should work. Maybe some Gradle user can comment here.

**Comment by epernice** [comment]
Thanks!  I'm new to Gradle myself, but I think I got it working.  Maybe someone who knows Gradle better could chime in on whether there is a better solution.  I couldn't get it working with multiple generateTypeScript configurations - it would always just run the last one.  I had to create new tasks like this:

	task generateA(type:cz.habarta.typescript.generator.gradle.GenerateTask, dependsOn: [compileJava]) {
		outputFile = 'src/main/webapp/app/Models/ServerDtos/A.d.ts'
		// etc
	}

	task generateB(type:cz.habarta.typescript.generator.gradle.GenerateTask, dependsOn: [compileJava]) {
		outputFile = 'src/main/webapp/app/Models/ServerDtos/B.d.ts'
		// etc
	}

	task generateDtos(dependsOn: [generateA, generateB])
	classes.dependsOn generateDtos

And I run the generateDtos task and ignore the built-in generateTypeScript task

**Comment by vojtechhabarta** [comment]
Glad to see that you found some solution.
