### ISSUE TITLE
How to include spring artifact for plugin using Kotlin Gradle DSL

### ISSUE THREAD

**Issue by rvplauborg** [vojtechhabarta/typescript-generator#707]
```
plugins {
    id("cz.habarta.typescript-generator") version "2.32.889"
}

tasks {
  generateTypeScript {
    // different normal options here, including:
    generateSpringApplicationClient = true
  }
}
```

And in settings.gradle:
```
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "cz.habarta.typescript-generator") {
                useModule("cz.habarta.typescript-generator:typescript-generator-gradle-plugin:${requested.version ?: "+"}")
            }
        }
    }
}
```
I also have the spring dependency declared (`implementation(...)`)
But how do I include the Spring dependency for the plugin? There is no sample using the Gradle Kotlin DSL:
Error I get is:
> generateStringApplicationInterface' or 'generateStringApplicationClient' parameter was specified but 'cz.habarta.typescript.generator.spring.SpringApplicationParser$Factory' was not found. Please add 'cz.habarta.typescript-generator:typescript-generator-spring' artifact to typescript-generator plugin dependencies (not module dependencies).

I think just a minimal working example with gradle spring using Kotlin DSL would be a big help.

**Comment by nstdspace** [comment]
What was your solution? Why did you close the issue?
