### ISSUE TITLE
An Interface With Optional Properties (In Kotlin) Is Generated With Required Properties

### ISSUE THREAD

**Issue by dudiharush** [vojtechhabarta/typescript-generator#708]
Hi, i'm trying to generate from a Kotlin interface like:
`interface ISomeInterface {
   val someProp: String?;
}`
and i get
`interface ISomeInterface {
   someProp: string
}`
i expect "someProp" to be optional: `someProp?: string`

this is the config i have:
` <nullabilityDefinition>undefinedInlineUnion</nullabilityDefinition> `
if i add ` <optionalProperties>useLibraryDefinition</optionalProperties>` then all props are mapped as optional, even if they are not.

 it works well only with classes, but not with interfaces.

Thanks!

**Comment by aswiezowski** [comment]
Hi, I have similar/same issue with sealed classes. When I generate typescript from:
```
sealed class SealedClass {

    abstract val optionalList: List<String>?

    abstract val optional: String?
}

data class SealedClassImpl(override val optionalList: List<String>?, override val optional: String?) : SealedClass() {

}
```

I get:
```
export class SealedClass {
    optional: string;
    optionalList: string[];
}

export class SealedClassImpl extends SealedClass {
    optionalList: string[] | null;
    optional: string | null;
}
```
`SealedClassImpl` have incompatible definition of fields with super class. I'd expect everywhere type is nullable.

I created sample project with generation code: https://github.com/aswiezowski/typescript-generator-kotlin

**Comment by slively** [comment]
You may want to check the nullable property configuration options: https://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#nullabilityDefinition

Where I work we created an annotation called `@GenerateNullable` and put it on all nullable properties that typescript-generator converts.

**Comment by johnellinwood** [comment]
I have this same problem. But I'm trying to inherit from multiple interfaces, so I can't use the class workaround. Any other ideas?
