### ISSUE TITLE
Generation issue when JAXB element name contains paths

### ISSUE THREAD

**Issue by epernice** [vojtechhabarta/typescript-generator#71]
I've come across an issue when JAXB element names contain paths.  For example, consider this Java:

```
@XmlAccessorType(XmlAccessType.FIELD)
public class Person {
    @XmlElement(name = "LocationHistory/Addresses")
    private List<Address> addresses;

    // ...
}
```

This generates JSON that looks like the following:

```
{
    ...
    LocationHistory: {
        Addresses: [...]
    }
}
```

But the generated TypeScript is:

```
export interface Person {
    "LocationHistory/Addresses": Address[]
}
```

**Comment by vojtechhabarta** [comment]
@epernice you are right that generated declaration doesn't describe JSON correctly.
But it's not easy to fix it and to be honest I don't consider this high priority now.
However I am leaving this issue open.

**Comment by vojtechhabarta** [comment]
I don't plan to implements this. It is very special feature and according to #265 it seems JAXB itself is not much used these days for JSON processing.
