### ISSUE TITLE
Can't get rid of "Warning: Unknown serializer '(...) for class 'interface java.io.Serializable'"

### ISSUE THREAD

**Issue by ogerardin** [vojtechhabarta/typescript-generator#73]
OK I'm being a bit pedantic since the generated file is as expected, but I have a bunch of these warnings during the generation, and I don't seem to be able to get rid of them:

> Warning: Unknown serializer 'com.fasterxml.jackson.databind.ser.impl.UnknownSerializer' for class 'interface java.io.Serializable'

As you suggested [here](https://github.com/vojtechhabarta/typescript-generator/issues/62), I tried to exclude Serializable but it doesn't change anything.

Here's the relevant part of the POM:

 ```
              <plugin>
                <groupId>cz.habarta.typescript-generator</groupId>
                <artifactId>typescript-generator-maven-plugin</artifactId>
                <version>1.10.212</version>
                <executions>
                    <execution>
                        <id>generate-ts</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jsonLibrary>jackson2</jsonLibrary>
                    <classPatterns>
                        <classPattern>(edited)</classPattern>
                    </classPatterns>
                    <excludeClasses>
                        <class>java.io.Serializable</class>
                    </excludeClasses>
                    <outputFile>${project.basedir}/src/main/webapp/domain.d.ts</outputFile>
                    <outputKind>module</outputKind>
                </configuration>
            </plugin>
```

**Comment by vojtechhabarta** [comment]
1. Excluding `java.io.Serializable` worked for properties of type Serializable but not for classes implementing Serializable. I think I fixed this (will be part of next release).

2. Another option is to set `displaySerializerWarning` parameter to `false`.

**Comment by ogerardin** [comment]
Until the next release, option 2 did the trick. 
Thanks!
