### ISSUE TITLE
Error when generating class that has already been generated.

### ISSUE THREAD

**Issue by dan-madaket** [vojtechhabarta/typescript-generator#74]
This makes it impossible to generate classes that, for example:
- extend the same base class
- contain the same subclass
- really overlap in any other way

Rather than bottoming out, we should just skip the generation of a class if it already exists in the target file.

**Comment by vojtechhabarta** [comment]
@dan-madaket typescript-generator is designed to generate for each Java class just one TypeScript interface. Maybe you mean some bug or there is some misunderstanding. Could you be more specific? Ideally if you could paste here some example of 1. Java source classes, 2. current typescript-generator output, 3. expected output.

**Comment by vojtechhabarta** [comment]
Closing the issue (inactive for some time). Please reopen if needed.
