### ISSUE TITLE
Improve Documentation for nullableAnnotations

### ISSUE THREAD

**Issue by git9999999** [vojtechhabarta/typescript-generator#745]
Hi,
When i read the documentation, i am under the impression that with the Annotation @Nullable and the config
```  
<nullabilityDefinition>nullAndUndefinedUnion</nullabilityDefinition>
<nullableAnnotations>
    <nullableAnnotation>javax.annotation.Nullable</nullableAnnotation>
</nullableAnnotations>
```
the generator should create in TypeScript something like "string | null". 

Is this correct? If yes, some example would help.

I debugged the the code, an i saw that the config is taken
![image](https://user-images.githubusercontent.com/78401496/140024947-8ec4c52b-62f8-4974-bfa8-31f50b550ccc.png)

but the i got lost in the code :-(

I found this, but not sure if this helps
![image](https://user-images.githubusercontent.com/78401496/140024566-1d26fd4d-68b7-49ac-b9a7-153c08c5f331.png)

Cheers T

**Comment by FlorianCousin** [comment]
According to the documentation:

> nullAndUndefinedUnion - type alias Nullable<T> which is defined as union of T | null | undefined

As I understand it, the generator should then create in TypeScript something like `Nullable<string>`, with `Nullable<T>` defined as `T | null | undefined`.

I find it pretty clear but an example might be better indeed.

Also, the first part of your comment asks for the documentation to be clearer, and the second part uses a code debugger.
Could you please explain what are you debugging ?
What is your goal while doing so ?
Have you experienced any bug using the generator ?

Thank you for your contribution.

**Comment by git9999999** [comment]
Hi @FlorianCousin  
I can't remember what the problem was. 
I will close the Ticket.
Regards G
