### ISSUE TITLE
Support for jakarta.json.bind.annotation.JsonbTransient

### ISSUE THREAD

**Issue by jbaker-dstl** [vojtechhabarta/typescript-generator#751]
Currently, the plugin checks for transience of fields by looking for the `javax.json.bind.annotation.JsonbTransient` annotation:

https://github.com/vojtechhabarta/typescript-generator/blob/1d533d9466bfc1a79f31c5105408e5900281d96a/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/parser/JsonbParser.java#L246

However, the namespace has moved from `javax.json` to `jakarta.json` in the latest version of the JSON Binding API (https://github.com/eclipse-ee4j/jsonb-api/pull/217). This means any transient fields annotated with the new annotation are no longer picked up as transient by the plugin.

Could the plugin be updated to the new namespace, or even add support for both?

**Comment by rmannibucau** [comment]
Hi,

Think this one is fixed on master but no release hit central. @vojtechhabarta is it possible to push a release on central with jakarta support for JSON-B please?

Thanks

**Comment by vojtechhabarta** [comment]
Released in [v2.35.1025](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.35.1025).
