### ISSUE TITLE
Gradle generateTypeScript task fails if output folder does not exist

### ISSUE THREAD

**Issue by rikoe** [vojtechhabarta/typescript-generator#76]
I am using the Gradle generateTypeScript task as shown in the README, and it works great. If, however, I would like my typescript definitions to go to a sub-folder of the build folder that doesn't yet exist, I get the following error:

Execution failed for task ':generateTypeScript'.
> java.io.FileNotFoundException: C:\...\build\typescript\messages.d.ts (The system cannot find the path specified)

In this case I specified the outputFile property as ```outputFile = 'build/typescript/messages.d.ts'```

I don't know Gradle well enough to be able to add a custom "create directory" step before the generateTypeScript task is run.

How could I work around this issue?

**Comment by vojtechhabarta** [comment]
I modified typescript-generator so it creates missing output directory. I will make release soon.
(Workaround is to add some "create directory" step as you mentioned.)

**Comment by vojtechhabarta** [comment]
Fix is released (v1.10.220).

**Comment by rikoe** [comment]
Awesome, thanks for fixing this so quickly, just had the opportunity to test it and it works perfectly.
