### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by rgevrek** [vojtechhabarta/typescript-generator#77]
**Enum**s are turned into **type**s, but they could be turned into **enum**s in TypeScript, as in this following example:

`export enum MyEnum { el1, elem2 }`

instead of:

`export type MyEnum = "el1" | "elem2";`

**Comment by vojtechhabarta** [comment]
Main reason for this is that Java enum values are sent as strings in JSON. See #65 or other issues for more info.

**Comment by rgevrek** [comment]
Thank you for your answer, I've added the support for enums in this [pull request](https://github.com/vojtechhabarta/typescript-generator/pull/78)

**Comment by hypery2k** [comment]
is it possible to release the enum extension ?

**Comment by vojtechhabarta** [comment]
I don't want to add this feature as core functionality for two reasons:
1. As I mentioned TypeScript enums are **number** based but Java enums are sent as **strings** in JSON.
2. TypeScript enums (even with `const` keyword) don't work well in declaration files (`.d.ts`).

Here is example for point 2:
_Declaration file with enum_
```
// enums.d.ts
export const enum Direction {
     North, East, South, West
}
```
_Implementation file which uses the enum_
```
// test.ts
import * as enums from "./enums";
const value: enums.Direction = enums.Direction.East;
console.log(value);
```

If you run TypeScript compiler it successfully generates `test.js` file but this file fails in runtime (using `node test.js`). I can describe this in more details if you want or you can try it and check what TypeScript generates and why it fails.

@rgevrek If you really want to have this functionality despite mentioned drawbacks you can change your PR to contain just an extension (and not `typescriptEnums` core option).

I would also like to hear from you guys the motivation for this feature. Maybe I will convince you that you don't need it ;-)

**Comment by ollwenjones** [comment]
If all one does is pass "ENUM_VAUE" strings around the client, and all you want is typescript to complain if you misspell something, then 
```TypeScript
type MyEnum = "BOB" | "SALLY" | "JIM";
```
is fine, but if you want to do some normal enum opration, i.e. compare those things as enums, for instance:
```TypeScript
    let person = "BOB";
    if (person === MyEnum.BOB) {
```
you can't do that.

would be nice if it was an object that presented itself as if it were a Java enum:
```JavaScript
const MyEnum {
  BOB: 'BOB', //etc.
...
```
but that doesn't work in a `.d.ts`

**Comment by vojtechhabarta** [comment]
@ollwenjones you are right, you can for example accidentally compare value with misspelled string without any error from compiler:
``` typescript
type MyEnum = "BOB" | "SALLY" | "JIM";
let person: MyEnum;
if (person === "BOP") {
}
```
But you can have constants for enum values in addition to enum union:
``` typescript
type MyEnum = "BOB" | "SALLY" | "JIM";
const MyEnum = {
    BOB: <MyEnum>"BOB",
    SALLY: <MyEnum>"SALLY",
    JIM: <MyEnum>"JIM",
}
let person: MyEnum;
if (person === MyEnum.BOB) {
}
person = MyEnum.JIM;
```
Unfortunately this only works in `.ts` (not in `.d.ts`).
There is `cz.habarta.typescript.generator.ext.EnumConstantsExtension` extension (by @ryan10132 - #33, #34) which generates these constants.

What do you think?

Anyway it seems there is an interest in mapping Java enums to TypeScript enums so lets introduce this feature.

**Comment by ollwenjones** [comment]
@vojtechhabarta the const is handy, especially if it is also auto-generated by an extension (thanks for the tip on that!). Alternatively a colleague just pointed out that we _can_ get the enum string from a TypeScript enum. From the docs:
>
Enums are real objects that exist at runtime. One reason is the ability to maintain a reverse mapping from enum values to enum names.
```
enum Enum {
    A
}
let a = Enum.A;
let nameOfA = Enum[Enum.A]; // "A"
```
>

That would be work using @rgevrek's PR code as well. the const generation would make for more elegant code, but those would have to be imported instead of installed with `typings` - more things for me to think about.

**Comment by vojtechhabarta** [comment]
@ollwenjones since enum values to enum names mapping (and vice versa) only works in `.ts` files I prefer not to do string to enum transformation and use string values directly. String literal unions types (`"BOB" | "SALLY" | "JIM"`) exactly describes this.

In general I think it is not necessary to have same type safety as in Java. TypeScript is just different and has other features which Java lacks.

**Comment by vojtechhabarta** [comment]
I committed Java enum to TypeScript enum feature and I would appreciate feedback from anybody before making a release.

**Comment by rgevrek** [comment]
Hi,

after I tested and worked with different variants. Using const is the best option for a interconnection between a web service and TypeScript models. But for a syntax check you need to add for each attribute of the const an:

as EnumType

So if we append this in the extension, it will be greate.
Thank you!

**Comment by rgevrek** [comment]
Thank you for your advices I will test these in the following days.

**Comment by ollwenjones** [comment]
> In general I think it is not necessary to have same type safety as in Java
This could be true, but I tend to avoid passing naked strings around, even when writing pure JavaScript - there's just a comfort level that comes with `MyFakeEnumObj.VALUE`

The other angle on using strings directly is having to maintain them in the UI code, versus having them handed to us by a generation tool. :wink: 

Lots of pros and cons, and I realize things are getting fairly subjective. Thank you again for this tool, and for the consideration and feedback on this topic.

**Comment by vavasilev** [comment]
Hello, the enums fix is cool and I'd like to use it. When will a version be available in the central maven repository?

**Comment by vavasilev** [comment]
I have another problem. To use enums in Angular 2 template you have to do something like this in the controller: private Mode = Mode; (here Mode is an enum). But this does not work with const enums. Is it possible that "const" is configurable?

**Comment by vojtechhabarta** [comment]
@vavasilev for Angular template you need enums which exist in runtime. This means enums without `const` keyword AND contained in runnable `.js` file. In other words having enums just in `.d.ts` is not sufficient, either `.js`+`.d.ts` or `.ts` (which is compiled to `.js`) is needed.

I don't want to add features which don't work in declaration files (`.d.ts`) to typepescript-generator as a **core** feature. However we can create **extension** which could generate enums without `const` keyword to implementation files (`.ts`).

**Comment by vavasilev** [comment]
Thanks for the suggestion. I took a look at the code, but I do not see how I could disable the default generation. Does it mean that I will have the enums twice in the final output?

**Comment by vojtechhabarta** [comment]
Yes, you are right. I have to make it possible to disable default enum handling. I will let you know.

**Comment by vavasilev** [comment]
Great!

**Comment by vojtechhabarta** [comment]
It seems that in TypeScript 2.0 we will not need to map Java enums to TypeScript enums with string constants.

Following screenshot shows that TypeScript 2.0 compiler is more strict than version 1.8 and flags comparison with wrong string literal.

![stringliteralsts20-dark](https://cloud.githubusercontent.com/assets/1191407/18730019/72022478-8054-11e6-870c-b8e54bd638e7.PNG)

This is really cool for me and I think that union of string literals (`"Left" | "Right"`) in TypeScript 2.0 is actually better than enum with string constants and it works in declaration files (`.d.ts`). What do you think @rgevrek @ollwenjones @vavasilev?

**Comment by vavasilev** [comment]
For me it is cool that you cannot enter wrong string, but still you do not have the hint, when you write the enum name and press dot.

**Comment by vojtechhabarta** [comment]
@vavasilev I added `cz.habarta.typescript.generator.ext.NonConstEnumsExtension` which generates enums without `const` keyword. Could you please check if it does what's expected?

**Comment by ollwenjones** [comment]
@vojtechhabarta - sorry late to the game. The 2.0 improvements are good, but the use-cases for having a TypeScript enum, or something like it (run-time comparison, not just compile-time comparison) are more important to me.

If I had to have either a TypeScript enum ( no string constants ) or the string literal types, i would chose the enums.

Thanks again for the consideration on this.

**Comment by vojtechhabarta** [comment]
Closing.
#83 is part of [1.11.232](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.11.232) release.
