### ISSUE TITLE
maven plugin, problem with configuration

### ISSUE THREAD

**Issue by froux** [vojtechhabarta/typescript-generator#80]
Hi, 

I have setup my project with your plugin (by pasting it from doc and changing Pojo classes) but a message appears : 
`Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.10.220:generate (default-cli) on project ConfOnline: The parameters 'outputFile', 'outputKind', 'jsonLibrary' for goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.10.220:generate are missing or invalid`

configuration is 
```
<jsonLibrary>jackson2</jsonLibrary>       
<classesFromJaxrsApplication>fr.test.MyApp</classesFromJaxrsApplication>
<outputFile>target/sample.d.ts</outputFile>
<outputKind>module</outputKind>
```

I have checked following things : 

- jackson2 is imported (I've tried with same version than in your example).
- outputFile : checked that target folder exists, try also by adding an empty sample.d.ts file
- outputKind : try the 3 authorized values without success
- classes : I tried to provide just a simple class with classes instead of classesFromJaxrs.

What am I missing ?

**Comment by vojtechhabarta** [comment]
Hi @froux, it si not a problem with parameters you mentioned but with configuration itself. Can you paste your `pom.xml` (or some relevant part)?

**Comment by froux** [comment]
here it is  : 
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>Lapeyre</groupId>
  <artifactId>ConfOnline</artifactId>
  <packaging>war</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>ConfOnline Maven Webapp</name>
  <url>http://maven.apache.org</url>

  <dependencies>
    
    
    
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-undertow</artifactId>
      <version>3.0.10.Final</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.logging</groupId>
      <artifactId>jboss-logging</artifactId>
      <version>3.3.0.Final</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.undertow</groupId>
      <artifactId>undertow-core</artifactId>
      <version>1.4.0.Final</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.undertow</groupId>
      <artifactId>undertow-servlet</artifactId>
      <version>1.4.0.Final</version>
      <scope>test</scope>
    </dependency>

    
    
    
    
    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-jaxrs</artifactId>
      <version>3.0.10.Final</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-client</artifactId>
      <version>3.0.10.Final</version>
      <scope>provided</scope>
    </dependency>

    

    
    
    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-multipart-provider</artifactId>
      <version>3.0.10.Final</version>
      <scope>provided</scope>
    </dependency>

    
    
    
    
    

    
    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>async-http-servlet-3.0</artifactId>
      <version>3.0.10.Final</version>
      <scope>provided</scope>
    </dependency>
    
    
    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-jackson2-provider</artifactId>
      <version>3.0.10.Final</version>
    </dependency>
    <dependency>
      <groupId> com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.8.2</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.jaxrs</groupId>
      <artifactId>jackson-jaxrs-json-provider</artifactId>
      <version>2.8.2</version>
    </dependency>
    <dependency>
      <groupId>org.jdom</groupId>
      <artifactId>jdom2</artifactId>
      <version>2.0.6</version>
    </dependency>
	<dependency>
      <groupId>org.jboss.spec.javax.servlet</groupId>
      <artifactId>jboss-servlet-api_3.1_spec</artifactId>
      <version>1.0.0.Final</version>
    </dependency>
    
    
    <dependency>
      <groupId>cz.habarta.typescript-generator</groupId>
      <artifactId>typescript-generator-core</artifactId>
      <version>1.10.220</version>
    </dependency>
    <dependency>
      <groupId>cz.habarta.typescript-generator</groupId>
      <artifactId>typescript-generator-maven-plugin</artifactId>
      <version>1.10.220</version>
    </dependency>

  </dependencies>
  <build>
    <finalName>ConfOnline</finalName>
    <plugins>
      <plugin>
        <groupId>cz.habarta.typescript-generator</groupId>
        <artifactId>typescript-generator-maven-plugin</artifactId>
        <version>1.10.220</version>
        <executions>
          <execution>
            <id>generate</id>
            <phase>process-classes</phase>
            <configuration>
              <jsonLibrary>jackson2</jsonLibrary>
              <classesFromJaxrsApplication>fr.lapeyre.conf.rest.LapeyreConfiguratorApp</classesFromJaxrsApplication>
              <outputFile>target/sample.d.ts</outputFile>
              <outputKind>global</outputKind>
              <namespace>Rest</namespace>
            </configuration>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
`

**Comment by froux** [comment]
Just a precision, I've download your project and try to simply open "sample-maven" project with Intellij and the message is the same :(

**Comment by vojtechhabarta** [comment]
Your pom.xml looks good. I tried it and typescript-generator started successfully. (I have Maven version 3.3.9.)
Can you run following commands?
``` shell
mvn --version
mvn install
```

**Comment by sousarka** [comment]
@froux: Can you please try to put the `configuration` element outside the `executions` tag. I had the exact problem and got it working with that. See my pom snippet:
```
			<plugin>
				<groupId>cz.habarta.typescript-generator</groupId>
				<artifactId>typescript-generator-maven-plugin</artifactId>
				<version>1.10.220</version>
				<executions>
					<execution>
						<id>generate</id>
						<phase>process-classes</phase>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<jsonLibrary>jackson2</jsonLibrary>
					<classes>
						<class>com.xy.model.Item</class>
					</classes>
					<outputFile>target/Item.d.ts</outputFile>
					<outputKind>global</outputKind>
				</configuration>
			</plugin>
```
@vojtechhabarta : Thank you for the awesome tool.

**Comment by froux** [comment]
Ok this finally works ! It was a problem in my maven install. I had a mess between embedded maven in Intellij and installed maven. This is fixed. Thank you for your help and your wonderful tool !

**Comment by vojtechhabarta** [comment]
@froux @sousarka thanks for sharing the issue, might be useful for other users too

**Comment by emreavsar** [comment]
@sousarka's solution works perfectly. please update the doc if not done yet. i had the same problem (also update your answer on stackoverflow, which brings lots of people to this github repo. http://stackoverflow.com/a/36225867/557335)

cheers

**Comment by vojtechhabarta** [comment]
@emreavsar do you know why `<configuration>` inside `<executions>` doesn't work? Is it caused by specific Maven version? Which version are you using? (`mvn --version`)

**Comment by emreavsar** [comment]
```
mvn --version                                                                                                                                                                                                                    
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
```

**Comment by vojtechhabarta** [comment]
That's strange I have exactly the same version and it works for me.
And how do you run typescript-generator? As part of `mvn install`?

**Comment by emreavsar** [comment]
nope, only the generate itself: ```mvn typescript-generator:generate```

**Comment by emreavsar** [comment]
So currently I'm facing the issue that on my jenkins I have maven with version 3.2.5 and on my dev machine i have 3.3.9. And the build fails because of poor configuration.

=> Is this a **bug** of the plug-in or did it just change? What do you think @vojtechhabarta ?

**Comment by vojtechhabarta** [comment]
What is the problem with Maven 3.2.5? I haven't tested typescript-generator on older Maven versions for a long time but it should work.

**Comment by emreavsar** [comment]
It was something like that there is no `<configuration>` tag found in `<execution>`, I cannot find the build logs anymore.
