### ISSUE TITLE
Create Input interface to enable extensibility

### ISSUE THREAD

**Issue by sygour** [vojtechhabarta/typescript-generator#85]
Using typescript generator with an annotation processor is currently impossible: during this process, classes are not yet loaded, you only have `javax.lang.model.element.TypeElement`.

It would be really convenient to have an interface for Input (used in `generateTypeScript` method), so one can implement its own Input (for me it would be from `TypeElement`, it could be from text files, but you could imagine something more fancy even).

**Comment by vojtechhabarta** [comment]
Typescript-generator uses reflections and works with `java.lang.reflect.Type` and derived classes and interfaces. I don't think having flexibility on input side solves anything. It would be needed to rework (and generalize) big portions of the tool.

Or have I misunderstand your intent?

**Comment by sygour** [comment]
No, you understood correctly...
Do you think it would be an interesting rework?

I guess I'll try using the generator instead of the core itself.
Thanks for the reply! (and the work done!)

**Comment by vojtechhabarta** [comment]
Typescript-generator is still based on reflections directly and also indirectly (it uses libraries like Jackson2) and I don't plan to generalize it to work as annotation processor.
Thanks
