### ISSUE TITLE
Classes from different artifacts

### ISSUE THREAD

**Issue by tux4ever** [vojtechhabarta/typescript-generator#90]
It would be great if we can generate typescript definitions from third party libraries which are included in the maven dependencies.

e.g. pom dependency

```
<dependency>
  <groupId>com.sample</groupId>
   <artifactid>api</artifactid>
</dependency>
```
Something like would be helpful

```
<configuration>
     <classes>
          <class>classpath:at.porscheinformatik.cpi.garage.api.dto.CarlistDTO</class>
          <classpath>at.porscheinformatik.cpi.garage.api.dto.CarlistDTO</classpath>
      </classes>
</configuration>
```

**Comment by vojtechhabarta** [comment]
@tux4ever It should be already possible. Add `<dependency>` with classes from which you want to generate TypeScript declaration file (as in your example) and configure typescript-generator like this:

``` xml
<configuration>
    <classes>
        <class>at.porscheinformatik.cpi.garage.api.dto.CarlistDTO</class>
    </classes>
</configuration>
```

**Comment by tux4ever** [comment]
Thank you for your answer - You are right it works well!
