### ISSUE TITLE
JsonTypeInfo and nested interfaces

### ISSUE THREAD

**Issue by ollwenjones** [vojtechhabarta/typescript-generator#91]
Having trouble with `JsonTypeInfo` generation in the output, for example:

```Java
// Java
@JsonTypeInfo(use = Id.NAME, include = As.PROPERTY, property = "beanTypeName")
public interface HasId {

  /**
   * @return the unique identifier
   */
  IdClass getId();
	
}

// results in TypeScript:
export interface IProvidesDetail extends HasId {
  beanTypeName: "IProvidesDetail";
  /**
    * @return id of the home group
    */
  detail: IdClass;
}

// which is okay, except lots of other interfaces extend IProvidesDetail

export interface IProvidesName extends IProvidesDetail {
  beanTypeName: "IProvidesName"; // TypeScript error: "IProvidesName" != "IProvidesDetail"

  name: string;
}
```

Open to any input here, as it's likely I've configured something wrong.
I would be okay with leaving that piece of `@JsonTypeInfo` off, or it could always be `string`, etc.

**Comment by vojtechhabarta** [comment]
Probably typescript-generator should not generate `beanTypeName` property for Java interfaces, only for classes (to describe Jackson behavior closely). For Java classes it is working correctly, I think.
I will look into it.

**Comment by ollwenjones** [comment]
Many thanks. That sounds right to me, too. 

For interfaces it found a discreet class set for, it seemed to generate the right string literals. e.g.
```TypeScript
export interface Thing {
  beanTypeName: "thingOne | thingTwo | thingThree";
  ...
}
```
Which seems to be as intended.
The problem was only with layers of interfaces.

**Comment by vojtechhabarta** [comment]
I committed fix to master. Could you please try it?

**Comment by ollwenjones** [comment]
I'll try it shortly.

**Comment by ollwenjones** [comment]
That made a huge difference. 👍 The remaining `JsonTypeInfo` related errors were due the an abstract class, which I didn't realize before. It seems like it accounts for class inheritance in other cases. Could we skip them for abstract classes as well as interfaces?

**Comment by ollwenjones** [comment]
was thinking `!Modifier.isAbstract(sourceClass.type.getModifiers())` in Jackson2Parser.java:92, but that fails `GenericsTest` 😛

**Comment by ollwenjones** [comment]
If I adjust that test expectation to
```TypeScript
export interface IA extends IB<string> {
}

export interface IB<T> {
    type: string;
    x: T;
}
```
Everything works for me, and this seems correct, since `IB` is a `@JsonTypeInfo` annotated interface, and `IA` is an abstract class.

**Comment by vojtechhabarta** [comment]
You are right this is more logical since neither interface nor abstract class can be instantiated.
Thanks

**Comment by vojtechhabarta** [comment]
Part of [1.13.241](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.13.241) release.
