### ISSUE TITLE
Support for Jakarta EE / Java EE bean validation annotations

### ISSUE THREAD

**Issue by Tr1ple-F** [vojtechhabarta/typescript-generator#997]
We are currently facing the issue that the package doesn't recognise the `@NotNull` field annotation from Jakarta / Java EE and therefore makes each field required which not necessary. In fact all fields should be optional and only the fields with the tag `@NotNull` should be required. An option to support this typing would solve this issue.

**Comment by JoaoBrlt** [comment]
Hey :wink: I think you can already do this using the [`requiredAnnotations`](https://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#requiredAnnotations) parameter.

**Comment by Tr1ple-F** [comment]
Yes, thanks that works
